Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMainBusiness_Ctrl.cls
@isTest 
private class TestMainBusiness_Ctrl {
    @testsetup static void setup()
    {
        Test.startTest();
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;
        Test.stopTest();
    
    }
    //mainBusiness_UnitTest needs to be removed once test class has been written for Previous_Balance_Ctrl and ProcessorInformation_Ctrl
/*    static testMethod void mainBusiness_UnitTest() {
        Test.startTest(); 
        // DS-CONAM CALC.apexTesting();
         DS-CONAM
       // Account acc = TestUtils.createAccount();
      //  Campaign cm = TestUtils.createCampaign();
       // Opportunity opp = TestUtils.createOpportunity(acc, cm);
       
        
        
        
        ProcessorInformation_Ctrl proObj = new ProcessorInformation_Ctrl();
        proObj.doSave();
        Previous_Balance_Ctrl  balObj1 = new Previous_Balance_Ctrl();
        balObj1.doSave();
       // MainBusiness_Ctrl bussObj1 = new MainBusiness_Ctrl();
        //bussObj1.doSave();
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
       // MainBusiness_Ctrl bussObj = new MainBusiness_Ctrl();
     //   bussObj.doSave();
        Previous_Balance_Ctrl  balObj = new Previous_Balance_Ctrl();
        balObj.doSave();
        ProcessorInformation_Ctrl proObj1 = new ProcessorInformation_Ctrl();
        proObj1.doSave();
        Test.stopTest();
    }
    
   
    
    static testMethod void unitTest3() {
        Test.startTest();       
        // DS-CONAM CALC.apexTesting();

        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        
        
        PageReference p=Page.MainBusinessPage;
        Test.setCurrentPage(p); 
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(opp);
        MainBusiness_Ctrl bussObj1 = new MainBusiness_Ctrl();
        bussObj1.doSave();
        
        
        
        
        ProcessorInformation_Ctrl proObj = new ProcessorInformation_Ctrl();
        proObj.doSave();
        Previous_Balance_Ctrl  balObj1 = new Previous_Balance_Ctrl();
        balObj1.doSave();
        
        
        MainBusiness_Ctrl bussObj = new MainBusiness_Ctrl();
        bussObj.doSave();
        Previous_Balance_Ctrl  balObj = new Previous_Balance_Ctrl();
        balObj.doSave();
        ProcessorInformation_Ctrl proObj1 = new ProcessorInformation_Ctrl();
        proObj1.doSave();
        Test.stopTest();
    }
    */ 
     static testMethod void unitTest() {
        Test.startTest(); 
        // DS-CONAM CALC.apexTesting();

        Opportunity opp=[select
                                id
                        from 
                                opportunity
                        where
                                name='testOpportunity' Limit 1];
        
        PageReference p=Page.MainBusinessPage;
        Test.setCurrentPage(p); 
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(opp);
        MainBusiness_Ctrl bussObj1 = new MainBusiness_Ctrl();
        bussObj1.doSave();
        
        Test.stopTest();
     }
     
     static testMethod void unitTest2() {
        Test.startTest(); 
        // DS-CONAM CALC.apexTesting();
       
        Campaign  cm=[select
                                id
                        from 
                                Campaign  
                        where
                                name='Test' Limit 1];
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        insert opp;
        
        PageReference p=Page.MainBusinessPage;
        Test.setCurrentPage(p); 
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(opp);
        MainBusiness_Ctrl bussObj1 = new MainBusiness_Ctrl();
        bussObj1.doSave();
        
        Test.stopTest();
     }  
}