Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DBA__c</fullName>
        <inlineHelpText>&quot;Doing Business As&quot; Name</inlineHelpText>
        <label>DBA (if different from Account Name)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Purged_Account_Name__c</fullName>
        <label>Purged Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purged_DBA_Name__c</fullName>
        <label>Purged DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purged_Legal_Name__c</fullName>
        <label>Purged Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <label>Legal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purged_Company_Name__c</fullName>
        <label>Purged Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purged_Legal_Business_Name__c</fullName>
        <label>Purged Legal Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Purge_characters_in_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list will contain all the characters or the strings that are to be eliminated from the account name and lead company name</description>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Replace_With__c</fullName>
        <label>Replace With</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Purge characters in Name</label>
</CustomObject>

Rapid Prd/src/classes/PurgeNameHelper.cls
public class PurgeNameHelper
{

    public static void cleanAccountName(List<Account> accList)
    {
        List<Purge_characters_in_Name__c> pcinList=[Select
                                                                name, character__c, replace_with__c
                                                        from 
                                                                 Purge_characters_in_Name__c Limit 100];
        for(Account accTemp : accList)
        {
            String str=accTemp.Legal_Name__c!=null ? String.escapeSingleQuotes(accTemp.Legal_Name__c).toLowerCase() : '';
            String bstr=accTemp.dba__c!=null ? String.escapeSingleQuotes(accTemp.dba__c).toLowerCase() : '';
            String accName=accTemp.name.toLowerCase();
        
        for(Purge_characters_in_Name__c pTemp : pcinList)
        {
            String lvalue=pTemp.character__c.toLowerCase();
            String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();                    
            
            if(str.indexOf(lvalue)!=-1)
            {  
                String regexPattern;
                if(lvalue.length()==1)
                {
                    regexPattern='\\'+lvalue;
                    str=str.replaceAll(regexPattern,rValue);
                }
                else
                { //if the string is the last string
                    if(str.endsWith(lvalue))
                        regexPattern='\\ '+lvalue;
                    else
                        regexPattern='\\ '+lvalue+' ';
                    str=str.replaceAll(regexPattern, ' '+rvalue+' ');
                }
            }
            
            if( bstr.indexOf(lvalue)!=-1)
            {    
                String regexPattern;
                if(lvalue.length()==1)
                {
                    regexPattern='\\'+lvalue;
                    bstr=bstr.replaceAll(regexPattern,rValue);
                }
                else
                { 
                    if(bstr.endsWith(lvalue))
                        regexPattern='\\ '+lvalue;
                    else
                        regexPattern='\\ '+lvalue+' ';
                    bstr=bstr.replaceAll(regexPattern, ' '+rvalue+' ');
                }
            }

            if( accName.indexOf(lvalue)!=-1)
            {    
                String regexPattern;
                if(lvalue.length()==1)
                {
                    regexPattern='\\'+lvalue;
                    accName=accName.replaceAll(regexPattern,rValue);
                }
                else
                { 
                    if(accName.endsWith(lvalue))
                        regexPattern='\\ '+lvalue;
                    else
                        regexPattern='\\ '+lvalue+' ';
                    
                    accName=accName.replaceAll(regexPattern, ' '+rvalue+' ');
                }
            }
        }
        
        str=str.replaceAll('space', '');
        str=str.replaceAll(' ', '');
        str=str.replaceall('_','');
        str=str.replaceall('[^\\w\\s]','');
        for(Purge_characters_in_Name__c pTemp : pcinList)
        {
            String lvalue=pTemp.character__c.toLowerCase();
            String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();       
            if(lvalue.length()>1)
            {
                if(str.endsWith(lvalue))
                {
                    str=str.replace(lvalue, rvalue);
                }
            }
        }
        accTemp.Purged_Legal_Name__c=str.toLowerCase();
        
        bstr=bstr.replaceAll('space', '');
        bstr=bstr.replaceAll(' ', '');
        bstr=bstr.replaceall('_','');
        bstr=bstr.replaceall('[^\\w\\s]','');
        for(Purge_characters_in_Name__c pTemp : pcinList)
            {
                String lvalue=pTemp.character__c.toLowerCase();
                String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();       
                if(lvalue.length()>1)
                {
                    if(bstr.endsWith(lvalue))
                    {
                        bstr=bstr.replace(lvalue, rvalue);
                    }
                }
            }
        accTemp.Purged_DBA_Name__c=bstr.toLowerCase();  
        System.debug('accName.Purged_DBA_Name__c' +bstr.toLowerCase());
        accName=accName.replaceAll('space', '');
        accName=accName.replaceAll(' ', '');
        accName=accName.replaceall('_','');
        accName=accName.replaceall('[^\\w\\s]','');
        for(Purge_characters_in_Name__c pTemp : pcinList)
        {
            String lvalue=pTemp.character__c.toLowerCase();
            String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();       
            if(lvalue.length()>1)
            {
                if(accName.endsWith(lvalue))
                {
                    accName=accName.replace(lvalue, rvalue);
                }
            }
        }
        accTemp.Purged_Account_Name__c=accName.toLowerCase();
        System.debug('accName.toLowerCase()' +accName.toLowerCase());
        
        }

    }
    
    public static void cleanLeadCName(List<Lead> leadList)
    {
        List<Purge_characters_in_Name__c> pcinList=[Select
                                                            name, character__c, replace_with__c
                                                    from 
                                                            Purge_characters_in_Name__c Limit 100];
        for(Lead lTemp : leadList)
        {
            String str=lTemp.company!=null ? String.escapeSingleQuotes(lTemp.company).toLowerCase() : '';
            String bstr=lTemp.Legal_Business_Name__c!=null ? String.escapeSingleQuotes(lTemp.Legal_Business_Name__c).toLowerCase() : '';
        
            for(Purge_characters_in_Name__c pTemp : pcinList)
            {
                String lvalue=pTemp.character__c.toLowerCase();
                String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();                    

                if(str.indexOf(lvalue)!=-1)
                {    
                    String regexPattern;
                    if(lvalue.length()==1)
                    {
                        regexPattern='\\'+lvalue;
                        str=str.replaceAll(regexPattern,rValue);
                    }
                    else
                    { 
                        if(str.endsWith(lvalue))
                            regexPattern='\\ '+lvalue;
                        else
                            regexPattern='\\ '+lvalue+' ';
                        str=str.replaceAll(regexPattern, ' '+rvalue+' ');
                    }
                
                }
                if(bstr.indexOf(lvalue)!=-1)
                {    
                    String regexPattern;
                    if(lvalue.length()==1)
                    {
                        regexPattern='\\'+lvalue;
                        bstr=bstr.replaceAll(regexPattern,rValue);
                    }
                    else
                    { 
                        if(bstr.endsWith(lvalue))
                            regexPattern='\\ '+lvalue;
                        else
                            regexPattern='\\ '+lvalue+' ';
                            
                        bstr=bstr.replaceAll(regexPattern, ' '+rvalue+' ');
                    }
                }
            }
            str=str.replaceAll('space', '');
            str=str.replaceAll(' ', '');
            str=str.replaceall('_','');
            str=str.replaceall('[^\\w\\s]','');
            for(Purge_characters_in_Name__c pTemp : pcinList)
            {
                String lvalue=pTemp.character__c.toLowerCase();
                String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();       
                if(lvalue.length()>1)
                {
                    if(str.endsWith(lvalue))
                    {
                        str=str.replace(lvalue, rvalue);
                    }
                }
            } 
            lTemp.Purged_Company_Name__c=str.toLowerCase();
            
            bstr=bstr.replaceAll('space', '');
            bstr=bstr.replaceAll(' ', '');
            bstr=bstr.replaceall('_','');
            bstr=bstr.replaceall('[^\\w\\s]','');
            for(Purge_characters_in_Name__c pTemp : pcinList)
            {
                String lvalue=pTemp.character__c.toLowerCase();
                String rValue=pTemp.replace_with__c==null ? '':  pTemp.replace_with__c.toLowerCase();       
                if(lvalue.length()>1)
                {
                    if(bstr.endsWith(lvalue))
                    {
                        bstr=bstr.replace(lvalue, rvalue);
                    }
                }
            } 
            lTemp.Purged_Legal_Business_Name__c=bstr.toLowerCase();    
                    
        }
    }  

}