Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Purged_DBA_Name__c</fullName>
        <label>Purged DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purged_Legal_Name__c</fullName>
        <label>Purged Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/BatchUpdateAccountPurgeDetails.cls
global class BatchUpdateAccountPurgeDetails implements Database.Batchable<sObject>
{
    global DataBase.QueryLocator start(DataBase.BatchableContext bc)
    {
        return Database.getQueryLocator('Select id from Account where (Purged_Legal_Name__c=\'\' or Purged_DBA_Name__c=\'\')');
    }
    
    global void execute(DataBase.BatchableContext  bc , List<Account > scope)
    {
        List<Account > upList=new List<Account >();
        for( Account lTemp : scope)
        {    
            
            upList.add(lTemp );
        }
        
        if(upList.size()>0)
            update upList;
    }
    
    global void finish(DataBase.BatchableContext  bc)
    {
    }
}