Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>GreenTree</fullName>
        <active>true</active>
        <businessProcess>GreenTree</businessProcess>
        <label>GreenTree</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestOppTrackGTFStageChanges.cls
@isTest

private class TestOppTrackGTFStageChanges {

    public static testMethod voId oppTrackGTFStageChangesTest1() {

        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp1 = new Opportunity();
        gOpp1.name = 'oppname1';
        gOpp1.accountId = ac.Id;
        gOpp1.RecordTypeId = gId.get(0).Id;
        gOpp1.ForecastCategoryName = 'Commit';
        gOpp1.LeadSource = 'A001';
        gOpp1.CampaignId = cp.Id;
        gOpp1.CloseDate = system.today();
        gOpp1.Current_Processor__c = '1st federal financial';
        gOpp1.StageName = 'Initial Call Needed';
        insert gOpp1;

        Green_Tree_Oppy_Extension__c gt1 = new Green_Tree_Oppy_Extension__c();
        gt1.opportunity__c = gOpp1.Id;
        insert gt1;

        
        update gOpp1;
    }

    public static testMethod voId oppTrackGTFStageChangesTest2() {

        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;
        Opportunity gOpp2 = new Opportunity();
        gOpp2.name = 'oppname2';
        gOpp2.accountId = ac.Id;
        gOpp2.RecordTypeId = gId.get(0).Id;
        gOpp2.ForecastCategoryName = 'Commit';
        gOpp2.LeadSource = 'A001';
        gOpp2.CampaignId = cp.Id;
        gOpp2.CloseDate = system.today();
        gOpp2.Current_Processor__c = '1st federal financial';
        gOpp2.StageName = 'Initial Call Needed';
        insert gOpp2;

        Green_Tree_Oppy_Extension__c gt2 = new Green_Tree_Oppy_Extension__c();
        gt2.opportunity__c = gOpp2.Id;
        insert gt2;

        
        update gOpp2;
        test.stopTest();
    }

    public static testMethod voId oppTrackGTFStageChangesTest3() {
        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp3 = new Opportunity();
        gOpp3.name = 'Goppname3';
        gOpp3.accountId = ac.Id;
        gOpp3.RecordTypeId = gId.get(0).Id;
        gOpp3.ForecastCategoryName = 'Commit';
        gOpp3.LeadSource = 'A001';
        gOpp3.CampaignId = cp.Id;
        gOpp3.CloseDate = system.today();
        gOpp3.Current_Processor__c = '1st federal financial';
        gOpp3.StageName = 'Initial Call Needed';
        insert gOpp3;

        Green_Tree_Oppy_Extension__c gt3 = new Green_Tree_Oppy_Extension__c();
        gt3.opportunity__c = gOpp3.Id;
        insert gt3;

        
        
        Test.stopTest();
    }
    public static testMethod voId oppTrackGTFStageChangesTest4() {
        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp4 = new Opportunity();
        gOpp4.name = 'Goppname4';
        gOpp4.accountId = ac.Id;
        gOpp4.RecordTypeId = gId.get(0).Id;
        gOpp4.ForecastCategoryName = 'Commit';
        gOpp4.LeadSource = 'A001';
        gOpp4.CampaignId = cp.Id;
        gOpp4.CloseDate = system.today();
        gOpp4.Current_Processor__c = '1st federal financial';
        gOpp4.StageName = 'Initial Call Needed';
        
        insert gOpp4;

        Green_Tree_Oppy_Extension__c gt4 = new Green_Tree_Oppy_Extension__c();
        gt4.opportunity__c = gOpp4.Id;
        insert gt4;

       


        Test.stopTest();
    }


    public static testMethod voId oppTrackGTFStageChangesTest5() {


        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp5 = new Opportunity();
        gOpp5.name = 'Goppname5';
        gOpp5.accountId = ac.Id;
        gOpp5.RecordTypeId = gId.get(0).Id;
        gOpp5.ForecastCategoryName = 'Commit';
        gOpp5.LeadSource = 'A001';
        gOpp5.CampaignId = cp.Id;
        gOpp5.CloseDate = system.today();
        gOpp5.Current_Processor__c = '1st federal financial';
        gOpp5.StageName = 'Initial Call Needed';
        
        insert gOpp5;

        Green_Tree_Oppy_Extension__c gt5 = new Green_Tree_Oppy_Extension__c();
        gt5.opportunity__c = gOpp5.Id;
        insert gt5;

        
        test.stopTest();
    }
    public static testMethod voId oppTrackGTFStageChangesTest6() {
        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp6 = new Opportunity();
        gOpp6.name = 'Goppname6';
        gOpp6.accountId = ac.Id;
        gOpp6.RecordTypeId = gId.get(0).Id;
        gOpp6.ForecastCategoryName = 'Commit';
        gOpp6.LeadSource = 'A001';
        gOpp6.CampaignId = cp.Id;
        gOpp6.CloseDate = system.today();
        gOpp6.Current_Processor__c = '1st federal financial';
        gOpp6.StageName = 'Initial Call Needed';
        
        insert gOpp6;

        Green_Tree_Oppy_Extension__c gt6 = new Green_Tree_Oppy_Extension__c();
        gt6.opportunity__c = gOpp6.Id;
        insert gt6;

        test.stopTest();
    }
    public static testMethod voId oppTrackGTFStageChangesTest7() {
        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp7 = new Opportunity();
        gOpp7.name = 'Goppname7';
        gOpp7.accountId = ac.Id;
        gOpp7.RecordTypeId = gId.get(0).Id;
        gOpp7.ForecastCategoryName = 'Commit';
        gOpp7.LeadSource = 'A001';
        gOpp7.CampaignId = cp.Id;
        gOpp7.CloseDate = system.today();
        gOpp7.Current_Processor__c = '1st federal financial';
        gOpp7.StageName = 'Initial Call Needed';
       
        insert gOpp7;

        Green_Tree_Oppy_Extension__c gt7 = new Green_Tree_Oppy_Extension__c();
        gt7.opportunity__c = gOpp7.Id;
        insert gt7;

       
        test.stopTest();
    }
    public static testMethod voId oppTrackGTFStageChangesTest8() {
        Test.startTest();
        
        List<RecordType> gId = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND DeveloperName = 'GreenTree' LIMIT 1];
        Account ac = new Account();
        ac.name = 'testcase';
        insert ac;

        Campaign cp = new Campaign();
        cp.name = 'cppname';
        insert cp;

        Opportunity gOpp8 = new Opportunity();
        gOpp8.name = 'Goppname8';
        gOpp8.accountId = ac.Id;
        gOpp8.RecordTypeId = gId.get(0).Id;
        gOpp8.ForecastCategoryName = 'Commit';
        gOpp8.LeadSource = 'A001';
        gOpp8.CampaignId = cp.Id;
        gOpp8.CloseDate = system.today();
        gOpp8.Current_Processor__c = '1st federal financial';
        gOpp8.StageName = 'Initial Call Needed';
       
        insert gOpp8;

        Green_Tree_Oppy_Extension__c gt8 = new Green_Tree_Oppy_Extension__c();
        gt8.opportunity__c = gOpp8.Id;
        insert gt8;

        
        update gOpp8;

        Test.stopTest();
    }
}