Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <label>Legal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Visa_Mastercard_Volume__c</fullName>
        <label>Monthly Visa/Mastercard Sales</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Does Not Accept Visa/MC</fullName>
                </value>
                <value>
                    <fullName>0 - 2,500</fullName>
                </value>
                <value>
                    <fullName>2,500 - 5,000</fullName>
                </value>
                <value>
                    <fullName>3,500 - 5,000</fullName>
                </value>
                <value>
                    <fullName>5,000 - 10,000</fullName>
                </value>
                <value>
                    <fullName>10,000 - 20,000</fullName>
                </value>
                <value>
                    <fullName>20,000 - 40,000</fullName>
                </value>
                <value>
                    <fullName>40,000 - 60,000</fullName>
                </value>
                <value>
                    <fullName>60,000 - 80,000</fullName>
                </value>
                <value>
                    <fullName>80,000 - 100,000</fullName>
                </value>
                <value>
                    <fullName>100,000 +</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operating_Since__c</fullName>
        <label>Length of time in business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>6 months to 1 year</fullName>
                </value>
                <value>
                    <fullName>1 year to 2 years</fullName>
                </value>
                <value>
                    <fullName>More than 2 years</fullName>
                </value>
                <value>
                    <fullName>Less than 6 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Principal_1_City__c</fullName>
        <label>Principal 1 City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_State__c</fullName>
        <label>Principal 1 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_Street_Address__c</fullName>
        <label>Principal 1 Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_1_Zip__c</fullName>
        <label>Principal 1 Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_City__c</fullName>
        <label>Principal 2 City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_First_Name__c</fullName>
        <label>Principal 2 First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_Last_Name__c</fullName>
        <label>Principal 2 Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_State__c</fullName>
        <label>Principal 2 State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_Street_Address__c</fullName>
        <label>Principal 2 Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Zip__c</fullName>
        <label>Principal 2 Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Of_Business__c</fullName>
        <label>Type Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Cigar Cigarette &amp; Tobacco Dealer-Retail</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
                <value>
                    <fullName>Framing Store</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <formula>Account.Owned_Business_Since__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updated From Account Owned Business Since Field.</inlineHelpText>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type_of_Business__c</fullName>
        <formula>TEXT (Account.BusinessType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Business</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestAfterLeadCreatePrincipal2.cls
@isTest 
public with sharing class TestAfterLeadCreatePrincipal2 {

 
    static testMethod void createPrincipal2_UnitTest() {
        Test.startTest(); 
        CALC.ApexTesting();
        Lead l = new Lead();
        
        l.Status = 'Inital Call Needed';
        l.LeadSource = 'A001';
        l.Company = 'Krell Audio/Video';
        l.Legal_Business_Name__c = 'Krell Audio/Video';
        l.Phone = '3132329090';
        l.Type_Of_Business__c = 'Entertainment';
        l.Operating_Since__c = 'More than 2 years';
        l.DateBusinessStarted__c = system.today();
        l.Owned_Business_Since__c = system.today();
        l.FirstName = 'Jake';
        l.LastName = 'Jones';
        l.Principal_1_Street_Address__c = '1000 West Street';
        l.Principal_1_City__c = 'Washington';
        l.Principal_1_State__c = 'DC';
        l.Principal_1_Zip__c = '20012';
        l.Monthly_Visa_Mastercard_Volume__c ='80,000 - 100,000';
        
        l.Principal_2_First_Name__c = 'Jerry';
        l.Principal_2_Last_Name__c = 'Jones';
        l.Principal_2_Street_Address__c = '1000 Dallas Way';
        l.Principal_2_City__c = 'Dallas';
        l.Principal_2_State__c = 'TX';
        l.Principal_2_Zip__c = '30012';        
        
        insert l;
        
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm); 
        
    String id = l.id;

    Database.LeadConvert lc = new Database.LeadConvert();
    lc.setLeadId(id);
     
    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
    lc.setConvertedStatus(convertStatus.MasterLabel);

    Database.LeadConvertResult lcr = Database.convertLead(lc);
    if(lcr.isSuccess())
    {
      String cId = lcr.getContactId();

    }
            
        
        Test.stopTest();
    }
 
}