Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>note-{000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <recordTypes>
        <fullName>Processing</fullName>
        <active>true</active>
        <label>Processing Notes</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMasterNoteTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 
@isTest
private class TestMasterNoteTrigger 
{
    @testSetup static void setup() {
        Account Acc = new Account();
        Acc.name = 'Test Account1';
        Acc.BusinessType__c = 'testBusiness';
        insert Acc;
        
        Campaign cam = new Campaign();
        cam.Name = 'Test';
        cam.Type='Internet';
        insert cam ;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.id;
        insert opp;   
    }
    
    static testMethod void myUnitTest() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType> rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'Internal QC'
                                And
                                    sobjectType='Note__c'];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity 
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.recordTypeID=rt.get(0).id;
        noteObj2.Opportunity__c = opp.Id; 
        insert noteObj2;
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                            
    }
    
     static testMethod void myUnitTest2() 
     {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        List<RecordType> rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'Internal UW Notes'
                                And
                                    sobjectType='Note__c'];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity 
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
               
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;

        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                           
    }
        
    static testMethod void myUnitTest3() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType>rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'Processing Notes'
                                And
                                    sobjectType='Note__c' Limit 1];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
                
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id;
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;
             
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                           
    }
        
    static testMethod void myUnitTest4() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType> rt = [SELECT 
                                        Id,Name, LastModifieddate
                                    FROM 
                                        RecordType 
                                    WHERE 
                                        Name = 'UW Notes'
                                    And
                                        sobjectType='Note__c' Limit 1];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;

        
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                            
    }
    static testMethod void myUnitTest5() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType> rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'Third Party UW Notes'
                                And
                                    sobjectType='Note__c'];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                   Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;
                
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                            
    }
    static testMethod void myUnitTest6() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType> rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'UW Notes to Processing/Risk Department'
                                And
                                    sobjectType='Note__c'];
       Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;

        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
         Test.stopTest();                           
    }
    static testMethod void myUnitTest7() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        List<RecordType> rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'SA Internal Notes'
                                And
                                    sobjectType='Note__c'];
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        
        
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                           
    }    

    static testMethod void myUnitTest8() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        
        Account acc=[select
                            name, BusinessType__c 
                    from 
                            Account
                    where 
                            name = 'Test Account1'];
        Campaign cam= [select
                            name, type
                    from 
                            Campaign 
                    where 
                            name = 'Test'];
        Opportunity opp= [select
                                    Name , LeadSource ,StageName ,CloseDate ,CampaignId,Current_Processor__c  ,AccountId  
                            from 
                                    Opportunity
                            where 
                                    name = 'testOpportunity'];
        
        List<RecordType>rt = [SELECT 
                                    Id,Name, LastModifieddate
                                FROM 
                                    RecordType 
                                WHERE 
                                    Name = 'Pre Qual Notes'
                                AND
                                    sobjectType='Note__c' LIMIT 2];     
        
        Note__c noteObj2 = new Note__c();
        noteObj2.Note_Content__c='Conditions';
        noteObj2.Opportunity__c = opp.Id; 
        noteObj2.recordTypeID=rt.get(0).id;
        insert noteObj2;
       
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        noteObj.recordTypeID=rt.get(0).id;
        update noteObj;
        delete noteObj;
        Test.stopTest();                    
    }
}