Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Site_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Site Surveys</relationshipLabel>
        <relationshipName>R00N70000001wK6gEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Type__c</fullName>
        <label>Site Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Merchant Site 72</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 72</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 72</fullName>
                </value>
                <value>
                    <fullName>Merchant Site 48</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 48</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 48</fullName>
                </value>
                <value>
                    <fullName>Merchant Site 24</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 24</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Site Survey</label>
    <nameField>
        <label>Site Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestSiteSurveys_Ctrl.cls
@isTest 
private class TestSiteSurveys_Ctrl
{
    @testSetup static void setup()
    {
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cam = new Campaign();
        cam.Name = 'Test';
        cam.Type='Internet';
        insert cam;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.id;
        insert opp; 
        
        Site_Survey__c siteObj = new  Site_Survey__c();
        siteObj.Name = 'TestSite';
        siteObj.Site_Survey_Type__c = 'Merchant Site 72';
        siteObj.Opportunity__c = opp.Id;
        insert  siteObj;
    }    
    static testMethod void unitTest1() 
    {
        Test.startTest();        
        Opportunity opp=[SELECT
                                Id
                            FROM
                                Opportunity
                            WHERE
                                Name='testOpportunity' LIMIT 1];
     
        Site_Survey__c siteObj = [SELECT 
                                        Id
                                    FROM
                                        Site_Survey__c 
                                    WHERE
                                        Name='TestSite' LIMIT 1];        
        PageReference p=Page.SiteSurveysCustom;
        Test.setCurrentPage(p);
        
        ApexPages.currentPage().getParameters().put('Id', siteObj.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();        
        Test.stopTest();
    }
    
    static testMethod void unitTest2() 
    {
        Test.startTest(); 
        
        Opportunity opp=[SELECT
                                Id
                            FROM
                                Opportunity
                            WHERE
                                Name='testOpportunity' LIMIT 1];
     
        Site_Survey__c siteObj = [SELECT 
                                        Id
                                    FROM
                                        Site_Survey__c 
                                    WHERE
                                        Name='TestSite' LIMIT 1];

        PageReference p=Page.SiteSurveysCustom;
        Test.setCurrentPage(p);
        
        ApexPages.currentPage().getParameters().put('Id', NULL);
        ApexPages.currentPage().getParameters().put('retURL', '/apex/SiteSurveysCustom?id='+siteObj.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();
        
        Test.stopTest();
    }
    
     static testMethod void unitTest3() 
     {
        Test.startTest(); 
        // DS-CONAM CALC.apexTesting();
        Opportunity opp=[SELECT
                                Id
                            FROM
                                Opportunity
                            WHERE
                                Name='testOpportunity' LIMIT 1];
     
        Site_Survey__c siteObj = [SELECT 
                                        Id
                                    FROM
                                        Site_Survey__c 
                                    WHERE
                                        Name='TestSite' LIMIT 1];
        
        PageReference p=Page.SiteSurveysCustom;
        Test.setCurrentPage(p);
        
        ApexPages.currentPage().getParameters().put('Id', NULL);
        ApexPages.currentPage().getParameters().put('retURL', '/apex/SiteSurveysCustom?id='+siteObj.Id+'&oppId='+opp.id);
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
       
        siteS.Save();
        siteS.cancel();        
        Test.stopTest();
    }   
    
    static testMethod void unitTest4() 
    {
        Test.startTest(); 
        Opportunity opp=[SELECT
                                Id
                            FROM
                                Opportunity
                            WHERE
                                Name='testOpportunity' LIMIT 1];
     
        Site_Survey__c siteObj = [SELECT 
                                        Id
                                    FROM
                                        Site_Survey__c 
                                    WHERE
                                        Name='TestSite' LIMIT 1];      
        
        PageReference p=Page.SiteSurveysCustom;
        Test.setCurrentPage(p);
        
        ApexPages.currentPage().getParameters().put('', siteObj.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.StandardController siteController = new ApexPages.standardController(siteObj);
        SiteSurveys_Ctrl siteS = new SiteSurveys_Ctrl(siteController);
               
        siteS.Save();
        siteS.cancel();   
        siteS.genDynamicQuery(Null);
        Test.stopTest();
    }   
}