Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Funding_Date__c</fullName>
        <label>First Funding Date</label>
        <summarizedField>Opportunity.Funded_by_WC__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Created_Opportunity__c</fullName>
        <label>Last Created Opportunity</label>
        <summarizedField>Opportunity.CreatedDate</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Renewal_Date__c</fullName>
        <label>Last Renewal Date</label>
        <summarizedField>Opportunity.CreatedDate</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.Renewal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Months_with_Current_Processor__c</fullName>
        <label>Months with Current Processor</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Funded_Renewal_Date__c</fullName>
        <label>Most Recent Funded Renewal Date</label>
        <summarizedField>Opportunity.Time_For_Renewal_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Roll_up_Approved__c</fullName>
        <label>Roll up Approved</label>
        <summaryFilterItems>
            <field>Opportunity.Renewal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.Approved_Flag__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>note-{000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Database_Entry_Due_Date__c</fullName>
        <label>Account Database Entry Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Database_Entry__c</fullName>
        <label>Account Database Entry</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account_In_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account In Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advance_ID__c</fullName>
        <externalId>true</externalId>
        <label>Advance ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Funding_Date__c</fullName>
        <formula>Account.First_Funding_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Funding Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Months_with_Current_Processor__c</fullName>
        <formula>Account.Months_with_Current_Processor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Months with Current Processor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <formula>Account.Number_of_Locations__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <formula>Account.Number_of_Terminals_at_Location__c</formula>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <description>Opportunity ID Number</description>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <formula>Account.Owned_Business_Since__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updated From Account Owned Business Since Field.</inlineHelpText>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PrimaryCampaignSource__c</fullName>
        <formula>CASE(Campaign.Type ,
&quot;Internet&quot;, &quot;Internet&quot;,
&quot;Rapid Advance Internal Campaign&quot;, &quot;Rapid Advance Internal Campaign&quot;,
Campaign.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PrimaryCampaignSource</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Number__c</fullName>
        <label>Renewal Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Syndication_Amount__c</fullName>
        <label>Syndication Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Time_For_Renewal_Date__c</fullName>
        <formula>CloseDate + 150</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time For Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/MainClass.cls
/*
@Name               : 
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        :  
@Revision History   : Uses of Field Account_In_Risk__c Commented/Removed By MK Conam 2 Dec 2015
*/
global class MainClass 
{
    public Note_Detail objNoteDetail {get;set;}
    public Opportunity_Detail objOpportunityDetail {get;set;}
    public oppDetail oppDetail {get;set;}
    
    public MainClass() 
    {
        try 
        {
            Opportunity objOpportunity = [Select 
                                                Renewal_Number__c, Renewal__c, Account_Database_Entry_Due_Date__c, Account_Database_Entry__c, Id,
                                                Name, StageName, Type, AccountId, Account.BillingCity, Account.BillingCountry, Account.BillingState,
                                                Account.BillingStreet, Account.BillingPostalCode, Account.Roll_up_Approved__c, Account.Fax, 
                                                Account.DateBusinessStarted__c, Account.Phone, Account.Name, Account.FederalTaxID__c, 
                                                Account.First_Funding_Date__c, Account.Most_Recent_Funded_Renewal_Date__c, Time_For_Renewal_Date__c, 
                                                Account.Last_Renewal_Date__c, CreatedDate, Account.Last_Created_Opportunity__c, Account.Legal_Name__c, 
                                                Account.Months_with_Current_Processor__c, Account.Number_of_Locations__c, Account.Number_of_Terminals_at_Location__c, 
                                                Syndication_Amount__c, Product__c, PrimaryCampaignSource__c, OwnerId, LastModifiedById, CreatedById, 
                                                Amount, Advance_ID__c, Account.Owned_Business_Since__c, Account.BusinessType__c,
                                                Account.ownerId, Account.Type, Opportunity_Number__c 
                                        From 
                                                Opportunity 
                                        WHERE 
                                                Id = : ApexPages.currentPage().getParameters().get('Id')];
            if (objOpportunity != null) 
            {
                oppDetail = new oppDetail(objOpportunity, getAllUsers.get(objOpportunity.LastModifiedById).Name, getAllUsers.get(objOpportunity.CreatedById).Name);
                objOpportunityDetail = new Opportunity_Detail(objOpportunity);
            }
            objNoteDetail = new Note_Detail('Note');
        }
        catch (Exception ex) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Please contact your Administrator!'));
        }
    }

    public static map <Id, User> getAllUsers {
        get {
            if (getAllUsers == null) {
                getAllUsers = new map <Id, User> ([select Id, Name from User where isActive = true]); //FullPhotoUrl
            }
            return getAllUsers;
        }
        private set;
    }

    @RemoteAction
    public static void createNote(String noteContent, String recordTypeId1, String oppId) {
        try
        {
            Note__c objNote = new Note__c(Note_Content__c = noteContent, RecordTypeId = recordTypeId1, Opportunity__c = oppId);
            insert objNote;
            System.debug('>>>>>>>>>>>>>>>>>>>' + objNote);
        }
        catch (Exception e)
        {
            throw e;
        }
    }

    @RemoteAction
    public static void updateAccount(String name, String billingCity, String billingCountry, String billingState, String billingStreet, 
                                    String billingPostalCode, String fax, String dateBusinessStarted, String phone, String federalTaxID, 
                                    String monthsWithCurrentProcessor, String numberOfLocations, String numberOfTerminalsAtLocation, 
                                    String ownedBusinessSince, String accountId) 
    {
        try
        {
            Account objAccount = [Select 
                                        Type, Phone, Owned_Business_Since__c, Number_of_Terminals_at_Location__c, Number_of_Locations__c,
                                        Name, Most_Recent_Funded_Renewal_Date__c, Months_with_Current_Processor__c, Last_Created_Opportunity__c, 
                                        First_Funding_Date__c, FederalTaxID__c, Fax, DateBusinessStarted__c, BillingStreet, BillingState, 
                                        BillingPostalCode, BillingCountry, BillingCity 
                                From 
                                        Account 
                                where   
                                        Id = : accountId];
            if (objAccount != null)
            {
                objAccount.Name = name;
                objAccount.BillingCity = billingCity;
                objAccount.BillingCountry = billingCountry;
                objAccount.BillingPostalCode = billingPostalCode;
                objAccount.BillingState = billingState;
                objAccount.BillingStreet = billingStreet;
                if (dateBusinessStarted != null && dateBusinessStarted.trim() != '') {
                    objAccount.DateBusinessStarted__c = Date.valueOf(dateBusinessStarted);
                }
                objAccount.Fax = fax;
                objAccount.FederalTaxID__c = federalTaxID;
                //objAccount.First_Funding_Date__c = Datetime.valueOf(firstFundingDate);
                //objAccount.Last_Created_Opportunity__c = Datetime.valueOf(lastOpp); 
                if (monthsWithCurrentProcessor != null && monthsWithCurrentProcessor.trim() != '') 
                {
                    objAccount.Months_with_Current_Processor__c = decimal.valueOf(monthsWithCurrentProcessor);
                }
                //objAccount.Most_Recent_Funded_Renewal_Date__c = Date.valueOf(mostRecentOpp);
                if (numberOfLocations != null && numberOfLocations.trim() != '')
                {
                    objAccount.Number_of_Locations__c = decimal.valueOf(numberOfLocations);
                }
                if (numberOfTerminalsAtLocation != null && numberOfTerminalsAtLocation.trim() != '')
                {
                    objAccount.Number_of_Terminals_at_Location__c = decimal.valueOf(numberOfTerminalsAtLocation);
                }
                if (ownedBusinessSince != null && ownedBusinessSince.trim() != '')
                {
                    objAccount.Owned_Business_Since__c = Date.valueOf(ownedBusinessSince);
                }
                objAccount.Phone = phone;
                update objAccount;
            }
        } 
        catch (Exception e) 
        {
            throw e;
        }
    }

    public void createNote1(String noteContent, String recordTypeId1, String oppId) {
        try 
        {
            Note__c objNote = new Note__c(Note_Content__c = noteContent, RecordTypeId = recordTypeId1, Opportunity__c = oppId);
            insert objNote;
            System.debug('>>>>>>>>>>>>>>>>>>>' + objNote);
        } catch (Exception e) {
            throw e;
        }
    }

    public MainClass(ApexPages.StandardController controller) {
        try {
            Opportunity objOpportunity = [Select 
                                                Renewal_Number__c, Renewal__c, Account_Database_Entry_Due_Date__c, Account_Database_Entry__c, Id, 
                                                Name, StageName, Type, AccountId, Account.BillingCity, Account.BillingCountry, Account.BillingState,
                                                Account.BillingStreet, Account.BillingPostalCode, Account.Roll_up_Approved__c, Account.Fax, 
                                                Account.DateBusinessStarted__c, Account.Phone, Account.Name, Account.FederalTaxID__c, 
                                                Account.First_Funding_Date__c, Account.Most_Recent_Funded_Renewal_Date__c, Time_For_Renewal_Date__c, 
                                                Account.Last_Renewal_Date__c, CreatedDate, Account.Last_Created_Opportunity__c, Account.Legal_Name__c,
                                                Account.Months_with_Current_Processor__c, Account.Number_of_Locations__c, Account.Number_of_Terminals_at_Location__c,
                                                Syndication_Amount__c, Product__c, PrimaryCampaignSource__c, OwnerId, LastModifiedById, CreatedById, Amount, 
                                                Advance_ID__c,  Account.Owned_Business_Since__c, Account.BusinessType__c,
                                                Account.ownerId, Account.Type, Opportunity_Number__c 
                                        From 
                                                Opportunity 
                                        WHERE Id = : ApexPages.currentPage().getParameters().get('Id')];
            if (objOpportunity != null)
            {
                oppDetail = new oppDetail(objOpportunity, getAllUsers.get(objOpportunity.LastModifiedById).Name, getAllUsers.get(objOpportunity.CreatedById).Name);
                objOpportunityDetail = new Opportunity_Detail(objOpportunity);
            }
            objNoteDetail = new Note_Detail('Note');
        }
        catch (Exception ex)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Please contact your Administrator!'));
        }
    }

    public class oppDetail {
        public String createdByUserName{get;set;}
        public String modifiedByUserName {get;set;}
        public Opportunity opp {get;set;}
        public String dbaName {get;set;}
        
        public oppDetail(Opportunity opp, String modifiedByUserName, String createdByUserName)
        {
            this.createdByUserName = createdByUserName;
            this.modifiedByUserName = modifiedByUserName;
            this.opp = opp;
            this.dbaName = FormulaFieldUtility.DBA_Name;
        }
    }
}