Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Funded_Referrals__c</fullName>
        <label>Number of Funded Referrals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Number_of_Funded_Referrals__c</fullName>
        <label>Number of Funded Referrals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referral_Merchant_ID__c</fullName>
        <label>Referral Merchant ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMasterOpportunityTrigger7.cls
@isTest
private class TestMasterOpportunityTrigger7
{
    @testSetup
    static void setup()
    {
        Test.startTest();
        List<lead> leadList=new List<lead>();
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;

        Lead lTemp= new Lead();
        lTemp.Company ='lead 1';
        lTemp.Email='Test@test.com';
        lTemp.FirstName='test';
        lTemp.LastName='last name97';
        lTemp.state='CT';
        insert lTemp;

        Lead lTemp2= new Lead();
        lTemp2.Company ='referral lead';
        lTemp2.Email='Test@test.com';
        lTemp2.FirstName='tes t';
        lTemp2.LastName='lastname97';
        lTemp2.state='CT';
        lTemp2.referral_merchant_id__c=lTemp.id;
        insert lTemp2;
        
        Test.stopTest();
    }
    static testmethod void unitTest()
    {
        Test.startTest();
        Lead lTemp2=[Select id from lead where lastname='lastname97' Limit 1];
        Lead lTemp=[Select id from lead where lastname='last name97' Limit 1];
        PageReference pg = Page.LeadAutoConvert; 
        Test.setCurrentPage(pg); 
        ApexPages.StandardController cont = new ApexPages.standardController(lTemp2); 
        leadConvertButtonOverride ext = new leadConvertButtonOverride(cont); 
        ext.autoConvert(); 
        
        List<lead> lRec=[select id, number_of_funded_referrals__c, convertedOpportunityId from lead where id=: lTemp2.id];
        
        if(lRec.size()>0)
        {
            Opportunity opp=[Select stagename from opportunity where id =: lRec.get(0).convertedOpportunityId ];
            opp.stageName='Closed Won';
            update opp;
        }
        Test.stopTest();
    }
    
    static testmethod void unitTest2()
    {
        Test.startTest();
         
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
               
        Lead lTemp2= new Lead();
        lTemp2.Company ='referral lead';
        lTemp2.Email='Test@test.com';
        lTemp2.FirstName='tes t';
        lTemp2.LastName='lastname97';
        lTemp2.state='CT';
        lTemp2.referral_merchant_id__c=acc.id;
        insert lTemp2;
        
        PageReference pg = Page.LeadAutoConvert; 
        Test.setCurrentPage(pg); 
        ApexPages.StandardController cont = new ApexPages.standardController(lTemp2); 
        leadConvertButtonOverride ext = new leadConvertButtonOverride(cont); 
        ext.autoConvert(); 
        
        List<lead> lRec=[select id, number_of_funded_referrals__c, convertedOpportunityId from lead where id=: lTemp2.id];
        
        if(lRec.size()>0)
        {
            Opportunity opp=[Select stagename from opportunity where id =: lRec.get(0).convertedOpportunityId ];
            opp.stageName='Closed Won';
            update opp;
        }        
        Test.stopTest();
    }
    
    static testmethod void unitTest3()
    {
        Test.startTest();
        
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        /*
        Lead lTemp= new Lead();
        lTemp.Company ='lead 1';
        lTemp.Email='Test@test.com';
        lTemp.FirstName='test';
        lTemp.LastName='lastname97';
        lTemp.state='CT';
        insert lTemp;
        */
        
        Lead lTemp=[Select id from lead where Company ='lead 1' Limit 1];
        
        Lead lTemp2= new Lead();
        lTemp2.Company ='referral lead';
        lTemp2.Email='Test@test.com';
        lTemp2.FirstName='tes t';
        lTemp2.LastName='lastname97';
        lTemp2.state='CT';
        lTemp2.referral_merchant_id__c=lTemp.id;
        insert lTemp2;
        
        PageReference pg = Page.LeadAutoConvert; 
        Test.setCurrentPage(pg); 
        ApexPages.StandardController cont = new ApexPages.standardController(lTemp2); 
        leadConvertButtonOverride ext = new leadConvertButtonOverride(cont); 
        ext.autoConvert(); 
        
        List<lead> lRec=[select id, number_of_funded_referrals__c, convertedOpportunityId from lead where id=: lTemp2.id];
        
        if(lRec.size()>0)
        {
            Opportunity opp=[Select stagename from opportunity where id =: lRec.get(0).convertedOpportunityId ];
            opp.stageName='Closed Won';
            update opp;
        }
        Test.stopTest();
    }
}