Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/PartnerCategoryAccount__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting For Account Multiselect</description>
    <label>Partner Category Account</label>
</CustomObject>

Rapid Prd/src/classes/TestAccountPartnerCategoryEditExtn.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.


@Name            : TestAccountPartnerCategoryEditExtn
@Author          : DS-Conam
@Date            : Nov 12  , 2015
@Description     : Test Class for AccountPartnerCategoryEditExtn

*/
@isTest

private class TestAccountPartnerCategoryEditExtn
{
    @testSetup static void setup() 
    {
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        PartnerCategoryAccount__c pcObj=new PartnerCategoryAccount__c();
        pcObj.Name='Accountant';
        insert pcObj; 
        
        pcObj=new PartnerCategoryAccount__c();
        pcObj.Name='Agent/MLS-US';
        insert pcObj;
        
        pcObj=new PartnerCategoryAccount__c();
        pcObj.Name='Franchise';
        insert pcObj; 
    }
    
    static testMethod void unitTest()
    {
        Test.startTest();
        Account aTemp=[Select 
                                id, name
                       from
                                Account
                       where 
                                name ='Test Account1' Limit 1];
                                
        PageReference pPage=Page.AccountPartnerCategoryEdit;
        Test.setCurrentPage(pPage);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(aTemp);
        AccountPartnerCategoryEditExtn ctrl=new AccountPartnerCategoryEditExtn(sc);
        
        ApexPages.CurrentPage().getParameters().put('id',aTemp.id);
        ctrl=new AccountPartnerCategoryEditExtn(sc);
        ctrl.onSave();
        
        Partner_Category__c p1=new Partner_Category__c();
        p1.name='Accountant';
        p1.Partner_Account__c=aTemp.id;
        p1.Sort_Order__c=1;
        insert p1;
        
        p1=new Partner_Category__c();
        p1.Partner_Account__c=aTemp.id;
        p1.name='Franchise';
        p1.Sort_Order__c=1;
        insert p1;
        
        ctrl=new AccountPartnerCategoryEditExtn(sc);
        ctrl.onSave();
        
        ctrl.outputMessage='This is a test output Message. This is a test Message. This is a test Message. This is a test Message.';
        String sTemp=ctrl.outputMessage;
        Test.stopTest();
        
    }
    
    static testMethod void unitTest2()
    {
        Test.startTest();
        
        Account acc = new Account();
        
        PageReference pPage=Page.AccountPartnerCategoryEdit;
        Test.setCurrentPage(pPage);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(acc );
        AccountPartnerCategoryEditExtn ctrl=new AccountPartnerCategoryEditExtn(sc);
        try
        {
            ctrl.onSave();
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
        
        
    }
}