Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/DistributorGreenTree__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used to store the default owner for Green Tree opportunities which will be the used as the Distributor From in Lead distribution engine currently Jeff Hageman</description>
    <label>Distributor Green Tree</label>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Calculate_Due_Dates__c</fullName>
        <label>Calculate Due Dates</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Advance_ID__c</fullName>
        <externalId>true</externalId>
        <label>Advance ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calculate_Due_Dates__c</fullName>
        <label>Calculate Due Dates</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Opportunity record is a clone from a previous opportunity, the link to that original opportunity will be here.  No one has to fill this in manually.</inlineHelpText>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Underwriter_Assigned__c</fullName>
        <label>Underwriter Assigned:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aisha</fullName>
                </value>
                <value>
                    <fullName>Andre</fullName>
                </value>
                <value>
                    <fullName>Ashton Tucker</fullName>
                </value>
                <value>
                    <fullName>Audley</fullName>
                </value>
                <value>
                    <fullName>Cassandra</fullName>
                </value>
                <value>
                    <fullName>CREDIT COMMITTEE OVERIDE</fullName>
                </value>
                <value>
                    <fullName>Dylan</fullName>
                </value>
                <value>
                    <fullName>Ericka Harry</fullName>
                </value>
                <value>
                    <fullName>Evan</fullName>
                </value>
                <value>
                    <fullName>Greg Dye</fullName>
                </value>
                <value>
                    <fullName>Janice Peterson</fullName>
                </value>
                <value>
                    <fullName>John</fullName>
                </value>
                <value>
                    <fullName>Juan Feldman</fullName>
                </value>
                <value>
                    <fullName>Mark</fullName>
                </value>
                <value>
                    <fullName>Rani</fullName>
                </value>
                <value>
                    <fullName>Theresa</fullName>
                </value>
                <value>
                    <fullName>Vashia</fullName>
                </value>
                <value>
                    <fullName>Vilma</fullName>
                </value>
                <value>
                    <fullName>Will Tumulty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>GreenTree</fullName>
        <active>true</active>
        <businessProcess>GreenTree</businessProcess>
        <label>GreenTree</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/UnderWriting_Opportunity_users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>UnderWriting Opportunity users</label>
</CustomObject>

Rapid Prd/src/classes/TestMasterOpportunityTrigger2.cls
/**
@Name            : TestMasterOpportunityTrigger_2nd 
@Author          : MK Conam
@Date            : Aug 28 2015
@Description     : Test Class for OpportunityTriggerHandler
**/

@isTest

private class TestMasterOpportunityTrigger2
{  
    static testMethod voId unitTestUnderwritingOpprtunity()
    {    
        // DS-CONAM CALC.apexTesting();
        Test.startTest();
        try
        {
            Account acc = new Account();
            acc.name = 'Test Account1';
            acc.BusinessType__c = 'testBusiness';
            insert acc;
            
            Campaign cam= new Campaign();
            cam.Name = 'Test';
            cam.Type='Internet';
            insert cam;
            
            Opportunity opp = new Opportunity();
            opp.Name = 'testOpportunity';
            opp.LeadSource = 'web';
            opp.StageName = 'Prospecting';
            opp.Underwriter_Assigned__c ='AUTO DECISION';
            opp.CampaignId = cam.Id;           
            opp.Current_Processor__c = 'Abanco INTERNATIONAL';
            opp.CloseDate = System.today() + 20;
            opp.AccountId = acc.Id;
            insert opp;      
        
            User usr = new User();
            usr.LastName='TestUser1';
            usr.Email ='test@test.com';
            insert usr;
            
            UnderWriting_Opportunity_Users__c uWO =new UnderWriting_Opportunity_Users__c();
            uWO.Name='Test111';
            uWO.Id =usr.Id;
            insert uWO;
        }
        Catch(Exception e)
        {
        }
        test.stopTest();
    }
    
    static testMethod voId unitTestOpportunityCampaign()
    {
        Test.startTest(); 
        try
        {
         testRenewalClone();
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    }
    
    static voId testRenewalClone() 
    {       
        // DS-CONAM CALC.ApexTesting();
         try
        {
            User uVal = [SELECT 
                            Id 
                        FROM 
                            User 
                        WHERE 
                            isActive = true 
                        AND 
                            profile.name='System administrator' LIMIT 1];
            Opportunity opp =new Opportunity(name='Test Opportunity 12345',closedate = system.today(), 
                                                stagename = 'Closed Deal', calculate_due_dates__c = system.now());
            insert opp;
            
                    OpportunityTeamMember newOtm = new OpportunityTeamMember();
                    newOtm.OpportunityId = opp.Id;
                    newOtm.UserId = uVal.Id;
                    newOtm.TeamMemberRole = 'Partner Sales Representative';
                    
                    insert newOtm;
                    
            Opportunity oppOther = new Opportunity(name='Test Opportunity 12345',closedate = system.today(), 
                                                    stagename = 'Closed Deal', calculate_due_dates__c = system.now());
            oppOther.previous_opportunity__c = opp.Id;
            insert oppOther; 
        }
        catch(Exception e)
        {
        }

    }
       
    static testMethod voId unitTestOpprtunityStageChangeCALC()
    {
        // DS-CONAM CALC.apexTesting();
         Test.startTest();
        try
        {
            List<RecordType> gId=[SELECT
                                        Id
                                    FROM
                                        RecordType
                                    WHERE
                                        sObjectType='Opportunity'
                                    AND
                                        DeveloperName='GreenTree'];
    
            Account ac= new Account();
            ac.name='testcase';
            ac.BusinessType__c = 'testBusiness';
           
            insert ac;
            
            Campaign cp= new Campaign();
            cp.name='cppname';
            cp.Type='Internet';
            insert cp;
           
            Opportunity opp = new Opportunity();
            opp.name='oppname';
            opp.accountId=ac.Id;
            opp.ForecastCategoryName='Commit';
            opp.LeadSource='A001';
            opp.CampaignId=cp.Id;
            opp.CloseDate=system.today();
            opp.Current_Processor__c='1st federal financial';
            opp.StageName='closed';
            opp.Advance_ID__c ='0987654321';
            insert opp;      
            
            Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
            gt.opportunity__c=opp.Id;
            insert gt;
            
            List <DistributorGreenTree__c> defaultOwnerId = [SELECT
                                                                        Name
                                                                FROM
                                                                        DistributorGreenTree__c
                                                                ORDER BY
                                                                        createddate Limit 1];
                                                                    
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    }
}