Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Created_By_Conversion__c</fullName>
        <label>Created By Conversion</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Duplicate_Contact_Blocker_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Match_Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Account Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_First_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match First Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Last_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Last Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Phone</label>
        <type>Checkbox</type>
    </fields>
    <label>Duplicate Contact Blocker Setup</label>
    <nameField>
        <label>Duplicate Contact Blocker Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duplicate Contact Blocker Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMasterContactTrigger.cls
@isTest

public class TestMasterContactTrigger 
{   
   public static testMethod void DuplicateContactBlocker_unitTest()
   {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        PageReference testPage = Page.DuplicateContactBlockerSetup;
        Test.setCurrentPage(testPage);                  
        Duplicate_Contact_Blocker_Setup__c dcbs =  new Duplicate_Contact_Blocker_Setup__c();
        dcbs.Name = 'TestDCBS1';
        dcbs.Match_Account_Name__c= true;
        dcbs.Match_Email__c=true;
        dcbs.Match_Phone__c= false;        
        insert dcbs;            
        if (dcbs.id!=null) 
        {
            DuplicateContactBlockerController theController = new DuplicateContactBlockerController();
            delete dcbs;
            theController.ReadyPage();                
        }

        Account acct = new Account();
        acct.Name = 'Test Account1';
        acct.BusinessType__c='testBusiness';
        insert acct;
    
        Contact existingContact = new Contact();
        existingContact.FirstName = 'John';
        existingContact.LastName = 'Smith123';
        existingContact.Email = 'js123@gmail.com';
        existingContact.AccountId = acct.id;
        existingContact.Phone = '1231231234';
        insert existingContact;
        
        Contact duplicateContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com');
        duplicateContact.AccountId = acct.id;
    
        Duplicate_Contact_Blocker_Setup__c dcbs2 = new Duplicate_Contact_Blocker_Setup__c();
        
        dcbs2.Match_Phone__c = true;
        dcbs2.Match_Last_Name__c = true;
        dcbs2.Match_First_Name__c = true;
        dcbs2.Match_Email__c = true;
        dcbs2.Match_Account_Name__c = true;
        insert dcbs2;
        
        Contact dContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com', Phone = '1231231234');
        duplicateContact.AccountId = acct.id;    
        try
        {
           insert duplicateContact;
           insert dContact;
        }        
        catch (Exception e) 
        {
            System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
        }         
            delete dcbs2;
            
        try 
        {
            insert dContact;
        } 
        
        catch (Exception e) 
        {
            System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
        }
        
        Test.stopTest();
    }
    public static testMethod void DuplicateContactBlocker_unitTest1()
    {
        // DS-CONAM CALC.apexTesting();
        Test.startTest();         
        Duplicate_Contact_Blocker_Setup__c dcbs =  new Duplicate_Contact_Blocker_Setup__c();
        dcbs.Name = 'TestDCBS1';
        dcbs.Match_Account_Name__c= true;
        dcbs.Match_Email__c=true;
        dcbs.Match_Phone__c= true;
        insert dcbs;
            
        if (dcbs.id!=null) 
        {
            DuplicateContactBlockerController theController = new DuplicateContactBlockerController();
            theController.ReadyPage();                
        }

        Account acct = new Account();
        acct.Name = 'Test Account1';
        acct.BusinessType__c='testBusiness';
        insert acct;
    
        Contact existingContact = new Contact();
        existingContact.FirstName = 'John';
        existingContact.LastName = 'Smith123';
        existingContact.Email = 'js123@gmail.com';
        existingContact.AccountId = acct.id;
        existingContact.Phone = '1231231234';
        insert existingContact;
        
        Contact duplicateContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com');
        duplicateContact.AccountId = acct.id;    
        Duplicate_Contact_Blocker_Setup__c dcbs2 = new Duplicate_Contact_Blocker_Setup__c();        
        dcbs2.Match_Phone__c = true;
        dcbs2.Match_Last_Name__c = true;
        dcbs2.Match_First_Name__c = true;
        dcbs2.Match_Email__c = true;
        dcbs2.Match_Account_Name__c = true;
        insert dcbs2;
        
        Contact dContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com', Phone = '1231231234');
        duplicateContact.AccountId = acct.id;    
        try
        {
           insert duplicateContact;
           insert dContact;
        }        
        catch (Exception e) 
        {
            System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
        }         
        try 
        {
            insert dContact;
        } 
        
        catch (Exception e) 
        {
            System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
        }
        
        Test.stopTest();
    }
    
    static testMethod void ContactAfterInsertTrigger_unitTest()
    {    
        test.startTest();
        // DS-CONAM CALC.apexTesting();

        Account acc= new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusibess';
        insert acc;
        
        Campaign  cmObj = new Campaign();
        cmObj.Name = 'Test';
        cmObj.Type='Internet';
        insert cmObj;

        Opportunity opp= new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cmObj.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.id;
        insert opp;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'test';
        con.Created_By_Conversion__c = opp.Id;
        insert con;
        
        OpportunityContactRole  oppRole = new OpportunityContactRole();
        oppRole.ContactId = con.Id;
        oppRole.OpportunityId  = opp.Id;
        oppRole.Role = 'Principal 2'; 
        oppRole.isPrimary=true;
        insert oppRole;        
        
        ApexPages.StandardController sc = new ApexPages.standardController(oppRole);        
        ApexPages.currentPage().getParameters().put('Id', oppRole.Id);

        test.stopTest();
     
     }
}