Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Additional_Locations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Locations</relationshipLabel>
        <relationshipName>Additional_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <label>DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Additional Location</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Additional Locations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Customer_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>R00N70000002H6uVEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>R00N70000002FrsQEAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Survey</label>
    <nameField>
        <label>Customer Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Merchant__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Merchants</relationshipLabel>
        <relationshipName>Merchants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Merchant</label>
    <nameField>
        <displayFormat>Merchant-{0000}</displayFormat>
        <label>Merchant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>note-{000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DBA Name:</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Site_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Site Surveys</relationshipLabel>
        <relationshipName>R00N70000001wK6gEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Type__c</fullName>
        <label>Site Survey Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Merchant Site 72</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 72</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 72</fullName>
                </value>
                <value>
                    <fullName>Merchant Site 48</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 48</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 48</fullName>
                </value>
                <value>
                    <fullName>Merchant Site 24</fullName>
                </value>
                <value>
                    <fullName>Merchant Term 24</fullName>
                </value>
                <value>
                    <fullName>Mystery Shopper 24</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Site Survey</label>
    <nameField>
        <label>Site Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestUtils.cls
public class TestUtils {

    public static Account createAccount()
    {
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusiness';
        insert testAccount;
        return testAccount;
    }

    public static Campaign createCampaign()
    {
        Campaign  cmObj = new Campaign();
        cmObj.Name = 'Test';
        cmObj.Type='Internet';
        insert cmObj;
        return cmObj;
    }


    public static Opportunity createOpportunity(Account acc, Campaign cam)
    {
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 50;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.AccountId = acc.id;
        insert opp;
        return opp;
    }
    public static Quote createQuote(Opportunity opp)
    {
        Quote Quo = new Quote();
        Quo.Name = 'Test';
        Quo.OpportunityId = opp.id;
        insert Quo;
        return Quo;
    }
    
    public static Contact createContact(Account acc){
        Contact c = new Contact();
        c.AccountId = acc.Id;
        c.LastName = 'test';
        insert c;
        return c;
    }
    
    public static OpportunityContactRole createOpportunityContactRole(Contact con, Opportunity opp) {
        OpportunityContactRole  oppRole = new OpportunityContactRole();
        oppRole.ContactId = con.Id;
        oppRole.OpportunityId  = opp.Id;
        oppRole.Role = 'Principal 2'; 
        insert oppRole;
        return oppRole;
    }
    public static OpportunityContactRole createOpportunityContactRolePrimary(Contact con, Opportunity opp) {
        OpportunityContactRole  oppRole = new OpportunityContactRole();
        oppRole.ContactId = con.Id;
        oppRole.OpportunityId  = opp.Id;
        oppRole.Role = 'Principal 1'; 
        oppRole.isPrimary=true;
        insert oppRole;
        return oppRole;
    }
    
    
    public static Note__c createNote(Opportunity opp){
       Note__c Nc= new Note__c();
       nc.Note_Content__c='Conditions';
       RecordType rc= new RecordType(name='Approved');
       Nc.Opportunity__c = opp.Id; 
       insert Nc;
       return Nc;
    }
    
     public static Note__c createNote_New(Opportunity opp){
       Note__c Nc= new Note__c();
       nc.Note_Content__c='Conditions';
       RecordType rc= new RecordType(name='Internal UW Notes');
       Nc.Opportunity__c = opp.Id; 
       insert Nc;
       return Nc;
    }
    
    public static  Merchant__c createMerchant(Opportunity opp){
        Merchant__c  mc = new Merchant__c ();
        mc.Opportunity__c = opp.Id;
        insert mc;
        return mc;
    }
    
    
    public static Additional_Locations__c createAdditionalLocation(Account acc) {
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = acc.Id;
        insert aloc;
        return aloc;
    }
    
    
    public static Attachment createAttachment(Opportunity opp) {
        Attachment attachment = new Attachment();
        attachment.Body = Blob.valueOf('Test Attatchment on Class');
        attachment.Name = String.valueOf('test.txt');
        attachment.ParentId = opp.Id; 
        insert attachment;
        return attachment;
    }
    
    
     public static Customer_Survey__c createCustomerSurvey(Opportunity opp , Account acc) {
         Customer_Survey__c cs = new Customer_Survey__c();
         cs.Name = 'test';
         cs.Account__c = acc.Id;
         cs.Opportunity__c = opp.Id;
         insert cs;
         return cs;
     }
     
     public static Site_Survey__c createSiteSurvey(Opportunity opp) {
         Site_Survey__c surveyObj = new Site_Survey__c();
         surveyObj.Name = 'test';
         surveyObj.Site_Survey_Type__c = 'Merchant Site 24';
         surveyObj.Opportunity__c = opp.Id;
         insert surveyObj;
         return surveyObj;
             
     }
     
     Static testMethod void testUtil_UnitTest() {
        Account acc = TestUtils.createAccount(); 
        Campaign ca =  TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, ca);
        Quote q = TestUtils.createQuote(opp);
        Customer_Survey__c  cs = TestUtils.createCustomerSurvey(opp ,acc);
        TestUtils.createAttachment(opp);
        TestUtils.createAdditionalLocation(acc);
        TestUtils.createMerchant(opp);
        TestUtils.createNote(opp);
        Contact con = TestUtils.createContact(Acc);
        TestUtils.createOpportunityContactRole(con, opp);
        TestUtils.createNote_New(opp);
        TestUtils.createSiteSurvey(opp);
     }
     
     
    
}