Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <label>Current Processor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Prospect_Contacted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if there are any calls on a prospect that lasts at least 90 seconds.</description>
        <label>Prospect Contacted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestPopulateLeadOppNumHandler.cls
@isTest
Public class TestPopulateLeadOppNumHandler
{
    static testmethod void TestPopulateLeadOppNumMethod() {
        
        try{
            Lead ld=new Lead(LastName='Doe',FirstName='John',Company='Test',Status='Initial Call Needed',LeadSource='Referral',Prospect_Contacted__c=false);
            insert ld; 
            
            Lead ld2=new Lead(LastName='TestDoe',FirstName='TestJohn',Company='Test',Status='Initial Call Needed',LeadSource='Referral',Prospect_Contacted__c=false);
            insert ld2; 
            
            Account Acc = new Account();
            Acc.name = 'Test Account1';
            Acc.BusinessType__c = 'testBusibess';
            insert Acc;
        
            Campaign cam = new Campaign();
            cam.Name = 'Test';
            cam.Type='Internet';
            insert cam ;
        
            Opportunity opp = new Opportunity();
            opp.Name = 'testOpportunity';
            opp.LeadSource = 'web';
            opp.StageName = 'Prospecting';
            opp.CloseDate = System.today() + 20;
            opp.CampaignId = cam.Id;
            opp.Current_Processor__c = 'Abanco INTERNATIONAL';
            opp.CloseDate = System.today() + 50;
            opp.AccountId = acc.id;
            insert opp;
            
            Opportunity opp2 = new Opportunity();
            opp2.Name = 'testOpportunity2';
            opp2.LeadSource = 'web';
            opp2.StageName = 'Prospecting';
            opp2.CloseDate = System.today() + 20;
            opp2.CampaignId = cam.Id;
            opp2.Current_Processor__c = 'Abanco INTERNATIONAL';
            opp2.CloseDate = System.today() + 50;
            opp2.AccountId = acc.id;
            insert opp2;
            
            Task newTask=new Task();
            newTask.whoid=ld.id;
            newTask.Subject='test call';
            newTask.CallDurationinSeconds= 90;            
            insert newTask;
            
            newTask.whoid=ld2.id;
            update newTask;
            
            Task newTask1=new Task();
            newTask1.whoid=ld.id;
            newTask1.whatid=opp.id;
            newTask1.Subject='test call';
            newTask1.CallDurationinSeconds= 90;            
            insert newTask1;
            
            newTask1.whatid=opp2.id;
            update newTask1;
        }        
        catch(Exception e)
        {
            System.debug(e.getMessage());
        }
    }
}