Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <label>Partner Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnership</fullName>
                </value>
                <value>
                    <fullName>Financial Institutions Group</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/PartnerCategoryAccount__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting For Account Multiselect</description>
    <label>Partner Category Account</label>
</CustomObject>

Rapid Prd/src/classes/TestCategoryAccountContoller.cls
@isTest
public class TestCategoryAccountContoller
{
    private static testMethod void unitTest1()
    {
        Test.startTest();      
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        acc.Partner_Channel__c ='Partner';
        insert acc;
        
        Partner_Category__c cm = new Partner_Category__c();
        cm.Name = 'Test';
        insert cm;    
       
        PartnerCategoryAccount__c pca = new PartnerCategoryAccount__c();
        pca.Name ='Test';
        insert pca;
               
        ApexPages.StandardController sc = new ApexPages.StandardController(acc);        
        PageReference P=Page.CategoryAccount;
        Test.setCurrentPage(p);
        ApexPages.currentPage().getParameters().put('Id', acc.Id);
        ApexPages.currentPage().getParameters().put('accId', acc.Id);
        
        CategoryAccountContoller cpObj = new CategoryAccountContoller(sc);
        cpObj.outputMessage ='A.....Z';
        cpObj.Message ='TestMessage';
        cpObj.outputMessage.length();
        cpObj.PrimaryMessage ='TestPMessage';
        Test.stopTest();
    }
    
    private static testMethod void unitTest2()
    {
        Test.startTest();      
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        acc.Partner_Channel__c ='Partner';
        insert acc;
        
        Partner_Category__c cm = new Partner_Category__c();
        cm.Name = 'Test';
        cm.Partner_Account__c = acc.Id;
        insert cm;        
       
        PartnerCategoryAccount__c pca = new PartnerCategoryAccount__c();
        pca.Name ='Test';        
        insert pca;
               
        ApexPages.StandardController sc = new ApexPages.StandardController(acc);        
        PageReference P=Page.PartnerCategoryAccount;
        Test.setCurrentPage(p);
        ApexPages.currentPage().getParameters().put('Id', acc.Id);
        ApexPages.currentPage().getParameters().put('accId', acc.Id);
        
        CategoryAccountContoller cpObj = new CategoryAccountContoller(sc);
        cpObj.outputMessage ='';
        cpObj.Message ='TestMessage2';
        cpObj.outputMessage.length();
        cpObj.PrimaryMessage ='TestPMessage2';
        Test.stopTest();
    }    
    
    private static testMethod void unitTest3()
    {
        Test.startTest();      
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        acc.Partner_Channel__c ='Partner';
        // insert acc;
        
        Partner_Category__c cm = new Partner_Category__c();
        cm.Name = 'Test';
        cm.Partner_Account__c = acc.Id;
        insert cm;        
       
        PartnerCategoryAccount__c pca = new PartnerCategoryAccount__c();
        pca.Name ='Test';        
        insert pca;
        
        String  message3 ='';
        message3+= 'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
               
        ApexPages.StandardController sc = new ApexPages.StandardController(acc);        
        PageReference P=Page.PartnerCategoryAccount;
        Test.setCurrentPage(p);
        ApexPages.currentPage().getParameters().put('Id', acc.Id);
        ApexPages.currentPage().getParameters().put('accId', acc.Id);
        
        CategoryAccountContoller cpObj = new CategoryAccountContoller(sc);
        cpObj.outputMessage =Message3;
        cpObj.outputMessage.length();
        cpObj.PrimaryMessage ='TestPMessage2';
        Test.stopTest();
    }  
 }