Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Note_Content__c</fullName>
        <label>Note Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>note-{000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <recordTypes>
        <fullName>Funding</fullName>
        <active>true</active>
        <label>Funding</label>
    </recordTypes>
    <recordTypes>
        <fullName>Processing</fullName>
        <active>true</active>
        <label>Processing Notes</label>
    </recordTypes>
    <recordTypes>
        <fullName>Quancor</fullName>
        <active>true</active>
        <label>Quancor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <recordTypes>
        <fullName>Underwriting</fullName>
        <active>true</active>
        <label>UW Notes</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestNoteController.cls
@isTest
public class TestNoteController
{
    static testMethod void RunTestCase()
    {
        // DS-CONAM CALC.apexTesting();
        RecordType rc= new RecordType(name='Approved');
        
        Account Acc = new Account();
        Acc.name = 'Test Account1';
        Acc.BusinessType__c = 'testBusibess';
        insert Acc;
        Campaign cam = new Campaign();
        cam.Name = 'Test';
        cam.Type='Internet';
        insert cam ;
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.id;
        insert opp;
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        RecordType rc1= new RecordType(name='Approved');
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        List<User> u= [SELECT 
                            Id,Name,TimeZoneSidKey 
                        FROM 
                            User 
                        WHERE 
                            isActive= true];//FullPhotoUrl
        apexpages.currentpage().getparameters().put('Id',noteObj.id);
        ApexPages.StandardController sc = new ApexPages.standardController(noteObj);
        NoteController cntrl = new NoteController();
        
        List<String> selectedNotesRT = new List<String>{'Approved With Conditions','Archived Credit Bureau','Business Bankruptcies','Underwriting','Funding','Individual Bankrupties','Internal QC','Internal UnderWriting','Pre Qual','Pre Qual Loss','Prefunding Call','Processing','Quancor','Renewal','Risk Alert','Risk Notes','SA Internal','Sales Check List','Sales to UW Processing','Site','Split change','UW Processing'};
        list<RecordType> allRecordsType = [SELECT 
                                                Id,Name 
                                            FROM 
                                                RecordType 
                                            WHERE 
                                                Name 
                                            IN
                                                :selectedNotesRT 
                                            AND 
                                                IsActive=true];
        allRecordsType.sort();
        apexpages.currentpage().getparameters().put('rtId',allRecordsType[0].id);    
        
        ApexPages.StandardController noteController = new ApexPages.standardController(noteObj);
        NoteController nc = new NoteController(noteController);
        NoteController nc1 = new NoteController();
        
        for(RecordType rt:allRecordsType)
        {        
        NoteController.RecordTypeDetail  tr= new NoteController.RecordTypeDetail(rt.Id,rt.Name);
        }
        
        nc.createnote();
        
        string var_time = System.now().format('MM/dd/yyyy hh:mm:ss a',u[0].TimeZoneSidKey); 
        cntrl.convertToLocalTime(System.now(),u[0].id);
        cntrl.editNote();
        cntrl.deleteNote();
        NoteController.NotesDetail notedtl= new NoteController.NotesDetail (noteObj.id,noteObj, u[0].name,'',var_time,noteObj.ownerId);//u[0].FullPhotoUrl
    }
    
    static testMethod void RunTestCaseExc()
    {
        test.starttest();
        // DS-CONAM CALC.apexTesting();
        RecordType rc= new RecordType(name='Approved');
        
        Account Acc = new Account();
        Acc.name = 'Test Account1';
        Acc.BusinessType__c = 'testBusibess';
        insert Acc;
        Campaign cam = new Campaign();
        cam.Name = 'Test';
        cam.Type='Internet';
        insert cam ;
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.id;  
        
        Note__c noteObj = new Note__c();
        noteObj .Note_Content__c='Conditions';
        RecordType rc1= new RecordType(name='Approved');
        noteObj .Opportunity__c = opp.Id; 
        insert noteObj ;
        
        List<User> u= [SELECT 
                            Id,Name,TimeZoneSidKey 
                        FROM 
                            User 
                        WHERE 
                            isActive= true];//FullPhotoUrl                           
       
       
        NoteController cntrl = new NoteController();        
        List<String> selectedNotesRT = new List<String>{'Approved With Conditions','Archived Credit Bureau','Business Bankruptcies','Underwriting','Funding','Individual Bankrupties','Internal QC','Internal UnderWriting','Pre Qual','Pre Qual Loss','Prefunding Call','Processing','Quancor','Renewal','Risk Alert','Risk Notes','SA Internal','Sales Check List','Sales to UW Processing','Site','Split change','UW Processing'};
        list<RecordType> allRecordsType = [SELECT 
                                                Id,Name 
                                            FROM 
                                                RecordType 
                                            WHERE 
                                                Name 
                                            IN
                                                :selectedNotesRT 
                                            AND 
                                                IsActive=true];
        allRecordsType.sort();
        
        PageReference newPage=Page.NoteContent;
        Test.setCurrentPage(newPage);
        apexpages.currentpage().getparameters().put('rtId',allRecordsType[0].id);
        ApexPages.StandardController noteController = new ApexPages.standardController(noteObj);
        NoteController ncE = new NoteController(noteController);
        NoteController ncE1 = new NoteController();        
        for(RecordType rt:allRecordsType)
        {        
            NoteController.RecordTypeDetail  tr= new NoteController.RecordTypeDetail(rt.Id,rt.Name);
        }        
        ncE.createnote();        
        string var_time = System.now().format('MM/dd/yyyy hh:mm:ss a',u[0].TimeZoneSidKey); 
        cntrl.convertToLocalTime(System.now(),u[0].id);
        cntrl.editNote();
        cntrl.deleteNote();
        NoteController.NotesDetail notedtl= new NoteController.NotesDetail (noteObj.id,noteObj, u[0].name,'',var_time,noteObj.ownerId);//u[0].FullPhotoUrl
        
        test.stopTest();
    }
}