Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestRADoc_Ctrl.cls
@isTest

public with sharing class TestRADoc_Ctrl 
{
    @testSetup static voId setup()
    {
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cam = new Campaign();
        cam.Name = 'Test';
        cam.Type='Internet';
        insert cam;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cam.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = acc.Id;
        insert opp;
        
        Quote Quo = new Quote();
        Quo.Name = 'Test';
        Quo.OpportunityId = opp.Id;
        insert Quo;

    }
    
    static TestMethod voId testMethod1()
    {
        test.startTest(); 
        
        // DS-CONAM CALC.apexTesting();        
        Opportunity opp=[SELECT
                                Id
                        FROM    
                                Opportunity
                        WHERE
                                name='testOpportunity' LIMIT 1];
                
        PageReference ref = new PageReference('/apex/RADoc_Custom'); 
        Test.setCurrentPage(ref); 
        ApexPages.currentPage().getParameters().put('retURL','oppId='+opp.Id);
        
        ApexPages.StandardController controller =new ApexPages.StandardController(opp);
        RADoc_Ctrl radocObj1 = new RADoc_Ctrl(controller);
        radocObj1.cancel();
        radocObj1.save();
         
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        RADoc_Ctrl radocObj = new RADoc_Ctrl(controller);
        radocObj.cancel();
        radocObj.save();        

        Test.stopTest();       
    }  
    
     static TestMethod voId testMethod11()
    {
        test.startTest(); 
        
        // DS-CONAM CALC.apexTesting();        
        Opportunity opp=[SELECT
                                Id
                        FROM    
                                Opportunity
                        WHERE
                                name='testOpportunity' LIMIT 1];
                
        PageReference ref = new PageReference('/apex/RADoc_Custom'); 
        Test.setCurrentPage(ref); 
        ApexPages.currentPage().getParameters().put('retURL',opp.Id);
        
        ApexPages.StandardController controller =new ApexPages.StandardController(opp);
        RADoc_Ctrl radocObj1 = new RADoc_Ctrl(controller);
        radocObj1.cancel();
        radocObj1.save();
         
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        RADoc_Ctrl radocObj = new RADoc_Ctrl(controller);
        radocObj.cancel();
        radocObj.save();        

        Test.stopTest();       
    }      

    Static TestMethod voId testMethod2()
    {
        test.startTest(); 
        
        Opportunity opp=[SELECT
                                Id
                        FROM    
                                Opportunity
                        WHERE
                                name='testOpportunity' LIMIT 1];
        Quote Quo=[SELECT
                                Id
                        FROM    
                                Quote 
                        WHERE
                                name='Test' LIMIT 1];
        
       
        PageReference ref = new PageReference('/apex/raDocsRelatedList'); 
        Test.setCurrentPage(ref); 
        ApexPages.currentPage().getParameters().put('Id', Quo.Id ); 
        //ApexPages.currentPage().getParameters().put('retURL', opp.Id + 'oppId='+ opp.Id ); 
        
        ApexPages.StandardController controller =new ApexPages.StandardController(opp);
        RADoc_Ctrl radocObj1 = new RADoc_Ctrl(controller);        
               
        radocObj1.cancel();
        radocObj1.save();
        radocObj1.genDynamicQuery(null);
        Test.stopTest();    
    }
}