Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Blue Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestContractValidation_Ctrl.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 
@Name            : TestContractValidation_Ctrl
@Author          : DS Conam
@Date            : Aug 03  , 2015
@Description     : Test Class for ContractValidation_Ctrl

 
 */
@isTest
private class TestContractValidation_Ctrl {
    static testMethod void myUnitTest() {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        RecordType rt = [SELECT 
                                id 
                        FROM 
                                RecordType 
                        WHERE 
                                sobjecttype = 'Opportunity' 
                        AND
                                name = 'New Opportunity' LIMIT 1 ];
                                
        Campaign camp = new Campaign();
        camp.name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        system.debug('>>>camp>>>'+camp);
        
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        system.debug('>>>Acc>>>'+Acc);
        
        Contact con = new Contact();
        con.accountId = acc.Id;
        con.lastName = 'test';
        insert con;
        
        system.debug('>>con>>>>'+con);
                
        Opportunity opp = new Opportunity();
        opp.name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.campaignId = camp.id;
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';
        opp.accountId=acc.id;
        
        insert opp;
        system.debug('>>>opp>>>'+opp);
        
        OpportunityContactRole  oppConRole = new OpportunityContactRole();
        oppConRole.contactId = con.Id;
        oppConRole.opportunityId  = opp.Id;
        oppConRole.role = 'Principal 1'; 
        oppConRole.isPrimary = true; 
        insert oppConRole;
        
        
        PageReference p=Page.Contract_Validation;
        Test.setCurrentPage(p);
        ApexPages.StandardController sc=new ApexPages.StandardController(opp);
        ApexPages.CurrentPage().getParameters().put('id',opp.id);
        
        ContractValidation_Ctrl cObj =new ContractValidation_Ctrl();
        cObj.doSave();   
        
        Test.stopTest();
        
    }
    
    static testMethod void myUnitTest2() {
        Test.startTest();
       /* RecordType rt = [SELECT 
                                id 
                        FROM 
                                RecordType 
                        WHERE 
                                sobjecttype = 'Opportunity' 
                        AND
                                name = 'New Opportunity' LIMIT 1 ];
                                
        Campaign camp = new Campaign();
        camp.name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        system.debug('>>>camp>>>'+camp);
        
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        system.debug('>>>Acc>>>'+Acc);
        
        Contact con = new Contact();
        con.accountId = acc.Id;
        con.lastName = 'test';
        insert con;
        */
                
        Opportunity opp = new Opportunity();
        opp.name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';       

        PageReference p=Page.Contract_Validation;
        Test.setCurrentPage(p);
        ApexPages.StandardController sc=new ApexPages.StandardController(opp);
        ApexPages.CurrentPage().getParameters().put('id',opp.id);
        
        ContractValidation_Ctrl cObj =new ContractValidation_Ctrl();
        cObj.doSave();  
        
        Test.stopTest();
        
    }

    
}