Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Campaign_Team__c</fullName>
        <formula>Campaign__r.Partner_Campaign_Team__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Campaign Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Partner_Campaign_Team__c</fullName>
        <label>Partner Campaign Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/OPEN_Dialer_Team_Counter_For_Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OPEN Dialer Team Counter For Opportunity</label>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Blue Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Campaign_Team__c</fullName>
        <formula>IF( ISBLANK(Campaign.Partner_Campaign_Team__c), &quot;OPEN&quot;, Campaign.Partner_Campaign_Team__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Campaign Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>Atlantic International- Sagar Handa</description>
        <label>ISO Sales Rep</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0995-CoCard/Charge it (Gary Ben-Houda)</fullName>
                </value>
                <value>
                    <fullName>Admar Capital, Inc.</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Adam Collins</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Alfred Cohen</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Andrew Lippman</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Danny Kogan</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Douglas Haddad</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Elaine Griner</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Francine Grimaldi</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - George Faham</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Jacob Lapidus</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Jane Joseph</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Mark Salem</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Michael Granat</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Michael Mansour</fullName>
                </value>
                <value>
                    <fullName>Advance Funds Network - Nathanial Sousan</fullName>
                </value>
                <value>
                    <fullName>Alliance Financial Services</fullName>
                </value>
                <value>
                    <fullName>All Merchant Funding LLC / All Bank Card</fullName>
                </value>
                <value>
                    <fullName>Allstate Merchant Services</fullName>
                </value>
                <value>
                    <fullName>ARF - Unknown</fullName>
                </value>
                <value>
                    <fullName>Aspen Merchant Capital</fullName>
                </value>
                <value>
                    <fullName>Atlantic International- Sagar Handa</fullName>
                </value>
                <value>
                    <fullName>B.L. Gibbs, Inc. dba Capital Fundings</fullName>
                </value>
                <value>
                    <fullName>Banc Certified- Gina Deniro</fullName>
                </value>
                <value>
                    <fullName>Bankcard Empire</fullName>
                </value>
                <value>
                    <fullName>Bankcard One, Inc. - Matt Milmeister</fullName>
                </value>
                <value>
                    <fullName>Bankers Merchant Services - Jack Froonjian</fullName>
                </value>
                <value>
                    <fullName>Bank Trans - Daniel Stein</fullName>
                </value>
                <value>
                    <fullName>Beverly Hills Processing</fullName>
                </value>
                <value>
                    <fullName>BPB - Jillian Pena</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_1_Counter_for_Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 1 Counter for Opportunity</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_2_Counter_For_Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 2 Counter for Opportunity</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_3_Counter_for_Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 3 Counter For Opportunity</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_4_Counter_For_Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 4 Counter For Opportunity</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Teams__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tiger_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Exclusion</label>
    <nameField>
        <displayFormat>U{000000}</displayFormat>
        <label>TT Exclusion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Exclusions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/OpportunityTriggerHandlertest.cls
@isTest
public class OpportunityTriggerHandlertest{

    public static testmethod  void assignCountersForRoundRobinOnInsert()
    { 
    
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
        FirstName = 'Darius',
        LastName = 'Polk',
        Email = 'puser000@amamama.com',
        Username = 'puser000@amamama.com' + System.currentTimeMillis(),
        CompanyName = 'TEST',
        Title = 'title',
        Alias = 'alias',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        isactive =  true
        );
        
        insert u;
        
        Tiger_Teams__c tt = new Tiger_Teams__c();
        tt.User__c = u.id;
        insert tt;
        
        
         OPEN_Dialer_Team_Counter_For_Opportunity__c od = new OPEN_Dialer_Team_Counter_For_Opportunity__c();
        od.Name = 'testName';
        od.Partner_Number__c = 0;
        insert od;
        
        Tiger_Team_1_Counter_for_Opportunity__c tiger1 = new Tiger_Team_1_Counter_for_Opportunity__c ();
        tiger1.Partner_Number__c = 2;
        tiger1.Name = 'Tiger Team 1 Counter';
        insert tiger1;
        
        Tiger_Team_2_Counter_for_Opportunity__c tiger2 = new Tiger_Team_2_Counter_for_Opportunity__c ();
        tiger2.Partner_Number__c = 2;
        tiger2.Name = 'Tiger Team 2 Counter';
        insert tiger2;
        
        Tiger_Team_3_Counter_for_Opportunity__c tiger3 = new Tiger_Team_3_Counter_for_Opportunity__c ();
        tiger3.Partner_Number__c = 2;
        tiger3.Name = 'Tiger Team 3 Counter';
        insert tiger3;
        
        Tiger_Team_4_Counter_for_Opportunity__c tiger4 = new Tiger_Team_4_Counter_for_Opportunity__c ();
        tiger4.Partner_Number__c = 2;
        tiger4.Name = 'Tiger Team 4 Counter';
        insert tiger4;
        
        
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        camp.partner_campaign_team__c = 'T1';
        insert camp;
        
        
        Campaign camp2 = new Campaign();
        camp2.Name = 'TestCamp';
        camp2.type = 'Internet';
        camp2.partner_campaign_team__c = 'T2';
        insert camp2;
        
        Campaign camp3 = new Campaign();
        camp3 .Name = 'TestCamp';
        camp3 .type = 'Internet';
        camp3 .partner_campaign_team__c = 'T3';
        insert camp3 ;
        
        Campaign camp4 = new Campaign();
        camp4.Name = 'TestCamp';
        camp4.type = 'Internet';
        camp4.partner_campaign_team__c = 'T4';
        insert camp4 ;
        
         Campaign camp5 = new Campaign();
        camp5.Name = 'TestCamp';
        camp5.type = 'Internet';
        //camp4.partner_campaign_team__c = 'T4';
        insert camp5 ;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.lastName = 'test';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.campaignId = camp.Id;
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';
        opp.AccountId=acc.Id;        
        insert opp;
        
        
        opp.campaignId = camp2.Id;
        update opp;
        
        opp.campaignId = camp3.Id;
        update opp;
        
        opp.campaignId = camp4.Id;
        update opp;
        
        opp.campaignId = camp5.Id;
        update opp;
        
        OPEN_Dialer_Team_Counter_For_Opportunity__c pn  = new OPEN_Dialer_Team_Counter_For_Opportunity__c();
        pn.name = 'test';
        pn.Partner_Number__c = 1;
        insert pn;
    }
}