Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Remaining_On_Lease__c</fullName>
        <label>Time Remaining On Site Lease/Mortgage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Additional_Locations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Locations</relationshipLabel>
        <relationshipName>Additional_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <label>DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Phone__c</fullName>
        <label>Landlord Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <label>Landlord</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Remaining_on_Lease__c</fullName>
        <label>Time Remaining on Lease</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-6 months</fullName>
                </value>
                <value>
                    <fullName>7-11 months</fullName>
                </value>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Additional Location</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Additional Locations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestExtjs_Bank_Statement.cls
@isTest 
private class TestExtjs_Bank_Statement  
{
/*
    static testMethod void Extjs_Bank_Statement_UnitTest2() 
    {
    
        // DS-CONAM CALC.ApexTesting();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        try
        {
            Extjs_Bank_Statement.describeFields('Additional_Locations', new List<String>{'DBA_Name__c'});
        }
        catch(Exception e)
        {
        }
    }
    
     static testMethod void Extjs_Bank_Statement_UnitTest4() 
    {
    
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
        
    }
    */
    static testMethod void Extjs_Bank_Statement_UnitTest3() 
    {
        Test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
        
        Extjs_Bank_Statement.CRUDData crudObj = new  Extjs_Bank_Statement.CRUDData();
        crudObj.sobjname = 'Additional_Locations__c';
        crudObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj.oppId = testAccount.Id;
        crudObj.parentFieldName = 'Account__c';
        
      /*  Extjs_Bank_Statement.CRUDData crudObj2 = new  Extjs_Bank_Statement.CRUDData();
        crudObj2.sobjname = '';
        crudObj2.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj2.oppId = testAccount.Id;
        crudObj2.parentFieldName = 'Account__c';
        
        Extjs_Bank_Statement.CRUDData crudObj3 = new  Extjs_Bank_Statement.CRUDData();
        crudObj3.sobjname = null;
        crudObj3.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj3.oppId = testAccount.Id;
        crudObj3.parentFieldName = 'Account__c';
        
        Extjs_Bank_Statement.CRUDData crudObj4 = new  Extjs_Bank_Statement.CRUDData();
        crudObj4.sobjname = 'Additional_Locations__c';
        crudObj4.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj4.oppId = testAccount.Id;
        crudObj4.parentFieldName = 'Account__c';
        
        Map<String, String> fieldMap4 = new Map<String, String>{'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c};
        crudObj4.records = new List<Map<String, String>>{fieldMap4};
        */
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        
        Map<String, String> fieldMap = new Map<String, String>{'Id' => aloc.Id, 'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c};
        crudObj.records = new List<Map<String, String>>{fieldMap};
       // crudObj2.records = null;
        
        Extjs_Bank_Statement.refreshObjects(crudObj, sobjList);
        Extjs_Bank_Statement.create(crudObj);
        Extjs_Bank_Statement.updat(crudObj);
        Extjs_Bank_Statement.CRUDResponse crdrespose = Extjs_Bank_Statement.delet(crudObj);
        /*
        Extjs_Bank_Statement.create(crudObj2);
        Extjs_Bank_Statement.updat(crudObj2);
        
        Extjs_Bank_Statement.create(crudObj3);
        Extjs_Bank_Statement.create(crudObj4);
        */
        Test.stopTest();
    }
    
    
    static testMethod void Extjs_Bank_Statement_UnitTest31() 
    {
        Test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
               
        Extjs_Bank_Statement.CRUDData crudObj2 = new  Extjs_Bank_Statement.CRUDData();
        crudObj2.sobjname = '';
        crudObj2.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj2.oppId = testAccount.Id;
        crudObj2.parentFieldName = 'Account__c';
        
       
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        
        crudObj2.records = null;
        
        Extjs_Bank_Statement.create(crudObj2);
        Extjs_Bank_Statement.updat(crudObj2);
        Test.stopTest();
      
    }
    
    static testMethod void Extjs_Bank_Statement_UnitTest32() 
    {
        Test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
        
        
        
        Extjs_Bank_Statement.CRUDData crudObj3 = new  Extjs_Bank_Statement.CRUDData();
        crudObj3.sobjname = null;
        crudObj3.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj3.oppId = testAccount.Id;
        crudObj3.parentFieldName = 'Account__c';
        
       
        
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        

        Extjs_Bank_Statement.create(crudObj3);
         Test.stopTest();
    }
    
    static testMethod void Extjs_Bank_Statement_UnitTest33() 
    {
        Test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusibess';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
        
        
        
        Extjs_Bank_Statement.CRUDData crudObj4 = new  Extjs_Bank_Statement.CRUDData();
        crudObj4.sobjname = 'Additional_Locations__c';
        crudObj4.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj4.oppId = testAccount.Id;
        crudObj4.parentFieldName = 'Account__c';
        
        Map<String, String> fieldMap4 = new Map<String, String>{'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c};
        crudObj4.records = new List<Map<String, String>>{fieldMap4};
        
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        

        Extjs_Bank_Statement.create(crudObj4);
        Test.stopTest();
    }
    
    /*
    static testMethod void Extjs_Bank_Statement_UnitTest1() 
    {
    
        // DS-CONAM CALC.ApexTesting();
        Account testAccount1 = new Account();
        testAccount1.name = 'Test Account1';
        testAccount1.BusinessType__c = 'testBusibess';
        insert testAccount1;
        
        Additional_Locations__c  aloc1 = new Additional_Locations__c();
        aloc1.DBA_Name__c = 'test';
        aloc1.Account__c = testAccount1.Id;
        insert aloc1;
        
        Extjs_Bank_Statement.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Bank_Statement.QueryObj queryObj = new Extjs_Bank_Statement.QueryObj( );
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount1.Id;
        queryObj.start = 0;
        queryObj.recordCount = 210;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> param1Map = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        Map<String, String> param2Map = new Map<String, String>{'direction' => 'DESC', 'property' => 'Street__c'};
        
        queryObj.sortParams.add(param1Map );
        queryObj.sortParams.add(param2Map );
        Extjs_Bank_Statement.query(queryObj);
        
        Extjs_Bank_Statement.CRUDData crudObj = new  Extjs_Bank_Statement.CRUDData();
        crudObj.sobjname = 'Additional_Locations__c';
        crudObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj.oppId = testAccount1.Id;
        crudObj.parentFieldName = 'Account__c';
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc1 );
        Map<String, String> fieldMap = new Map<String, String>{'Id' => aloc1.Id, 'Street__c' => aloc1.Street__c, 'Phone__c' => aloc1.Phone__c};
        crudObj.records = new List<Map<String, String>>{fieldMap};
        
        Extjs_Bank_Statement.refreshObjects(crudObj, sobjList);
        Extjs_Bank_Statement.create(crudObj);
        Extjs_Bank_Statement.updat(crudObj);
        Extjs_Bank_Statement.CRUDResponse crdrespose = Extjs_Bank_Statement.delet(crudObj);
    }
    */
}