Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Partner_Category__c</fullName>
        <label>Partner Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Asset Backed Lender</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processor</fullName>
                </value>
                <value>
                    <fullName>Credit Union</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing Company</fullName>
                </value>
                <value>
                    <fullName>High Quality Originator</fullName>
                </value>
                <value>
                    <fullName>High Volume Originator</fullName>
                </value>
                <value>
                    <fullName>ISO</fullName>
                </value>
                <value>
                    <fullName>Lead Generator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/PartnerCategoryLead__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting For Lead</description>
    <label>PartnerCategoryLead</label>
</CustomObject>

Rapid Prd/src/classes/TestLeadPartnerCategoryEditExtn.cls
/**
@Name            : TestLeadPartnerCategoryEditExtn
@Author          : Mk-Conam
@Date            : Nov 12  , 2015
@Description     : Test Class for AccountPartnerCategoryEditExtn
**/

@isTest

private class TestLeadPartnerCategoryEditExtn
{  
    static testMethod void unitTest()
    {
        Test.startTest();     
        
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign cmp = new campaign();
        cmp.Name = 'TestCamp';
        insert cmp;
        
        Lead led = new Lead();
        led.Company = 'Test Company1';
        led.FirstName='First Name1';
        led.LastName='Last Name1';
        led.LeadSource='Twitter';
        led.Status='Initial Call Made';
        insert led;
        
        CampaignMember newMember = new CampaignMember();
        newMember.campaignid=cmp.id;
        newMember.leadid=led.id;
        newMember.status='sent';
        insert newMember; 
        
        CampaignMember cmpM = [select LeadId from CampaignMember where Leadid =:led.Id Limit 1];
        
        PartnerCategoryLead__c pcObj=new PartnerCategoryLead__c();
        pcObj.Name='Leadant';
        insert pcObj; 
        
        pcObj=new PartnerCategoryLead__c();
        pcObj.Name='Agent/MLS-US';
        insert pcObj;
                
        pcObj=new PartnerCategoryLead__c();
        pcObj.Name='Franchise';
        insert pcObj; 
 
        Lead aTemp=[Select 
                                id, name
                       from
                                Lead
                       where 
                                Company ='Test Company1' Limit 1];
                                
        PageReference pPage=Page.AccountPartnerCategoryEdit;
        Test.setCurrentPage(pPage);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(aTemp);
        LeadPartnerCategoryEditExtn ctrl=new LeadPartnerCategoryEditExtn(sc);
        
        ApexPages.CurrentPage().getParameters().put('id',aTemp.id);
        ctrl=new LeadPartnerCategoryEditExtn(sc);
        ctrl.onSave();
        
        Partner_Category__c p1=new Partner_Category__c();
        p1.name='Leadant';
        p1.Partner_Lead__c=aTemp.id;
        p1.Sort_Order__c=1;
        insert p1;
        
        p1=new Partner_Category__c();
        p1.Partner_Lead__c=aTemp.id;
        p1.name='Franchise';
        p1.Sort_Order__c=1;
        insert p1;      
        
        ctrl=new LeadPartnerCategoryEditExtn(sc);
        ctrl.onSave();        
        
        String  message3 ='';
        message3+= 'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        message3+=  'TestStringMessage01212121212121212121212121212121212121212121212121212121212121212121212121';
        ctrl.outputMessage =message3;
        
        String sTemp=ctrl.outputMessage;
        
        Test.stopTest();
        
    }
    
    static testMethod void unitTest2()
    {
        Test.startTest(); 
         
        Lead led = new Lead();     

        PageReference pPage=Page.LeadPartnerCategoryEdit;
        Test.setCurrentPage(pPage);
        
        ApexPages.StandardController sc=new ApexPages.StandardController(led );
        LeadPartnerCategoryEditExtn ctrl=new LeadPartnerCategoryEditExtn(sc);
        ctrl.message ='TestMessage';
        ctrl.PrimaryMessage ='TestPrimary';
        ctrl.outputMessage ='';
        ctrl.led= ((Lead)new Lead());
        
        try
        {
            ctrl.onSave();
        }
        catch(Exception e)
        {
        }
        Test.stopTest();    
    } 
  
}