Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_ROI__c</fullName>
        <label>Current ROI</label>
        <summarizedField>Opportunity.Current_ROI__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.Remaining_Balance__c</field>
            <operation>notEqual</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Database_Entry_Due_Date__c</fullName>
        <label>Account Database Entry Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Database_Entry__c</fullName>
        <label>Account Database Entry</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Applicant_2_FICO__c</fullName>
        <label>Applicant #2 FICO</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Category__c</fullName>
        <inlineHelpText>If updated with new category, add similar to &quot;What type of Business is it?&quot; in UW Object.</inlineHelpText>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Antiques/Collectibles</fullName>
                </value>
                <value>
                    <fullName>Appliance Stores</fullName>
                </value>
                <value>
                    <fullName>Arrangements</fullName>
                </value>
                <value>
                    <fullName>Art Galleries</fullName>
                </value>
                <value>
                    <fullName>Audio Equipment</fullName>
                </value>
                <value>
                    <fullName>Automobile Dealerships New/Used</fullName>
                </value>
                <value>
                    <fullName>Automotive - Body Repair, Collision, Painting</fullName>
                </value>
                <value>
                    <fullName>Automotive - Brake and Muffler</fullName>
                </value>
                <value>
                    <fullName>Automotive - General Repair, Truck, RV</fullName>
                </value>
                <value>
                    <fullName>Automotive - Parts, Accessories</fullName>
                </value>
                <value>
                    <fullName>Automotive - Quick Sevice, Lube, Tune-Up</fullName>
                </value>
                <value>
                    <fullName>Automotive - Tire, Glass</fullName>
                </value>
                <value>
                    <fullName>Automotive - Towing &amp; Emergency Road Service</fullName>
                </value>
                <value>
                    <fullName>Automotive - Transmission</fullName>
                </value>
                <value>
                    <fullName>Bar</fullName>
                </value>
                <value>
                    <fullName>Barber Shop</fullName>
                </value>
                <value>
                    <fullName>Bicycle Repair</fullName>
                </value>
                <value>
                    <fullName>Bicycles/Motorcycles Shops</fullName>
                </value>
                <value>
                    <fullName>Bicycle Sales</fullName>
                </value>
                <value>
                    <fullName>Billing Services</fullName>
                </value>
                <value>
                    <fullName>Boating/Marina</fullName>
                </value>
                <value>
                    <fullName>Book and Stationary</fullName>
                </value>
                <value>
                    <fullName>Bowling</fullName>
                </value>
                <value>
                    <fullName>Bridal Shop</fullName>
                </value>
                <value>
                    <fullName>Car Alarm Supplier</fullName>
                </value>
                <value>
                    <fullName>Carpet Store</fullName>
                </value>
                <value>
                    <fullName>Car Wash</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Check Cashing Companies</fullName>
                </value>
                <value>
                    <fullName>Cigar Cigarette &amp; Tobacco Dealer-Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bad Landlord Reference</fullName>
                </value>
                <value>
                    <fullName>Business for sale</fullName>
                </value>
                <value>
                    <fullName>Can&apos;t pay off current advance</fullName>
                </value>
                <value>
                    <fullName>Closed for the season</fullName>
                </value>
                <value>
                    <fullName>Confirmed Fraud</fullName>
                </value>
                <value>
                    <fullName>Derogatory Business Report</fullName>
                </value>
                <value>
                    <fullName>Derogatory Credit</fullName>
                </value>
                <value>
                    <fullName>Gas Co does processing</fullName>
                </value>
                <value>
                    <fullName>Going out of business</fullName>
                </value>
                <value>
                    <fullName>High Chargeback Ratio</fullName>
                </value>
                <value>
                    <fullName>High Risk Business Type</fullName>
                </value>
                <value>
                    <fullName>Home based business</fullName>
                </value>
                <value>
                    <fullName>Inconsistent or Fluctuating Processing History</fullName>
                </value>
                <value>
                    <fullName>Insufficient Time on Lease</fullName>
                </value>
                <value>
                    <fullName>Limited Experience as Owner</fullName>
                </value>
                <value>
                    <fullName>Merchant withdrew</fullName>
                </value>
                <value>
                    <fullName>Negative SIte Inspection</fullName>
                </value>
                <value>
                    <fullName>No Credit Score</fullName>
                </value>
                <value>
                    <fullName>No Proof of Ownership</fullName>
                </value>
                <value>
                    <fullName>No statements</fullName>
                </value>
                <value>
                    <fullName>Not enough time in business</fullName>
                </value>
                <value>
                    <fullName>Not enough V/MC volume</fullName>
                </value>
                <value>
                    <fullName>Open bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Tender-shift Risk or Too Few Transactions</fullName>
                </value>
                <value>
                    <fullName>Too expensive</fullName>
                </value>
                <value>
                    <fullName>Too few transactions</fullName>
                </value>
                <value>
                    <fullName>Uses Pay Pal</fullName>
                </value>
                <value>
                    <fullName>V/MC Too Much of Overall Business</fullName>
                </value>
                <value>
                    <fullName>Wanted more than max quote</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_ROI__c</fullName>
        <label>Current % ROI</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Estimated_Daily_Transactions__c</fullName>
        <formula>IF( or(CONTAINS(TEXT(Product__c),&quot;Loan&quot;),CONTAINS(TEXT(Product__c),&quot;Line&quot;)),if(isblank( Loan_Term_Days__c ),0,Pay_Back_Amount__c / Loan_Term_Days__c ), if(isblank(Estimated_Days_to_Repay__c),0,Pay_Back_Amount__c / Estimated_Days_to_Repay__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estimated Daily Transactions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funded_by_WC__c</fullName>
        <label>Funds Wired</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Applicant_1_FICO_Score__c</fullName>
        <label>Manual Applicant 1 FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manual_Applicant_2_FICO_Score__c</fullName>
        <label>Manual Applicant 2 FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PSOE_Business_Term__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Term</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Packet_Preparation_Sent__c</fullName>
        <label>Packet Preparation Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Processing_Representative__c</fullName>
        <description>What RapidAdvance Processing Rep has this account?</description>
        <label>Processing Representative</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atiya</fullName>
                </value>
                <value>
                    <fullName>Cassandra</fullName>
                </value>
                <value>
                    <fullName>Destinie</fullName>
                </value>
                <value>
                    <fullName>Mark Deputy</fullName>
                </value>
                <value>
                    <fullName>Shawntavia</fullName>
                </value>
                <value>
                    <fullName>Tina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIC_CODE__c</fullName>
        <label>SIC CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Entity__c</fullName>
        <label>Type of Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Unable To Confirm by QC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UW_Underwriter_Assigned__c</fullName>
        <formula>text( Underwriting__r.Underwriter_Assigned__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Underwriter Assigned (Old)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/FundingInfoSignOff_Ctrl.cls
/*
@Name               : FundingInfoSignOff_Ctrl 
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        : @Revision History   : Uses of psoe loan key suppliment ,RA Finance Calc ,psoe voided check ,received rapid funding addendum  
                      green r errors ,psoe no qc calc ,Funding Checklist Error ,mla addendum ,PSOE Competitor Payoff ,rapid funding addendum ,
                      psoe funding checklist  Removed/Commented BY MK Conam 2 Dec 2015 

*/
public with sharing class FundingInfoSignOff_Ctrl 
{

    public Opportunity oppRecord{get; set;}
    public Account accRecord{get; set;}
    public Decimal applicant1FICO{get; private set;}
    public Decimal yrsInBusiness{get; private set;}      
    public fundingInfoSignOff_Ctrl()
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');        
        if (oppId != null && oppId.trim() != '')
        {
            List<Opportunity> oppList = [SELECT 
                                            Id, Type_of_Entity__c, Legal_Name__c, Current_ROI__c, OwnerId, Processing_Representative__c, 
                                            UW_Underwriter_Assigned__c,Product__c, Amount, Pay_Back_Amount__c,Packet_Preparation_Sent__c,
                                            Percent_Payback__c, Estimated_Daily_Transactions__c, 
                                            SIC_CODE__c, Business_Category__c, Applicant_2_FICO__c,Account_Database_Entry_Due_Date__c, 
                                            AccountId,Manual_Applicant_1_FICO_Score__c, Manual_Applicant_2_FICO_Score__c, Closed_Reason__c,
                                            PSOE_Business_Term__c, Account_Database_Entry__c, Funded_by_WC__c, Funding_Status__c, CloseDate
                                        FROM 
                                            Opportunity 
                                        WHERE 
                                            Id = :oppId 
                                        LIMIT 1];                                            
            if (!oppList.isEmpty())
            {
                oppRecord = oppList.get(0); 
                List<Account> accountList = [SELECT 
                                                Id, Name, Legal_Name__c,
                                                BillingStreet, BillingCity, BillingState, BillingPostalCode, 
                                                Number_of_Locations__c,Number_of_Terminals_at_Location__c
                                            FROM 
                                                Account 
                                            WHERE 
                                                Id =:oppRecord.AccountId];
                                                
                accRecord=!accountList.isEmpty() ? accountList.get(0) : new Account();
            }            
            applicant1FICO = FormulaFieldUtility.ccApplicant1FICO;
            yrsInBusiness = FormulaFieldUtility.yrsInBusiness;
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
    
    public PageReference doSave() 
    {
        Savepoint sp = Database.setSavepoint();
        try
        {
            if(accRecord != null) 
            {
                upsert accRecord;
                if(accRecord.Id != null) 
                {
                    oppRecord.AccountId = accRecord.Id;    
                }    
            }
            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Funding Info Sign Off Information Saved Successfully!'));
        }
        catch(Exception e)
        { 
            Database.rollback(sp); 
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        } 
            return null;
    }
}