Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/DistributorGreenTree__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used to store the default owner for Green Tree opportunities which will be the used as the Distributor From in Lead distribution engine currently Jeff Hageman</description>
    <label>Distributor Green Tree</label>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Blue Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTF_Qualified__c</fullName>
        <description>For Greentree</description>
        <label>GTF Qualified</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>If_Renewal_Preceding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>If Renewal, Preceding Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Renewal_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Representative__c</fullName>
        <description>What RapidAdvance Processing Rep has this account?</description>
        <label>Processing Representative</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atiya</fullName>
                </value>
                <value>
                    <fullName>Cassandra</fullName>
                </value>
                <value>
                    <fullName>Destinie</fullName>
                </value>
                <value>
                    <fullName>Mark Deputy</fullName>
                </value>
                <value>
                    <fullName>Shawntavia</fullName>
                </value>
                <value>
                    <fullName>Tina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rapid_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rapid Opportunity from which Green Tree Opportunity was created</inlineHelpText>
        <label>Preceding Rapid Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Green Tree Opportunity</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Risk_Employee__c</fullName>
        <label>Risk Employee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deborah Oliver</fullName>
                </value>
                <value>
                    <fullName>Gil Bowen</fullName>
                </value>
                <value>
                    <fullName>Marlowe Rogers</fullName>
                </value>
                <value>
                    <fullName>Tony Brown</fullName>
                </value>
                <value>
                    <fullName>Vanessa Waller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fires off a workflow to send an Email notification</description>
        <label>Send Risk Alert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>GreenTree</fullName>
        <active>true</active>
        <businessProcess>GreenTree</businessProcess>
        <label>GreenTree</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/User_Lookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Quick reference list of emails associated with particular strings, for conversion from Picklist values.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>User Lookup</label>
</CustomObject>

Rapid Prd/src/classes/TestMasterOpportunityTrigger.cls
/**
@Name            : TestMasterOpportunityTrigger
@Author          : MK Conam
@Date            : Aug 28 2015
@Description     : Test Class for OpportunityTriggerHandler
**/

@isTest

private class TestMasterOpportunityTrigger 
{    
    @testSetup static void setup()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.lastName = 'test';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.campaignId = camp.Id;
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';
        opp.AccountId=acc.Id;        
        insert opp;
    
    }
    static testMethod voId unitTestRiskAlert()
    {
        // DS-CONAM CALC.ApexTesting(); 
        Test.startTest();
        try
        {
            User_Lookup__c test1 = new User_Lookup__c(Name = 'test1', Email__c = 'test@test.com');
            insert test1;
            User_Lookup__c test2 = new User_Lookup__c(Name = 'test2', Email__c = 'test2@test.com');
            insert test2;
    
            Opportunity o = new Opportunity();
            o.Name = 'Test Opp';
            o.StageName = 'Credit Pulled';
            o.CloseDate = Date.today();
            o.Send_Risk_Alert__c =true;
            Database.SaveResult sr = Database.insert(o);
    
            String oppId = sr.GetId();
            o.Processing_Representative__c = 'test1';
            o.Risk_Employee__c = 'test2';
            update o;
    
            Opportunity[] o_query = [SELECT Id,Send_Risk_Alert__c FROM Opportunity WHERE Id=: oppId];
           //System.assertEquals(true, o_query[0].Send_Risk_Alert__c);
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    }
    
    static testMethod voId unitTestContactRolesOppr()
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();
        try
        {
            RecordType rt = [SELECT 
                                Id 
                            FROM 
                                RecordType 
                            WHERE 
                                sObjectType = 'Opportunity' 
                            AND
                                Name = 'New Opportunity' LIMIT 1 ];
            
            Opportunity opp=[select
                                    id
                            from
                                    Opportunity
                            where 
                                    name='TestingOpp' Limit 1];                        
            
            Account acc=[select
                                    id
                            from
                                    Account 
                            where 
                                    name='Test Account1' Limit 1];   
            Contact con = [select
                                    id
                            from
                                    Contact
                            where 
                                    lastname='test' Limit 1];  
            Campaign cam=[select
                                    id
                            from
                                    Campaign 
                            where 
                                    name='TestCamp' Limit 1]; 
            
            OpportunityContactRole  oppConRole = new OpportunityContactRole();
            oppConRole.contactId = con.Id;
            oppConRole.opportunityId  = opp.Id;
            oppConRole.role = 'Principal 1'; 
            oppConRole.isPrimary = true; 
            insert oppConRole;        
            
            Opportunity opp1 = new Opportunity();
            opp1.Name = 'TestingOpp';
            opp1.leadSource = 'A001';
            opp1.campaignId = cam.Id;
            opp1.closeDate = date.newInstance(2007, 5, 5);
            opp1.stageName = 'Prospecting';
            opp1.current_Processor__c = 'Blue Pay';
            opp1.if_Renewal_Preceding_Opportunity__c = opp.Id;
            opp1.AccountId=acc.Id;
            insert opp1;
        }
        catch(Exception e)
        {
            System.debug(e);
        }
        Test.stopTest();
    }
   
    static testMethod voId unitTestUpdateOpportunityForBiz2Credit()
    {
        // DS-CONAM CALC.apexTesting();
        Test.startTest();
        try
        {
            Campaign cam=[select
                                    id
                            from
                                    Campaign 
                            where 
                                    name='TestCamp' Limit 1];
            
            Opportunity opp=[select
                                    id
                            from
                                    Opportunity
                            where 
                                    name='TestingOpp' Limit 1];    
            
            Opportunity opp1 =[SELECT
                                    Name,Id,StageName,Status__c,CloseDate,CampaignId 
                                FROM
                                     Opportunity 
                                 WHERE Id=: opp.Id ];
            update opp1;
            // System.assertEquals(true, opp1[0].Status__c);
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    }
    
    static testMethod voId unitTestUpdateGTParentOpportunity()
    {
        // DS-CONAM CALC.apexTesting();
        Test.startTest();
        try
        {
            List<RecordType> gId=[SELECT
                            Id
                      FROM
                            RecordType
                      WHERE
                            sObjectType='Opportunity'
                      AND
                            DeveloperName='GreenTree'];
            Opportunity opp=[select
                                    id
                            from
                                    Opportunity
                            where 
                                    name='TestingOpp' Limit 1];   
            Account acc=[select
                                    id
                            from
                                    Account 
                            where 
                                    name='Test Account1' Limit 1];  
            Campaign cp=[select
                                    id
                            from
                                    Campaign 
                            where 
                                    name='TestCamp' Limit 1];      
            
            Opportunity gOpp = new Opportunity();
            gOpp.Name='GoppName';
            gOpp.AccountId=acc.Id;
            gOpp.RecordTypeId=gId.get(0).Id;
            gOpp.ForecastCategoryName='Commit';
            gOpp.LeadSource='A001';
            gOpp.CampaignId=cp.Id;
            gOpp.CloseDate=system.today();
            gOpp.Current_Processor__c='1st federal financial';
            gOpp.StageName='Initial Call Needed';
            gOpp.RapId_Opportunity__c=opp.Id;
            insert gOpp;
            
            Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
            gt.opportunity__c=gOpp.Id;
            insert gt;
            
            

            gOpp.GTF_Qualified__c='No';
            update gOpp;    
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    } 
   
    static testMethod voId unitTestCreateGreenTreeOpp()
    {
        Test.startTest();
        try
        {
            List<RecordType> gId=[SELECT
                                        Id
                                  FROM
                                        RecordType
                                  WHERE
                                        sObjectType='Opportunity'
                                  AND
                                        DeveloperName='GreenTree'];
            
            User u=[SELECT 
                        Id 
                    FROM 
                        User 
                    WHERE 
                        Profile.Name='System Administrator'
                    AND 
                        isActive=true LIMIT 1];
            
            DistributorGreenTree__c g=new DistributorGreenTree__c();
            g.Name=u.Id;
            insert g;
            
            Account ac= new Account();
            ac.Name='testcase';
            insert ac;
            
            Campaign cp= new Campaign();
            cp.Name='cppName';
            insert cp;
           
            Opportunity opp = new Opportunity();
            opp.Name='oppName';
            opp.AccountId=ac.Id;
            opp.ForecastCategoryName='Commit';
            opp.LeadSource='A001';
            opp.CampaignId=cp.Id;
            opp.CloseDate=system.today();
            opp.Current_Processor__c='1st federal financial';
            opp.StageName='Credit Pulled';
            insert opp;
            
            opp.StageName='Pending Management Review';
            update opp;    
        }
        catch(Exception e)
        {
        }
        Test.stopTest();    
    }
    
    static testMethod voId unitTestCreateGTOppOnUpdate()
    {
        Test.startTest();
        try
        {
            List<RecordType> gId=[SELECT
                                        Id
                                  FROM
                                        RecordType
                                  WHERE
                                        sObjectType='Opportunity'
                                  AND
                                        DeveloperName='GreenTree'];
            
            User u=[SELECT 
                        Id 
                    FROM 
                        User 
                    WHERE 
                        Profile.Name='System Administrator'
                    AND 
                        isActive=true LIMIT 1];
            
            DistributorGreenTree__c g=new DistributorGreenTree__c();
            g.Name=u.Id;
            insert g;
            
            Account ac= new Account();
            ac.Name='testcase';
            insert ac;
            
            Campaign cp= new Campaign();
            cp.Name='cppName';
            insert cp;
           
            Opportunity opp = new Opportunity();
            opp.Name='oppName';
            opp.AccountId=ac.Id;
            opp.ForecastCategoryName='Commit';
            opp.LeadSource='A001';
            opp.CampaignId=cp.Id;
            opp.CloseDate=system.today();
            opp.Current_Processor__c='1st federal financial';
            opp.StageName='Credit Pulled';
            insert opp;
            
            opp.recordTypeId=gId.get(0).id;
            update opp;    
        }
        catch(Exception e)
        {
            System.debug(e);
        }
        Test.stopTest();    
    }    
    
    static testmethod void populateLdSourceonRenewalOppsTest() {
       
        Test.startTest(); 
        Account acc = new Account(Name='Account1');
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'Opp 2016',AccountId=acc.id,CloseDate=System.Today(),StageName='Closed Won',LeadSource='Web');
        insert opp;
        
        Opportunity oppnew = new Opportunity(Name = 'Opp 2017',AccountId=acc.id,CloseDate=System.Today(),StageName='Prospecting',Renewal__c=true);
        insert oppnew;
               
        Test.stopTest();
    }
}