Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category_Contains_Banks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Category Contains Banks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Contains_CUSO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Category Contains CUSO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Contains_Credit_Union__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Category Contains Credit Union</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Agent/MLS-US</fullName>
                </value>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Banks</fullName>
                </value>
                <value>
                    <fullName>Broker/Intermediary</fullName>
                </value>
                <value>
                    <fullName>Cash Brokers</fullName>
                </value>
                <value>
                    <fullName>Commercial Real Estate</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Credit Unions</fullName>
                </value>
                <value>
                    <fullName>CUSO</fullName>
                </value>
                <value>
                    <fullName>Econcomic Development</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Government Contractor</fullName>
                </value>
                <value>
                    <fullName>High Quality Originator</fullName>
                </value>
                <value>
                    <fullName>High Volume Originator</fullName>
                </value>
                <value>
                    <fullName>Inventory Fianncing</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-CANADA</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-US</fullName>
                </value>
                <value>
                    <fullName>Lead Generator</fullName>
                </value>
                <value>
                    <fullName>Networking/COI</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Finance</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnerships</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <label>Partner Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnership</fullName>
                </value>
                <value>
                    <fullName>Financial Institutions Group</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Agent/MLS-US</fullName>
                </value>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Banks</fullName>
                </value>
                <value>
                    <fullName>Broker/Intermediary</fullName>
                </value>
                <value>
                    <fullName>Cash Brokers</fullName>
                </value>
                <value>
                    <fullName>Commercial Real Estate</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Credit Unions</fullName>
                </value>
                <value>
                    <fullName>CUSO</fullName>
                </value>
                <value>
                    <fullName>Economic Development</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Government Contractor</fullName>
                </value>
                <value>
                    <fullName>High Quality Originator</fullName>
                </value>
                <value>
                    <fullName>High Volume Originator</fullName>
                </value>
                <value>
                    <fullName>Inventory Fianncing</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-CANADA</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-US</fullName>
                </value>
                <value>
                    <fullName>Lead Generator</fullName>
                </value>
                <value>
                    <fullName>Networking/COI</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Finance</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnerships</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <label>Partner Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Banks</fullName>
                </value>
                <value>
                    <fullName>Credit Unions</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnership</fullName>
                </value>
                <value>
                    <fullName>Financial Institutions Group</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/MultiselectController.cls
Public with sharing class MultiselectController {
    
    // SelectOption lists for public consumption
    public SelectOption[] leftOptions {get;set;}
    public SelectOption[] rightOptions {get;set;}
    public String accid {get;set;}
    public String accountid {get;set;}
    public String sObjType {get;set;}
    public Boolean buttonVisible{get;set;}
    // Parse &-separated values and labels from value and 
    // put them in option
    private void setOptions(SelectOption[] options, String value) {
        if(options!=null)
        options.clear();
        String[] parts = value.split('&');
        
        for (Integer i = 0; i < parts.size() / 2; i++) {
        System.debug(parts);
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }
    }

    // Backing for hidden text field containing the options from the left list
    public String leftOptionsHidden {
        get;
        set {
            leftOptionsHidden = value;
            System.debug(value);
            setOptions(leftOptions, value);
        }
    }

    // Backing for hidden text field containing the options from the right list
    public String rightOptionsHidden {
        get;
        set {
            rightOptionsHidden = value;
            setOptions(rightOptions, value);
        }
    }

    public PageReference saveAccount()
    {
        System.debug('rightOptionsHidden  is ' + rightOptionsHidden);
        PageReference p=null;
        if(rightOptionsHidden!=null && rightOptionsHidden.length()>0)
        {
            List <SelectOption> options = new List <SelectOption> ();
            
            String message='';
            String[] parts = rightOptionsHidden.split('&');
            for (Integer i = 0; i <parts.size() / 2; i++) 
            {
                options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
                EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
            }
    
            List <Partner_Category__c> newRecordsList = new List <Partner_Category__c> ();
            List<Account> accountList=new List<Account>();
            Map<id, Account> accMap=new Map<id, Account>();
            Boolean first = false;
            String Primary;
            integer sortOrder = 0;
            Account acc=new Account(id=accountid);
            acc.Category_Contains_Banks__c=false;
            acc.Category_Contains_CUSO__c=false;
            acc.Category_Contains_Credit_Union__c=false;
            
            for (SelectOption so: options) 
            {
                sortOrder++;
                Partner_Category__c newRecord = new Partner_Category__c();
                newRecord.Partner_Account__c = accountid;
                newRecord.Name = so.getLabel();
                newRecord.Sort_Order__c = sortOrder;
    
                if (first == true) {
                    Primary = so.getLabel();
                    first = false;
                } else {
                    message = message + ';';
                    message += so.getLabel();
                }    
                newRecordsList.add(newRecord);
                //CA lenders license
                // account should be added only once
                if(accMap.containsKey(accountid))
                {
                    if(so.getLabel()=='Banks')
                        acc.Category_Contains_Banks__c=true;
                
                    if(so.getLabel()=='CUSO')
                        acc.Category_Contains_CUSO__c=true;
                        
                    if(so.getLabel()=='Credit Unions')
                        acc.Category_Contains_Credit_Union__c=true;
                        
                    accMap.put(accountid,acc);
                }
                else
                {
                    if(so.getLabel()=='Banks')
                        acc.Category_Contains_Banks__c=true;
                
                    if(so.getLabel()=='CUSO')
                        acc.Category_Contains_CUSO__c=true;
                        
                    if(so.getLabel()=='Credit Unions')
                        acc.Category_Contains_Credit_Union__c=true;
                    accMap.put(accountid,acc);
                }
            }
            System.debug('>>>>.accMap.size() '+accMap.size());
             System.debug('>>>>.accMap() '+accMap);
            if(accMap.size()>0)
            {
                for(Id iTemp : accMap.keyset())
                {
                    accountList.add(accMap.get(iTemp ));
                }
            }
            System.debug('message ' + message);
            System.debug('newRecordsList.size ' + newRecordsList.size());
            if (newRecordsList.size() >= 0) {
                // get existing records and delete them and insert new record
                List <Partner_Category__c> delRecordsList = new List <Partner_Category__c> ();
                delRecordsList = [select id from Partner_Category__c where Partner_Account__c = : accountid];
               
                List <Account> accTemp = [select Category__c from account where id = : accountid];
                SavePoint sp = Database.setSavePoint();
                try {
                   if (delRecordsList.size() > 0) 
                       delete delRecordsList;
                    
                    if (newRecordsList.size() > 0) {
                        accTemp[0].Category__c=message;
                        update accTemp;
                        insert newRecordsList;
                        /*
                        if(accountList.size()>0)
                            update accountList;
                        */
                    } else if (newRecordsList.size() == 0) {
                        accTemp.get(0).Category__c='';
                        accTemp.get(0).Category_Contains_Banks__c=false;
                        accTemp.get(0).Category_Contains_CUSO__c=false;
                        accTemp.get(0).Category_Contains_Credit_Union__c=false;
                        update accTemp;
                    }
    
                } catch (Exception e) {
                    System.Debug('An exception has occured ' + e.getLineNumber() + ' ' + e.getMessage());
                    Database.Rollback(sp);
                }
    
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL ,'Please select a partner category'));
            p=null;
             
        }
        return p;
    }


    public PageReference saveLead() {
        List <SelectOption> options = new List <SelectOption> ();
        System.debug('rightOptionsHidden  is ' + rightOptionsHidden);
        String message='';
        //Integer sortOrder = 0;
        String[] parts = rightOptionsHidden.split('&');
        for (Integer i = 0; i < parts.size() / 2; i++) {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }

         List <Partner_Category__c> newRecordsList = new List <Partner_Category__c> ();
 
        Boolean first = true;
        String Primary;
        integer sortOrderL = 0;
        for (SelectOption so: options) {
            sortOrderL++;
            Partner_Category__c newRecord = new Partner_Category__c();
            newRecord.Partner_Lead__c = accountid ;
            newRecord.Name = so.getLabel();
            newRecord.Sort_Order__c = sortOrderL;

            if (first == true) {
              //  message = so.getLabel();
                Primary = so.getLabel();
                first = false;
            } else {
                message = message + ';';
                message += so.getLabel();
            }


            newRecordsList.add(newRecord);

        }
        System.debug('message ' + message);
        System.debug('newRecordsList.size ' + newRecordsList.size());
        if (newRecordsList.size() >= 0) {
            // get existing records and delete them and insert new record
            List <Partner_Category__c> delRecordsList = new List <Partner_Category__c> ();
            delRecordsList = [select id from Partner_Category__c where Partner_Lead__c = : accountid ];
            List <Lead> leadTemp = [select  Category__c from Lead where id = : accountid ];
            SavePoint sp = Database.setSavePoint();
            try {
               if (delRecordsList.size() > 0) delete delRecordsList;
                if (newRecordsList.size() > 0) {
                   // leadTemp[0].Partner_Channel__c = Primary;
                    leadTemp[0].Category__c=message;
                    update leadTemp;
                    insert newRecordsList;

                } else if (newRecordsList.size() == 0) {
                    // leadTemp[0].Partner_Channel__c = '';
                    leadTemp[0].Category__c='';
                    update leadTemp;

                }


            } catch (Exception e) {
                System.Debug('An exception has occured ' + e.getLineNumber() + ' ' + e.getMessage());
                Database.Rollback(sp);
            }

        }

        return null;
    }
    
    public PageReference saveLead(String Id) {
        List <SelectOption> options = new List <SelectOption> ();
        System.debug('rightOptionsHidden  is ' + rightOptionsHidden);
        String message='';
        //Integer sortOrder = 0;
        String[] parts = rightOptionsHidden.split('&');
        for (Integer i = 0; i < parts.size() / 2; i++) {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }

         List <Partner_Category__c> newRecordsList = new List <Partner_Category__c> ();
 
        Boolean first = true;
        String Primary;
        integer sortOrderL = 0;
        for (SelectOption so: options) {
            sortOrderL++;
            Partner_Category__c newRecord = new Partner_Category__c();
            newRecord.Partner_Lead__c = Id;
            newRecord.Name = so.getLabel();
            newRecord.Sort_Order__c = sortOrderL;

            if (first == true) {
              //  message = so.getLabel();
                Primary = so.getLabel();
                first = false;
            } else {
                message = message + ';';
                message += so.getLabel();
            }


            newRecordsList.add(newRecord);

        }
        System.debug('message ' + message);
        System.debug('newRecordsList.size ' + newRecordsList.size());
        if (newRecordsList.size() >= 0) {
            // get existing records and delete them and insert new record
            List <Partner_Category__c> delRecordsList = new List <Partner_Category__c> ();
            delRecordsList = [select id from Partner_Category__c where Partner_Lead__c = : accountid ];
            List <Lead> leadTemp = [select  Category__c from Lead where id = : accountid ];
            SavePoint sp = Database.setSavePoint();
            try {
               if (delRecordsList.size() > 0) delete delRecordsList;
                if (newRecordsList.size() > 0) {
                   // leadTemp[0].Partner_Channel__c = Primary;
                    leadTemp[0].Category__c=message;
                    update leadTemp;
                    insert newRecordsList;

                } else if (newRecordsList.size() == 0) {
                    // leadTemp[0].Partner_Channel__c = '';
                    leadTemp[0].Category__c='';
                    update leadTemp;

                }


            } catch (Exception e) {
                System.Debug('An exception has occured ' + e.getLineNumber() + ' ' + e.getMessage());
                Database.Rollback(sp);
            }

        }

        return null;
    }
}