Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Customer_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>R00N70000002H6uVEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>R00N70000002FrsQEAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Survey</label>
    <nameField>
        <label>Customer Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestCustomerSurveys_Ctrl.cls
@isTest 
private class TestCustomerSurveys_Ctrl {
    static testMethod void CustomerSurveys_UnitTest() {
    
        Test.startTest(); 
        // DS-CONAM Calc.apexTesting();
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;
        
        Customer_Survey__c cs = new Customer_Survey__c();
        cs.Name = 'test';
        cs.Account__c = acc.Id;
        cs.Opportunity__c = opp.Id;
        insert cs;
        
        PageReference ref = new PageReference('/apex/CustomerSurveysCustom'); 
        Test.setCurrentPage(ref); 
        
        ApexPages.StandardController std  = new ApexPages.StandardController(cs);
        CustomerSurveys_Ctrl survey1Obj1 = new CustomerSurveys_Ctrl(std);
               
        survey1Obj1.save();
        survey1Obj1.cancel();
        
        ApexPages.CurrentPage().getParameters().put('retURL','oppId='+opp.Id); 
        
       
        CustomerSurveys_Ctrl survey1Obj = new CustomerSurveys_Ctrl(std);
        survey1Obj.save();
        survey1Obj.cancel();
         
        ApexPages.CurrentPage().getParameters().put('Id', cs.Id); 
              
        CustomerSurveys_Ctrl surveyObj = new CustomerSurveys_Ctrl(std);
        surveyObj.save();
        surveyObj.cancel();
      
        Test.stopTest();
    }
    
    static testMethod void CustomerSurveys_UnitTest2() {
    
        Test.startTest(); 
        // DS-CONAM Calc.apexTesting();
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;
        
        Customer_Survey__c cs = new Customer_Survey__c();
        cs.Name = 'test';
        cs.Account__c = acc.Id;
        cs.Opportunity__c = opp.Id;
        insert cs;
        
        PageReference ref = new PageReference('/apex/CustomerSurveysCustom'); 
        Test.setCurrentPage(ref); 
        ApexPages.CurrentPage().getParameters().put('Id', cs.Id); 
        delete cs;
        
        ApexPages.StandardController std  = new ApexPages.StandardController(cs);
        CustomerSurveys_Ctrl survey1Obj1 = new CustomerSurveys_Ctrl(std);
      
        Test.stopTest();
    }
    
    
    static testMethod void CustomerSurveys_UnitTest3() {
    
        Test.startTest(); 
        // DS-CONAM Calc.apexTesting();
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;
        
        Customer_Survey__c cs = new Customer_Survey__c();
        cs.Name = 'test';
        cs.Account__c = acc.Id;
        cs.Opportunity__c = opp.Id;
        insert cs;
        
        PageReference ref = new PageReference('/apex/CustomerSurveysCustom'); 
        Test.setCurrentPage(ref); 
        
        ApexPages.StandardController std  = new ApexPages.StandardController(cs);
        CustomerSurveys_Ctrl survey1Obj1 = new CustomerSurveys_Ctrl(std);
               
        survey1Obj1.save();
        survey1Obj1.cancel();
        
        ApexPages.CurrentPage().getParameters().put('retURL','oppId='+opp.Id+'&id='+cs.Id); 
        
       
        CustomerSurveys_Ctrl survey1Obj = new CustomerSurveys_Ctrl(std);
        survey1Obj.save();
        survey1Obj.cancel();
         
       Test.stopTest();
    }
    
    static testMethod void CustomerSurveys_UnitTest4() {
    
        Test.startTest(); 
        // DS-CONAM Calc.apexTesting();
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign cm = new Campaign();
        cm.name = 'Test';
        cm.type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;
        
        Customer_Survey__c cs = new Customer_Survey__c();
        cs.Name = 'test';
        cs.Account__c = acc.Id;
        cs.Opportunity__c = opp.Id;
        insert cs;
        
        PageReference ref = new PageReference('/apex/CustomerSurveysCustom'); 
        Test.setCurrentPage(ref); 
        
        ApexPages.StandardController std  = new ApexPages.StandardController(cs);
        CustomerSurveys_Ctrl survey1Obj1 = new CustomerSurveys_Ctrl(std);
               
        survey1Obj1.save();
        survey1Obj1.cancel();
        
        ApexPages.CurrentPage().getParameters().put('retURL','/'+opp.Id); 
        
       
        CustomerSurveys_Ctrl survey1Obj = new CustomerSurveys_Ctrl(std);
        survey1Obj.save();
        survey1Obj.cancel();
        Test.stopTest();
    }
    
    
}