Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/GetFeedback_Survey__c.object
<CustomObject>
    <description>This is a custom object created to capture the survey responses received through GetFeedback Survey App.</description>
    <fields>
        <fullName>BA_Service_Rating_Comments__c</fullName>
        <description>Received less than excellent service from your business advisor - Reason</description>
        <inlineHelpText>Received less than excellent service from your business advisor - Reason</inlineHelpText>
        <label>BA Service Rating Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GetFeedback Survey</relationshipLabel>
        <relationshipName>GetFeedback_Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Satisfaction_Comments__c</fullName>
        <description>Received less than completely satisfied rating for overall funding experience - Reason</description>
        <inlineHelpText>Received less than completely satisfied rating for overall funding experience - Reason</inlineHelpText>
        <label>Overall Satisfaction Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>GetFeedback Survey</label>
    <nameField>
        <displayFormat>GF-R-{00000000}</displayFormat>
        <label>GF Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GetFeedback Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestFillSurveyChoices.cls
@isTest
public class TestFillSurveyChoices {
   Static testMethod void FillSurveyChoicesTest(){
       Test.startTest();
       
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cm = new Campaign();
        cm.Name = 'Test';
        cm.Type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 50;
        opp.CampaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.AccountId = acc.id;
        opp.email_address__c='test@test.com';
        insert opp;
       
       Id recordTypeIdFunding= Schema.SObjectType.GetFeedback_Survey__c.getRecordTypeInfosByName().get('Funding Survey').getRecordTypeId();
       Id recordTypeIdClient= Schema.SObjectType.GetFeedback_Survey__c.getRecordTypeInfosByName().get('Client Service Survey').getRecordTypeId();
       
       GetFeedback_Survey__c gt=new GetFeedback_Survey__c();
       gt.recordtypeid = recordTypeIdFunding;
       gt.BA_Service_Rating_Comments__c='I didn\'t that the business advisor was knowledgeable enough about the details of my financing / funding.,I didn\'t get called back when promised.,My business advisor wasn\'t available to me when I tried to reach him/her.,My business advisor didn\'t set accurate expectations about the funding process.';     
       gt.Overall_Satisfaction_Comments__c='The application process was harder or more time consuming than I expected.,It took too long to get the approval decision from underwriting.,there were too many conditions prior to actually funding my account.,I experienced problems with customer service.,It took too long to get the decision from underwriting.,I was given the expectation I would be approved, but the situation seemed to change in underwriting.,The underwriting process was overly intrusive and disruptive.';
       gt.Opportunity__c = opp.Id;
       insert gt;
       
       GetFeedback_Survey__c gt1=new GetFeedback_Survey__c();
       gt1.recordtypeid = recordTypeIdClient;
       gt1.BA_Service_Rating_Comments__c='I didn\'t feel that the business advisor was knowledgeable enough about the details of my financing.I didn\'t get called back when promised.My business advisor wasn\'t available to me when I tried to reach him/her.My business advisor didn\'t set accurate expectations about the funding process.';
       gt1.Overall_Satisfaction_Comments__c='The application process was harder or more time consuming than I expected.It took too long to get the approval decision from underwriting.there were too many conditions prior to actually funding my account.I experienced problems with customer service.It took too long to get the decision from underwriting.I was given the expectation I would be approved but the situation seemed to change in underwriting.The underwriting process was overly intrusive and disruptive.';
       gt1.Opportunity__c = opp.Id;
       insert gt1;
       
       Test.stopTest();

   }
}