Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category_Contains_Banks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Category Contains Banks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <label>Legal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_Since__c</fullName>
        <label>Length of time in business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>6 months to 1 year</fullName>
                </value>
                <value>
                    <fullName>1 year to 2 years</fullName>
                </value>
                <value>
                    <fullName>More than 2 years</fullName>
                </value>
                <value>
                    <fullName>Less than 6 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Principal_1_City__c</fullName>
        <label>Principal 1 City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_State__c</fullName>
        <label>Principal 1 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_Street_Address__c</fullName>
        <label>Principal 1 Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_1_Zip__c</fullName>
        <label>Principal 1 Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Of_Business__c</fullName>
        <label>Type Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Cigar Cigarette &amp; Tobacco Dealer-Retail</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
                <value>
                    <fullName>Framing Store</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestSetCAlendersFields.cls
@isTest
private class TestSetCAlendersFields
{
    static testMethod void unitTest()
    {
        Test.startTest();
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        List<Partner_Category__c> pList=new List<Partner_Category__c>();
        Partner_Category__c p1=new Partner_Category__c();
        p1.Partner_Account__c=acc.id;
        p1.Sort_Order__c=1;
        p1.Name='Banks';
        pList.add(p1);
        
        Partner_Category__c p2=new Partner_Category__c();
        p2.Partner_Account__c=acc.id;
        p2.Sort_Order__c=2;
        p2.Name='CUSO';
        pList.add(p2);
        
        Partner_Category__c p3=new Partner_Category__c();
        p3.Partner_Account__c=acc.id;
        p3.Sort_Order__c=3;
        p3.Name='Credit Unions';
        pList.add(p3);
        
        insert pList;
        
        Account accQ=[Select Category_Contains_Banks__c from account where id=: acc.id Limit 1];
        System.assertEquals(accQ.Category_Contains_Banks__c,true);
        Test.stopTest();
    }
    
    
    static testMethod void unitTestUpdate()
    {
        Test.startTest();
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        Lead lTemp = new Lead();
        lTemp.Status = 'Inital Call Needed';
        lTemp.LeadSource = 'A001';
        lTemp.Company = 'Krell Audio/Video';
        lTemp.Legal_Business_Name__c = 'Krell Audio/Video';
        lTemp.Phone = '3132329090';
        lTemp.Type_Of_Business__c = 'Entertainment';
        lTemp.Operating_Since__c = 'More than 2 years';
        lTemp.DateBusinessStarted__c = system.today();
        lTemp.Owned_Business_Since__c = system.today();
        lTemp.FirstName = 'Jake';
        lTemp.LastName = 'Jones';
        lTemp.Principal_1_Street_Address__c = '1000 West Street';
        lTemp.Principal_1_City__c = 'Washington';
        lTemp.Principal_1_State__c = 'DC';
        lTemp.Principal_1_Zip__c = '20012';
        insert lTemp;
        
        List<Partner_Category__c> pList=new List<Partner_Category__c>();
        Partner_Category__c p1=new Partner_Category__c();
        p1.Partner_Lead__c=lTemp.id;
        p1.Sort_Order__c=1;
        p1.Name='Banks';
        pList.add(p1);
        
        Partner_Category__c p2=new Partner_Category__c();
        p2.Partner_Lead__c=lTemp.id;
        p2.Sort_Order__c=2;
        p2.Name='CUSO';
        pList.add(p2);
        
        Partner_Category__c p3=new Partner_Category__c();
        p3.Partner_Lead__c=lTemp.id;
        p3.Sort_Order__c=3;
        p3.Name='Credit Unions';
        pList.add(p3);
        
        insert pList;
        
        pList=new List<Partner_Category__c>();
        p1.Partner_Account__c=acc.id;
        p1.Partner_Lead__c=null;
        
        p2.Partner_Account__c=acc.id;
        p2.Partner_Lead__c=null;
        
        p3.Partner_Account__c=acc.id;
        p3.Partner_Lead__c=null;
        
        pList.add(p1);
        pList.add(p2);
        pList.add(p3);
        
        update pList;
        Test.stopTest();
    }
}