Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Five9VoicemailScreenpopSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Salesforce_User_Email__c</fullName>
        <label>Salesforce User Email</label>
        <type>Email</type>
    </fields>
    <label>Five9 Voicemail Screenpop Settings</label>
</CustomObject>

Rapid Prd/src/classes/Five9VoicemailScreenpopTest.cls
@isTest 
public class Five9VoicemailScreenpopTest {
    static testMethod void createLeadPositiveCase() {
        test.startTest();
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/F9VoiceMail/';  
        req.addParameter('ani', '1925948151');
        req.addParameter('dnis', '+1925948151');
        req.addParameter('leadSource', 'Voicemail');
        req.addParameter('company', 'Five9 Generated Lead');
        req.addParameter('lastName', 'Five9 Generated Lead');
        req.addParameter('status', 'Initial Call needed');
        req.addParameter('ownerId', '123456789');
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        
        string result =Five9VoicemailScreenpop.leadCreater();
        test.stopTest();
        system.assertEquals('SUCCESS', result);
        
    }
    static testMethod void createLeadAtleastOnePositiveCase() {
        test.startTest();
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/F9VoiceMail/';  
        req.addParameter('ani', '1925948151');
        req.addParameter('dnis', '+1925948150');
        req.addParameter('leadSource', 'Voicemail');
        req.addParameter('company', 'Five9 Generated Lead');
        req.addParameter('lastName', 'Five9 Generated Lead');
        req.addParameter('status', 'Initial Call needed');
        req.addParameter('ownerId', '123456789');
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        string result =Five9VoicemailScreenpop.leadCreater();
        test.stopTest();
        system.assertEquals('SUCCESS', result);        
    }    
    static testMethod void createLeadEmailCase() {
        contact c = new contact();
        c.LastName='test data';
        c.MobilePhone='+1925948150';
        Account a = new Account();
        a.Name='test';
        a.BusinessType__c='Large Business';
        insert a;
        //        Account a = [SELECT ID FROM ACCOUNT LIMIT 1];        
        c.AccountId=a.id;
        insert c;
        Five9VoicemailScreenpopSettings__c item = new Five9VoicemailScreenpopSettings__c();
        item.Salesforce_User_Email__c='test@mail.com';
        item.Name='abc';
        insert item;
        test.startTest();
        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/F9VoiceMail/';  
        req.addParameter('ani', '1925948151');
        req.addParameter('dnis', '1925948150');
        req.addParameter('leadSource', 'Voicemail');
        req.addParameter('company', 'Five9 Generated Lead');
        //req.addParameter('lastName', 'Five9 Generated Lead');
        req.addParameter('status', 'Initial Call needed');
        req.addParameter('ownerId', '123456789');
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        string result =Five9VoicemailScreenpop.leadCreater();
        test.stopTest();
        system.assertNotEquals('SUCCESS', result);        
    }
    
    static testMethod void createLeadOneContactCase() {
        contact c = new contact();
        c.LastName='test data';
        c.Phone='1925948150';
        Account a = new Account();
        a.Name='test';
        a.BusinessType__c='Large Business';
        insert a;       
        c.AccountId=a.id;
        insert c;
        Five9VoicemailScreenpopSettings__c item = new Five9VoicemailScreenpopSettings__c();
        item.Salesforce_User_Email__c='test@mail.com';
        item.Name='abc';
        insert item;
        test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/F9VoiceMail/';  
        req.addParameter('ani', '1925948150');
        req.addParameter('dnis', '1925948150');
        req.addParameter('leadSource', 'Voicemail');
        req.addParameter('company', 'Five9 Generated Lead');
        req.addParameter('lastName', 'Five9 Generated Lead');
        req.addParameter('status', 'Initial Call needed');
        req.addParameter('ownerId', '123456789');
        
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        
        string result =Five9VoicemailScreenpop.leadCreater();
        
        test.stopTest();
        system.assertEquals('SUCCESS', result);        
    }
}