Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessStructure__c</fullName>
        <label>Business Structure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C-Corporation</fullName>
                </value>
                <value>
                    <fullName>General Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership</fullName>
                </value>
                <value>
                    <fullName>Proprietorship</fullName>
                </value>
                <value>
                    <fullName>S-Corporation</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Partnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DateBusinessStarted__c</fullName>
        <label>Business Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_or_State_Tax_Liens__c</fullName>
        <label>Federal or State Tax Liens?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flag_Account_for_Renewal__c</fullName>
        <formula>if( Most_Recent_Funded_Renewal_Date__c &lt; Most_Recent_Opp_Not_Processed__c ,0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flag Account for Renewal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Landlord_Agent_Name__c</fullName>
        <label>Landlord/Agent Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Agent_Phone__c</fullName>
        <label>Landlord/Agent Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_For_Statements_etc__c</fullName>
        <description>Added per Earl and Karl.  This will be used for mailing purposed only and could be different for the actual retail location.</description>
        <label>Mailing Address (For Statements etc.)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Present_Management_Since__c</fullName>
        <label>Present Management Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricing_on_New_Deals__c</fullName>
        <label>Pricing on New Deals</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_on_Renewals__c</fullName>
        <label>Pricing on Renewals</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Remaining_On_Lease__c</fullName>
        <label>Time Remaining On Site Lease/Mortgage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <formula>Account.Number_of_Locations__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Terminals_at_Location__c</fullName>
        <formula>Account.Number_of_Terminals_at_Location__c</formula>
        <label>Number of Terminals at Location?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owned_Business_Since__c</fullName>
        <formula>Account.Owned_Business_Since__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updated From Account Owned Business Since Field.</inlineHelpText>
        <label>Owned Business Since</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/AccountMainBusiness.cls
global class AccountMainBusiness
{
    global boolean isVisible {get;set;}
    global String btnText{get;set;}
    global Account objAccount {get;set;}
    global Opportunity opp {get;set;}


    global AccountMainBusiness()
    {
        try
        {
            btnText = 'Edit';
            isVisible = false;
            String oppId = ApexPages.currentPage().getParameters().get('id');
            if (oppId.trim() != '' && oppId != null)
            {
                System.debug('I am here');
                opp = [select 
                            accountId 
                        from
                            Opportunity 
                        where 
                            id = : oppId];
                if (opp.accountId != null)
                {
                    objAccount = [Select 
                                            Legal_Name__c, Phone, Name, Fax, BillingState, Billingcity, Billingstreet, Billingcountry,
                                            Email_Address__c, Mailing_Address_For_Statements_etc__c, BillingPostalCode, Website, DateBusinessStarted__c, 
                                            FederalTaxID__c, BusinessType__c, Owned_Business_Since__c, Landlord_Agent_Name__c, Present_Management_Since__c,
                                            Landlord_Agent_Phone__c, Number_of_Locations__c, Time_Remaining_On_Lease__c, Number_of_Terminals_at_Location__c,
                                            Federal_or_State_Tax_Liens__c, Flag_Account_for_Renewal__c, Pricing_on_New_Deals__c, Sic, Pricing_on_Renewals__c,
                                            BusinessStructure__c 
                                    From 
                                            Account 
                                    where 
                                            id = : opp.accountId];
                }
                else 
                {
                    /* commentted out DS-Conam 08-04-2015
                    ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Opportunity does not have an Account ');
                    ApexPages.addMessage(msg);
                    */
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Opportunity does not have an Account '));
                    
                }

            }
            else
            {
                System.debug('I should be here');
                /* commentted out DS-Conam 08-04-2015
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'Please Provide Opportunity Id');
                ApexPages.addMessage(msg);
                */
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please Provide Opportunity Id'));
            }
        }
        catch (Exception ex) 
        {
            /* commentted out DS-Conam 08-04-2015
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred' + ex.getMessage());
            ApexPages.addMessage(msg);
            */
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred' + ex.getMessage()));
        }
    }
    
    global PageReference onEdit()
    {

        try {
            if (btnText == 'Edit') 
            {
                isVisible = true;
                btnText = 'Save';
            }
            else
            {
                update objAccount;
                btnText = 'Edit';
                isVisible = false;
            }

        } 
        catch (Exception ex) {
            /* commentted out DS-Conam 08-04-2015
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred');
            ApexPages.addMessage(msg);
            */
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'An exception occurred'));
        }
        return null;
    }
    
    global PageReference onCancel()
    {
        btnText = 'Edit';
        isVisible = false;
        return null;
    }
}