Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactID__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContactID__c</fullName>
        <formula>Contact__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <formula>Account.Legal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Update in Account Legal Name</inlineHelpText>
        <label>Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Entity__c</fullName>
        <label>Type of Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Unable To Confirm by QC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ContractValidation_Ctrl.cls
public with sharing class ContractValidation_Ctrl {

	public Opportunity oppRecord {get;set;}
	/*
	commentted out DS-Conam 08-03-2015 as not being used
	public List <OpportunityContactRole> oppRoleList {get;set;}
	*/
	public ContractValidation_Ctrl() 
	{
		String oppId = ApexPages.currentPage().getParameters().get('Id');

		if (oppId != null && oppId.trim() != '') 
		{
			List <Opportunity> oppList = [SELECT 
													Id, Account.BillingCountry, Account.BillingState, Account.Legal_Name__c, 
													Type_of_Entity__c, Amount, Percent_Payback__c, Product__c, Pay_Back_Amount__c, ContactID__c, 
													AccountId
											FROM 
													Opportunity 
											WHERE 
													Id = : oppId LIMIT 1];
													
													
			/*
            oppRoleList =[SELECT Id, Role, OpportunityId, IsPrimary, ContactId FROM OpportunityContactRole WHERE 
                                                            OpportunityId =:oppId and Contact.IsDeleted=false];
  			*/  
			if (!oppList.isEmpty())
			{
				oppRecord = oppList.get(0);
			}
		} 
		else
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
		}
	}

	public PageReference doSave() 
	{
		try
		{
			upsert oppRecord;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'Contract Validation Information Saved Successfully!'));
		} 
		catch (Exception e)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		return null;
	}
}