Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Duplicate_Contact_Blocker_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Match_Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Account Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_First_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match First Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Last_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Last Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Match Phone</label>
        <type>Checkbox</type>
    </fields>
    <label>Duplicate Contact Blocker Setup</label>
    <nameField>
        <label>Duplicate Contact Blocker Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duplicate Contact Blocker Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestDuplicateContactBlockerController.cls
@isTest

 public class TestDuplicateContactBlockerController  
 {
       public static testMethod void testContactDuplicateTrigger()
       {
            Test.startTest();
            // DS-CONAM CALC.apexTesting();
            PageReference testPage = Page.DuplicateContactBlockerSetup;
            Test.setCurrentPage(testPage);
                      
            Duplicate_Contact_Blocker_Setup__c dcbs =  new Duplicate_Contact_Blocker_Setup__c();                         
                                                                    
            dcbs.Name = 'TestDCBS1';
            dcbs.Match_Account_Name__c= true;
            dcbs.Match_Email__c=true;
            dcbs.Match_Phone__c= false;
            
            insert dcbs;
            
            if (dcbs.id!=null) 
            {
                DuplicateContactBlockerController theController = new DuplicateContactBlockerController();
                delete dcbs;
                theController.ReadyPage();                
            }

            Account acct = new Account();
            acct.Name = 'Test Account1';
            acct.BusinessType__c='testBusiness';
            insert acct;
        
            Contact existingContact = new Contact();
            existingContact.FirstName = 'John';
            existingContact.LastName = 'Smith123';
            existingContact.Email = 'js123@gmail.com';
            existingContact.AccountId = acct.id;
            existingContact.Phone = '1231231234';
            insert existingContact;
        
            Contact duplicateContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com');
            duplicateContact.AccountId = acct.id;
        
            Duplicate_Contact_Blocker_Setup__c dcbs2 = new Duplicate_Contact_Blocker_Setup__c();
            
            dcbs2.Match_Phone__c = true;
            dcbs2.Match_Last_Name__c = true;
            dcbs2.Match_First_Name__c = true;
            dcbs2.Match_Email__c = true;
            dcbs2.Match_Account_Name__c = true;
            insert dcbs2;
            
            Contact dContact = new Contact(FirstName = 'John', LastName = 'Smith123', Email = 'js123@gmail.com', Phone = '1231231234');
            duplicateContact.AccountId = acct.id;

        
            try
            {
               insert duplicateContact;
               insert dContact;
            }
            
            catch (Exception e) 
            {
                System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
            } 
            
                delete dcbs2;
                
            try 
            {
                insert dContact;
            } 
            
            catch (Exception e) 
            {
                System.debug('An exception has occured -'+e.getMessage()+' - '+ e.getLineNumber());
            }
            
            Test.stopTest();
      }
 }