Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opp_RD_Permission_Set__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in New Opp Tab</description>
    <fields>
        <fullName>Pre_Qual__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Qual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processing_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processing/CS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tab_Order__c</fullName>
        <label>Tab Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Vf_Page_Name__c</fullName>
        <label>Vf Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opp RD Permission Set</label>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMainClass3_Ctrl.cls
@isTest
private class TestMainClass3_Ctrl {

    @testSetup static void setup()
    {
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;

        Campaign cm = new Campaign();
        cm.name = 'Test';
        cm.type = 'Internet';
        insert cm;

        Opportunity opp = new Opportunity();
        opp.name = 'testOpportunity';
        opp.leadSource = 'web';
        opp.stageName = 'Prospecting';
        opp.closeDate = System.today() + 20;
        opp.campaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.closeDate = System.today() + 50;
        opp.accountId = acc.id;
        insert opp;

    
    }

    static testMethod void mainClass3_UnitTest() {
        Test.startTest();
        // DS-CONAM Calc.apexTesting();
        /* DS-CONAM
        Account acc = TestUtils.createAccount();
        Campaign cm = TestUtils.createCampaign();
        Opportunity opp = TestUtils.createOpportunity(acc, cm);
        
       */
        
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;


        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
        /*Profile p = [SELECT 
                            Id 
                    FROM 
                            Profile 
                    WHERE 
                            Name = 'System Administrator'];
        */
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u) {
            List < PermissionSet > pSet = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - Pre-Qual'];
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
           /* 
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - Processing'];
            PermissionSetAssignment psa1 = new PermissionSetAssignment();
            psa1.PermissionSetId = pset1[0].id;
            psa1.AssigneeId = u.ID;
            insert psa1;
            
            MainClass3 mc5 = new MainClass3();
            MainClass3 mc6 = new MainClass3(std);
            
            List < PermissionSet > pSet2 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'c'];
            PermissionSetAssignment psa2 = new PermissionSetAssignment();
            psa2.PermissionSetId = pset2[0].id;
            psa2.AssigneeId = u.ID;
            insert psa2;
            MainClass3 mc7 = new MainClass3();
            MainClass3 mc8 = new MainClass3(std);
            List < PermissionSet > pSet3 = [Select
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - UW'];
                                                    
            PermissionSetAssignment psa3 = new PermissionSetAssignment();
            psa3.PermissionSetId = pset3[0].id;
            psa3.AssigneeId = u.ID;
            insert psa3;
            
            MainClass3 mc9 = new MainClass3();
            MainClass3 mc10 = new MainClass3(std);
           */ 
           
            
        }
        Test.stopTest();
    }
    
    
    static testMethod void mainClass3_UnitTest2() {
        Test.startTest();
        
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - Processing'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
    
    static testMethod void mainClass3_UnitTest3() {
        Test.startTest();
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - QC'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
    static testMethod void mainClass3_UnitTest4() {
        Test.startTest();
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - UW'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
    
    /*static testMethod void mainClass3_UnitTest5() {
        Test.startTest();
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Promac - UW'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
    */
    static testMethod void mainClass3_UnitTest6() {
        Test.startTest();
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Operations - QC ExUser'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
    
    static testMethod void mainClass3_UnitTest7() {
        Test.startTest();
        Opp_RD_Permission_Set__c opSet=new Opp_RD_Permission_Set__c();
        opSet.Name='Test';
        opSet.Pre_Qual__c=true;
        opSet.Processing_CS__c=true;
        opSet.QC__c=true;
        opSet.Tab_Order__c=1;
        opSet.Vf_Page_Name__c='Test';
        insert opSet;
        
        Opp_RD_Permission_Set__c opSet2=new Opp_RD_Permission_Set__c();
        opSet2.Name='Test2';
        opSet2.Pre_Qual__c=true;
        opSet2.Processing_CS__c=true;
        opSet2.QC__c=true;
        opSet2.Tab_Order__c=2;
        opSet2.Vf_Page_Name__c='Test2';
        insert opSet2;
        Opportunity opp=[select
                                id
                        from
                                Opportunity
                        where 
                                name='testOpportunity' Limit 1];
        

        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        MainClass3 mc = new MainClass3();
        ApexPages.StandardController std = new ApexPages.StandardController(opp);
        MainClass3 mc3 = new MainClass3(std);
      
        User u = [Select 
                        id, name 
                from 
                        user 
                Where 
                        IsActive = true AND Profile.NAME = 'System Administrator' LIMIT 1];

        System.runAs(u)
        {
            List < PermissionSet > pSet1 = [Select 
                                                    Id, Label 
                                            FROM 
                                                    PermissionSet 
                                            Where 
                                                    Label = : 'Additional Opportunity Field Access'];
                                                    
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.PermissionSetId = pset1[0].id;
            psa.AssigneeId = u.ID;
            insert psa;
            
            MainClass3 mc1 = new MainClass3();
            MainClass3 mc4 = new MainClass3(std);
            
        }
        Test.stopTest();
    }
}