Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Funded_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Funded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>GreenTree</fullName>
        <active>true</active>
        <businessProcess>GreenTree</businessProcess>
        <label>GreenTree</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestOppInitialComAmtUpdateTrigger.cls
@isTest

private class TestOppInitialComAmtUpdateTrigger{ 

    public static testMethod voId oppInitialComAmtUpdateTest1(){
        
        Test.startTest();
        
        List<RecordType> gId=[SELECT
                                    Id
                                FROM
                                    RecordType
                                WHERE
                                    sObjectType='Opportunity'
                                AND
                                    DeveloperName='GreenTree' LIMIT 1];
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
                                   
        Opportunity gOpp1 = new Opportunity();
        gOpp1.name='oppname1';
        gOpp1.accountId=ac.Id;
        gOpp1.RecordTypeId=gId.get(0).Id;
        gOpp1.ForecastCategoryName='Commit';
        gOpp1.LeadSource='A001';
        gOpp1.CampaignId=cp.Id;
        gOpp1.CloseDate=system.today();
        gOpp1.Current_Processor__c='1st federal financial';
        gOpp1.StageName='Initial Call Needed';
        gOpp1.Renewal_Funded_Amount__c = 1000;
        insert gOpp1;
        
        Green_Tree_Oppy_Extension__c gt1=new Green_Tree_Oppy_Extension__c();
        gt1.opportunity__c=gOpp1.Id;
        gt1.Amount__c= 10000;
        gt1.Amount_Sold__c= 1000;
        
        insert gt1;
               
        
        Test.stopTest();
    }
    public static testMethod voId oppInitialComAmtUpdateTest2(){
        
        Test.startTest();
        
        List<RecordType> gId=[SELECT
                                    Id
                                FROM
                                    RecordType
                                WHERE
                                    sObjectType='Opportunity'
                                AND
                                    DeveloperName='GreenTree' LIMIT 1];
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
                                   
        Opportunity gOpp1 = new Opportunity();
        gOpp1.name='oppname1';
        gOpp1.accountId=ac.Id;
        gOpp1.RecordTypeId=gId.get(0).Id;
        gOpp1.ForecastCategoryName='Commit';
        gOpp1.LeadSource='A001';
        gOpp1.CampaignId=cp.Id;
        gOpp1.CloseDate=system.today();
        gOpp1.Current_Processor__c='1st federal financial';
        gOpp1.StageName='Initial Call Needed';
        gOpp1.Renewal_Funded_Amount__c = 1000;
        insert gOpp1;
        
        Green_Tree_Oppy_Extension__c gt1=new Green_Tree_Oppy_Extension__c();
        gt1.opportunity__c=gOpp1.Id;
        gt1.Amount__c= 10000;
        gt1.Amount_Sold__c= 1000;
        
        insert gt1;
        
                
        Test.stopTest();
    }
    public static testMethod voId oppInitialComAmtUpdateTest3(){
        
        Test.startTest();
        
        List<RecordType> gId=[SELECT
                                    Id
                                FROM
                                    RecordType
                                WHERE
                                    sObjectType='Opportunity'
                                AND
                                    DeveloperName='GreenTree' LIMIT 1];
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
                                   
        Opportunity gOpp1 = new Opportunity();
        gOpp1.name='oppname1';
        gOpp1.accountId=ac.Id;
        gOpp1.RecordTypeId=gId.get(0).Id;
        gOpp1.ForecastCategoryName='Commit';
        gOpp1.LeadSource='A001';
        gOpp1.CampaignId=cp.Id;
        gOpp1.CloseDate=system.today();
        gOpp1.Current_Processor__c='1st federal financial';
        gOpp1.StageName='Initial Call Needed';

        gOpp1.Renewal_Funded_Amount__c = 1000;
        insert gOpp1;
        
        Green_Tree_Oppy_Extension__c gt1=new Green_Tree_Oppy_Extension__c();
        gt1.opportunity__c=gOpp1.Id;
        gt1.Amount__c= 10000;
        gt1.Amount_Sold__c= 1000;
        
        insert gt1;
        
        gOpp1.Renewal_Funded_Amount__c = 200;
        update gOpp1;
        
        
        
        Test.stopTest();
    }
    public static testMethod voId oppInitialComAmtUpdateTest4(){
        
        Test.startTest();
        
        List<RecordType> gId=[SELECT
                                    Id
                                FROM
                                    RecordType
                                WHERE
                                    sObjectType='Opportunity'
                                AND
                                    DeveloperName='GreenTree' LIMIT 1];
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
                                   
        Opportunity gOpp1 = new Opportunity();
        gOpp1.name='oppname1';
        gOpp1.accountId=ac.Id;
        gOpp1.RecordTypeId=gId.get(0).Id;
        gOpp1.ForecastCategoryName='Commit';
        gOpp1.LeadSource='A001';
        gOpp1.CampaignId=cp.Id;
        gOpp1.CloseDate=system.today();
        gOpp1.Current_Processor__c='1st federal financial';
        gOpp1.StageName='Initial Call Needed';
        gOpp1.Renewal_Funded_Amount__c = 1000;
        insert gOpp1;
        
        Green_Tree_Oppy_Extension__c gt1=new Green_Tree_Oppy_Extension__c();
        gt1.opportunity__c=gOpp1.Id;
        gt1.Amount__c= 10000;
        gt1.Amount_Sold__c= 1000;
        
        insert gt1;
        
        update gOpp1;
        
        Test.stopTest();
    }
}