Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Remaining_On_Lease__c</fullName>
        <label>Time Remaining On Site Lease/Mortgage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Additional_Locations__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Locations</relationshipLabel>
        <relationshipName>Additional_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <label>DBA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Phone__c</fullName>
        <label>Landlord Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <label>Landlord</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Remaining_on_Lease__c</fullName>
        <label>Time Remaining on Lease</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-6 months</fullName>
                </value>
                <value>
                    <fullName>7-11 months</fullName>
                </value>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>2 Years</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>4 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Additional Location</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Additional Locations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DBA_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DBA Name:</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <formula>Account.Fax</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Fax</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestExtjs_Applicant_Credit.cls
@isTest 

private class TestExtjs_Applicant_Credit 
{
    static testMethod void Extjs_Applicant_Credit_UnitTest() 
    {
        // DS-CONAM CALC.apexTesting();
        Test.startTest();
        Account testAccount = new Account();
        testAccount.name = 'Test Account1';
        testAccount.BusinessType__c = 'testBusiness';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Contact c = new Contact();
        c.AccountId = testAccount.Id;
        c.LastName = 'test';
        insert c;
        
        Campaign  cmObj = new Campaign();
        cmObj.Name = 'Test';
        cmObj.Type='Internet';
        insert cmObj;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 20;
        opp.CampaignId = cmObj.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.CloseDate = System.today() + 50;
        opp.AccountId = testAccount.id;
        insert opp;
        
        OpportunityContactRole  oppRole = new OpportunityContactRole();
        oppRole.ContactId = c.Id;
        oppRole.OpportunityId  = opp.Id;
        oppRole.Role = 'Principal 2'; 
        insert oppRole;      
        
        Extjs_Applicant_Credit.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Applicant_Credit.QueryObj queryObj = new Extjs_Applicant_Credit.QueryObj( );
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 0;
        queryObj.recordCount = 10;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> paramMap = new Map<String, String>{'direction' => 'ASC', 'property' => 'DBA_Name__c'};
        queryObj.sortParams.add(paramMap );
        Extjs_Applicant_Credit.query(queryObj);
        
        Extjs_Applicant_Credit.CRUDData crudObj = new  Extjs_Applicant_Credit.CRUDData();
        crudObj.sobjname = 'Additional_Locations__c';
        crudObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj.oppId = testAccount.Id;
        crudObj.parentFieldName = 'Account__c';
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc );
        Map<String, String> fieldMap = new Map<String, String>{'Id' => aloc.Id, 'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c,'State__c' => aloc.State__c, 'Time_Remaining_on_Lease__c' => aloc.Time_Remaining_on_Lease__c};
        crudObj.records = new List<Map<String, String>>
        {
            fieldMap
        };
        
        Extjs_Applicant_Credit.CRUDData crudObj1 = new  Extjs_Applicant_Credit.CRUDData();
        crudObj1.sobjname = 'Additional_Locations__c';
        crudObj1.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj1.oppId = testAccount.Id;
        crudObj1.parentFieldName = 'Account__c';
        List<SObject> sobjList1 = new List<SObject>();
        sobjList.add(oppRole );
        Map<String, String> fieldMap1 = new Map<String, String>{'Id' => oppRole.Id};
        crudObj1.records = new List<Map<String, String>>
        {
            fieldMap
        };
        
        Extjs_Applicant_Credit.refreshObjects(crudObj, sobjList);
        Extjs_Applicant_Credit.create(crudObj);
        Extjs_Applicant_Credit.updat(crudObj);
        Extjs_Applicant_Credit.CRUDResponse crdrespose = Extjs_Applicant_Credit.delet(crudObj);
        
        Extjs_Applicant_Credit.refreshObjects(crudObj1, sobjList1);
        Extjs_Applicant_Credit.create(crudObj1);
        Extjs_Applicant_Credit.updat(crudObj1);
        Extjs_Applicant_Credit.CRUDResponse crdrespose1 = Extjs_Applicant_Credit.delet(crudObj1);
        
        Test.stopTest();
    }   
    
    static testMethod void Extjs_Applicant_Credit_UnitTest2() 
    {
        Test.startTest();
        // DS-CONAM CALC.apexTesting();        
        Account testAccount = new Account();
        testAccount.name = 'Test Account2';
        testAccount.BusinessType__c = 'testBusiness2';
        insert testAccount;
        
        Additional_Locations__c  aloc = new Additional_Locations__c();
        aloc.DBA_Name__c = 'test2';
        aloc.Account__c = testAccount.Id;
        insert aloc;
        
        Contact con = new Contact();
        con.AccountId = testAccount.Id;
        con.LastName = 'test2';
        insert con;
        
        Campaign  cmObj = new Campaign();
        cmObj.Name = 'Test2';
        cmObj.Type='Internet2';
        insert cmObj;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity2';
        opp.LeadSource = 'web2';
        opp.StageName = 'Prospecting2';
        opp.CloseDate = System.today() + 50;
        opp.CampaignId = cmObj.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL2';
        opp.AccountId = testAccount.id;
        insert opp;
        
        OpportunityContactRole  oppRole = new OpportunityContactRole();
        oppRole.ContactId = con.Id;
        oppRole.OpportunityId  = opp.Id;
        oppRole.Role = 'Principal 2'; 
        insert oppRole;      
        
        Extjs_Applicant_Credit.describeFields('Additional_Locations__c', new List<String>{'DBA_Name__c','Street__c','City__c','State__c','Postal_Code__c','Phone__c','Fax__c','Landlord__c','Landlord_Phone__c','Time_Remaining_on_Lease__c'});
        Extjs_Applicant_Credit.QueryObj queryObj = new Extjs_Applicant_Credit.QueryObj( );
        queryObj.sobjname = 'Additional_Locations__c';
        queryObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        queryObj.parentFieldName = 'Account__c';
        queryObj.oppId = testAccount.Id;
        queryObj.start = 10;
        queryObj.recordCount = 100;
        queryObj.sortParams = new List<Map<String, String>>();
        Map<String, String> paramMap = new Map<String, String>{'direction' => 'DES', 'property' => 'DBA_Name__c'};
        queryObj.sortParams.add(paramMap );
        Extjs_Applicant_Credit.query(queryObj);
        
        Extjs_Applicant_Credit.CRUDData crudObj = new  Extjs_Applicant_Credit.CRUDData();
        crudObj.sobjname = 'Additional_Locations__c';
        crudObj.fields = 'DBA_Name__c,Street__c,City__c,State__c,Postal_Code__c,Phone__c,Fax__c,Landlord__c,Landlord_Phone__c,Time_Remaining_on_Lease__c';
        crudObj.oppId = testAccount.Id;
        crudObj.parentFieldName = 'Account__c';
        List<SObject> sobjList = new List<SObject>();
        sobjList.add(aloc);
        Map<String, String> fieldMap = new Map<String, String>{'Id' => aloc.Id, 'Street__c' => aloc.Street__c, 'Phone__c' => aloc.Phone__c,'State__c' => aloc.State__c, 'Time_Remaining_on_Lease__c' => aloc.Time_Remaining_on_Lease__c};
        crudObj.records = new List<Map<String, String>>
        {
            // fieldMap
        };
        
        Extjs_Applicant_Credit.refreshObjects(crudObj, sobjList);
        Extjs_Applicant_Credit.create(crudObj);
        Extjs_Applicant_Credit.updat(crudObj);
        Extjs_Applicant_Credit.CRUDResponse crdrespose = Extjs_Applicant_Credit.delet(crudObj);
        
        test.stopTest();
    }  
}