Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This partner account is associated with this campaign.</description>
        <inlineHelpText>This partner account is associated with this campaign.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DBA__c</fullName>
        <inlineHelpText>&quot;Doing Business As&quot; Name</inlineHelpText>
        <label>DBA (if different from Account Name)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <label>Legal Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Purge_characters_in_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This list will contain all the characters or the strings that are to be eliminated from the account name and lead company name</description>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Replace_With__c</fullName>
        <label>Replace With</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Purge characters in Name</label>
</CustomObject>

Rapid Prd/src/classes/TestPurgeLeadName.cls
@isTest

private class TestPurgeLeadName 
{
    static TestMethod void unitTest()
    {
        Test.startTest();
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        acc.DBA__c='AB & BA';
        acc.Legal_Name__c='AB & BA';
        acc.Campaign__c=camp.id;
        insert acc;
        
        Purge_characters_in_Name__c p1=new Purge_characters_in_Name__c();
        p1.name='1';
        p1.Character__c='&';
        p1.Replace_With__c='space';
        insert p1;
        
        Lead lTemp = new Lead(
                                FirstName = 'Test',
                                LastName  = 'Test & offerson',
                                Company   = 'Test & Industries LLC',
                                Email     = 'test@test.com',
                                Phone     = '18005551111',
                                Status = 'Test',
                                Legal_Business_Name__c='AB & BA'
                                );
              
        insert lTemp;
        
        lTemp.Company   ='Test Industries';
        update lTemp;
        
        Test.stopTest();
    }
    
    static TestMethod void unitTest11()
    {
        Test.startTest();
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        acc.DBA__c='AB & BA';
        acc.Legal_Name__c='AB & BA';
        acc.Campaign__c=camp.id;
        insert acc;
        
        Purge_characters_in_Name__c p1=new Purge_characters_in_Name__c();
        p1.name='1';
        p1.Character__c='inc.';
        p1.Replace_With__c='incorporation';
        insert p1;
        
        Lead lTemp = new Lead(
                                FirstName = 'Test',
                                LastName  = 'Test inc. offerson',
                                Company   = 'Test inc. Industries LLC',
                                Email     = 'test@test.com',
                                Phone     = '18005551111',
                                Status = 'Test',
                                Legal_Business_Name__c='AB inc. BA'
                                );
              
        insert lTemp;
        
        lTemp.Company   ='Test Industries';
        update lTemp;
        
        Test.stopTest();
    }
    
    static TestMethod void unitTest2()
    {
        Test.startTest();
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        acc.DBA__c='AB & BA';
        acc.Legal_Name__c='AB & BA';
        acc.Campaign__c=camp.id;
        insert acc;
        
        Purge_characters_in_Name__c p1=new Purge_characters_in_Name__c();
        p1.name='1';
        p1.Character__c='&';
        p1.Replace_With__c='space';
        insert p1;
        
        Lead lTemp = new Lead(
                                FirstName = 'Test',
                                LastName  = 'Test offerson &',
                                Company   = 'Test Industries LLC &',
                                Email     = 'test@test.com',
                                Phone     = '18005551111',
                                Status = 'Test',
                                Legal_Business_Name__c='AB & BA &'
                                );
              
        insert lTemp;
        
        lTemp.Company   ='Test Industries';
        update lTemp;
        
        Test.stopTest();
    }
    
    static TestMethod void unitTest21()
    {
        Test.startTest();
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Internet';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        acc.DBA__c='AB & BA';
        acc.Legal_Name__c='AB & BA';
        acc.Campaign__c=camp.id;
        insert acc;
        
        Purge_characters_in_Name__c p1=new Purge_characters_in_Name__c();
        p1.name='1';
        p1.Character__c='inc.';
        p1.Replace_With__c='Incorporation';
        insert p1;
        
        Lead lTemp = new Lead(
                                FirstName = 'Test',
                                LastName  = 'Test offerson inc.',
                                Company   = 'Test Industries LLC inc.',
                                Email     = 'test@test.com',
                                Phone     = '18005551111',
                                Status = 'Test',
                                Legal_Business_Name__c='AB & BA inc.'
                                );
              
        insert lTemp;
        
        lTemp.Company   ='Test Industries';
        update lTemp;
        
        Test.stopTest();
    }

}