Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestGetDocumentList.cls
@isTest
    public class TestGetDocumentList
    {
        private static testMethod void testDoGet() 
        {
             Test.startTest();
            // DS-CONAM CALC.ApexTesting();            
            Application app = new Application();
            
            // Using unique identifier of source system for Acct and opportunity Name
            //Get List Of required fields - contact     
            app.FirstName = 'James';
            app.LastName = 'Jones';
            app.HomeCity = 'Washington';
            
            //Get List Of required fields - account
            app.BusinessCity = 'Washington DC';
            app.FederalTaxId = '111155555';
            
            //Get List Of required fields - opportunity
            app.AvgMonthSales = 50000;
            app.MajorCreditCardsProc = 'Visa';
            app.AvgMonthTrans = 45000;
            app.CCSalesLastMonth = 100000;
            app.CCSalesLast1Month = 45000;
            app.CCSalesLast2Month = 55000;
            app.CCSalesLast3Month = 65000;
            app.NumOfTransLastMonth = 300;
            app.NumOfTrans1Month = 250;
            app.NumOfTrans2Month = 350;
            app.NumOfTrans3Month = 450;
            app.SourceSystem = 'Biz2Credit';
            app.ExternalID = 'ExtID10001';
            app.MerchantID = 'Merchant 2000';
            
            Opportunity opp = Biz2CreditUtils.createOpportunity(app);
            
            
            OpportunityOffer oppOff = new OpportunityOffer();
            
            // Correctly Entered data should give successful resp
            oppOff.OfferID = '100333r0';
            oppOff.Amount = 1000;
            oppOff.DailyCollection = 1000;
            oppOff.Duration = 5;
            oppOff.ProductName = 'Product 1';
            oppOff.DailyPayment = 1000;
            oppOff.NumOfPayments = 6;
            oppOff.ExternalID = 'ExtID10001';
            oppOff.Source = 'Biz2Credit';
            
            Oppr_Document__c od = new Oppr_Document__c();
            od.document_name__c = 'Doc Test 1';
            od.Opportunity__c = opp.Id;
            od.Status__c = 'Requested';
            insert od;
        
            RestRequest req = new RestRequest();  
            RestResponse res = new RestResponse();
            req.addHeader('Content-Type','application/x-www-form-urlencoded');  
            
            
            req.addParameter('id', opp.External_ID__c);
            req.addParameter('SourceSystem', 'Biz2Credit');
            
            
            String instanceUrl = Biz2CreditUtils.getInstanceURL();
            req.requestURI = 'https://'+instanceUrl+'/services/apexrest/GetDocumentList';  
            req.httpMethod = 'GET';
            
            RestContext.request = req;
            RestContext.response = res;
            
            // request 1 No docList
            GetDocumentList.doGet();
            
            
            req.addParameter('id', opp.External_ID__c);
            req.addParameter('SourceSystem', 'B2C');
            
            
            instanceUrl = Biz2CreditUtils.getInstanceURL();
            req.requestURI = 'https://'+instanceUrl+'/services/apexrest/GetDocumentList';  
            req.httpMethod = 'GET';
            
            RestContext.request = req;
            RestContext.response = res;
            
            // request 1 No docList
            GetDocumentList.doGet();
            
             req.addParameter('id', opp.External_ID__c);
            req.addParameter('SourceSystem', 'BC');
            
            
            instanceUrl = Biz2CreditUtils.getInstanceURL();
            req.requestURI = 'https://'+instanceUrl+'/services/apexrest/GetDocumentList';  
            req.httpMethod = 'GET';
            
            RestContext.request = req;
            RestContext.response = res;
            
            // request 1 No docList
            GetDocumentList.doGet();
            Test.stopTest();
            
         }
    
 }