Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <label>Current Processor</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <businessProcess>Partner Registration Process</businessProcess>
        <label>Partners</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Blue Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestBatchUpdateCmpInactiveDormantStatus.cls
@istest
public class TestBatchUpdateCmpInactiveDormantStatus
{
/*
    @istest
    public static void unitTest()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Partners';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.lastName = 'test';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.campaignId = camp.Id;
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';
        opp.AccountId=acc.Id;        
        insert opp;
        Test.setCreatedDate(opp.Id, System.now().addDays(-70));
        
        Test.startTest();
        Database.executebatch(new BatchUpdateCmpIDSStatus(),1);
        Test.stopTest();
    }
    */
    @istest
    public static void unitTestLeadGT120()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Partners';
        insert camp;
        
        Lead ld = new Lead(FirstName = 'Test', LastName  = 'Testofferson', Company   = 'Test Industries LLC',
            Email= 'test@test.com', Phone = '18005551111',Status = 'Test');
        insert ld;
        
        CampaignMember cm=new CampaignMember();
        cm.campaignId=camp.id;
        cm.leadId=ld.id;
        insert cm;
        
        Test.setCreatedDate(cm.Id, System.now().addDays(-131));
        
        Test.startTest();
        Database.executebatch(new BatchUpdateLeadCmpIDSStatus(),1);
        Test.stopTest();
    }
    @istest
    public static void unitTestLeadGT60()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Partners';
        insert camp;
        
        Lead ld = new Lead(FirstName = 'Test', LastName  = 'Testofferson', Company   = 'Test Industries LLC',
            Email= 'test@test.com', Phone = '18005551111',Status = 'Test');
        insert ld;
        
        CampaignMember cm=new CampaignMember();
        cm.campaignId=camp.id;
        cm.leadId=ld.id;
        insert cm;
        
        Test.setCreatedDate(cm.Id, System.now().addDays(-65));
        
        Test.startTest();
        Database.executebatch(new BatchUpdateLeadCmpIDSStatus(),1);
        Test.stopTest();
    }
    @istest
    public static void unitTestLeadLT30()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Partners';
        insert camp;
        
        Lead ld = new Lead(FirstName = 'Test', LastName  = 'Testofferson', Company   = 'Test Industries LLC',
            Email= 'test@test.com', Phone = '18005551111',Status = 'Test');
        insert ld;
        
        CampaignMember cm=new CampaignMember();
        cm.campaignId=camp.id;
        cm.leadId=ld.id;
        insert cm;
        
        Test.startTest();
        Database.executebatch(new BatchUpdateLeadCmpIDSStatus(),1);
        Test.stopTest();
    }
    @istest
    public static void unitTest120()
    {
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.type = 'Partners';
        insert camp;
        
        Account acc = new Account();
        acc.Name = 'Test Account1';
        acc.businessType__c = 'testBusiness';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.lastName = 'test';
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestingOpp';
        opp.leadSource = 'A001';
        opp.campaignId = camp.Id;
        opp.closeDate = date.newInstance(2007, 5, 5);
        opp.stageName = 'Prospecting';
        opp.current_Processor__c = 'Blue Pay';
        opp.AccountId=acc.Id;        
        insert opp;
        Test.setCreatedDate(opp.Id, System.now().addDays(-131));
        
        Test.startTest();
        Database.executebatch(new BatchUpdateCmpIDSStatus(),1);
        Test.stopTest();
    }
}