Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Funding_Status__c</fullName>
        <formula>ISPICKVAL( Campaign__r.Status , &quot;Funding&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Funding Stutus</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Funding_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Funding Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Funded_by_WC__c</fullName>
        <label>Funds Wired</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Funding_Status__c</fullName>
        <label>Funding Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Funded - Processing Trial Completed</fullName>
                </value>
                <value>
                    <fullName>Funded - Needs Follow Up</fullName>
                </value>
                <value>
                    <fullName>Funding Exception Denied</fullName>
                </value>
                <value>
                    <fullName>Not Funded - Activity Too Low</fullName>
                </value>
                <value>
                    <fullName>Funded - Processing Trial Exception Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_90_Day_Post_Funding_Survey_On__c</fullName>
        <label>Send 90 Day Post Funding Survey On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Client_Funding_Survey_On__c</fullName>
        <label>Send Client Funding Survey On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Declined_Survey_On__c</fullName>
        <label>Send Declined Survey On</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestGetFeedBackSurveyHelper.cls
@isTest
Private Class TestGetFeedBackSurveyHelper
{   
    public static Boolean preventGetFeedBackSurveyHelperFromFire = False;
    @TestSetup
    static void setUpData()
    {
        Account acc = new Account();
        acc.name = 'Test Account1';
        acc.BusinessType__c = 'testBusiness';
        insert acc;
        
        Campaign  cm = new Campaign();
        cm.Name = 'Test';
        cm.Type='Internet';
        insert cm;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.LeadSource = 'web';
        opp.StageName = 'Prospecting';
        opp.CloseDate = System.today() + 50;
        opp.CampaignId = cm.Id;
        opp.Current_Processor__c = 'Abanco INTERNATIONAL';
        opp.AccountId = acc.id;
        opp.email_address__c='test@test.com';
        insert opp;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.LastName = 'test';
        con.email='test@test.com';
        insert con;
        
        OpportunityContactRole role =new OpportunityContactRole();
        role.ContactId = con.Id;
        role.OpportunityId  = opp.Id;
        role.isPrimary=true;
        role.Role = 'Principal 1'; 
        insert role;
    }
    static testMethod void unitTestDeclined()
    {
        Test.startTest();
        Opportunity oppL=[Select 
                                id, name, stageName,send_declined_survey_on__c 
                            from 
                                Opportunity 
                            where 
                                name='testOpportunity' Limit 1];
        oppL.send_declined_survey_on__c=system.now();
        oppL.StageName='Declined';
        update oppL;
        Test.stopTest();
    }
    
    static testMethod void unitTestFundingSurvey1Day()
    {
        Test.startTest();
        Opportunity oppL=[Select 
                                id, name, stageName,Send_Client_Funding_Survey_On__c,Amount,Funded_by_WC__c,Client_Funding_Survey__c   
                            from 
                                Opportunity 
                            where 
                                name='testOpportunity' Limit 1];
        oppL.Send_Client_Funding_Survey_On__c=system.now();
        oppL.StageName='Closed Won';
        oppL.Amount  = 1;
        oppL.Client_Funding_Survey__c = true;
        preventGetFeedBackSurveyHelperFromFire =False;
        oppL.Funded_by_WC__c = system.now();
        update oppL;
        Test.stopTest();
    }
    static testMethod void unitTestFundingSurvey90Day()
    {
        Test.startTest();
        Opportunity oppL=[Select 
                                id, name, stageName,Send_90_Day_Post_Funding_Survey_On__c, Funding_status__c,Amount,Funded_by_WC__c
                            from 
                                Opportunity 
                            where 
                                name='testOpportunity' Limit 1];
        oppL.Send_90_Day_Post_Funding_Survey_On__c=system.now();
        oppL.StageName='Closed Won';
        oppL.Funding_status__c='Funded - Processing Trial Completed';
        oppL.Amount  = 1;
        oppL.Client_Funding_Survey__c = true;
        preventGetFeedBackSurveyHelperFromFire =False;
        oppL.Funded_by_WC__c = system.now();
        update oppL;
        Test.stopTest();
    }
}