Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Funded_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Funded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestOppGreenTreeViewController.cls
@istest
public class TestOppGreenTreeViewController
{
    public static testMethod void unitTest()
    {        
        Test.startTest();
        
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
       
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.StageName='closed';
        opp.Renewal_Funded_Amount__c = 1000;
        insert opp;
        
        Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
        gt.opportunity__c=opp.id;
        gt.Amount__c= 20000;
        gt.Amount_Sold__c= 1000;
        insert gt;
        
        gt.Amount__c= 10000;
        gt.Amount_Sold__c= 1000;
        Update gt;
        
       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController (sc);
        nc.edit();
        nc.onSave();       
        nc.onCancel();
      
        apexpages.currentpage().getparameters().put('Id',opp.id);
        Test.stopTest();
    }
    
    public static testMethod void unitTest1()
    {  
        Test.startTest();        
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
        
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.Renewal_Funded_Amount__c = 1000;
        opp.StageName='closed';  
                              
            
        PageReference p = page.GreenTreeInfoDisplay;
        Test.setCurrentPage(p); 
        ApexPages.currentPage().getParameters().put('Id', opp.Id);       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController(sc);
        nc.edit();
        nc.onSave();       
       
        Test.stopTest();
    }
     public static testMethod void unitTest2()
    {        
        Test.startTest();
        
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
       
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.StageName='closed';
        opp.Renewal_Funded_Amount__c = 1000;
        insert opp;
        
        Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
        gt.opportunity__c=opp.id;
        gt.Amount__c= 20000;
        gt.Amount_Sold__c= 1000;
        insert gt;
        
        gt.Amount__c= 10000;
        gt.Amount_Sold__c= 1000;
        Update gt;
        
       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController (sc);
        nc.edit();
        nc.onSave();       
        nc.onCancel();
      
        apexpages.currentpage().getparameters().put('Id',opp.id);
        Test.stopTest();
    }
    public static testMethod void unitTest3()
    {        
        Test.startTest();
        
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
       
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.StageName='closed';
        opp.Renewal_Funded_Amount__c = 1000;
        insert opp;
        
        Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
        gt.opportunity__c=opp.id;
        gt.Amount__c= 20000;
        gt.Amount_Sold__c= 1000;
        insert gt;
        
        gt.Amount__c= 10000;
        gt.Amount_Sold__c= 1000;
        Update gt;
        
       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController (sc);
        nc.edit();
        nc.onSave();       
        nc.onCancel();
      
        apexpages.currentpage().getparameters().put('Id',opp.id);
        Test.stopTest();
    }
    public static testMethod void unitTest4()
    {        
        Test.startTest();
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
       
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.StageName='closed';
        opp.Renewal_Funded_Amount__c = 1000;
        insert opp;
        
        Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
        gt.opportunity__c=opp.id;
        gt.Amount__c= 20000;
        gt.Amount_Sold__c= 1000;
        insert gt;
        
        gt.Amount__c= 10000;
        gt.Amount_Sold__c= 1000;
        Update gt;
        
       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController (sc);
        nc.edit();
        nc.onSave();       
        nc.onCancel();
      
        apexpages.currentpage().getparameters().put('Id',opp.id);
        Test.stopTest();
    }
    public static testMethod void unitTest5()
    {        
        Test.startTest();
        Account ac= new Account();
        ac.name='testcase';
        insert ac;
        Campaign cp= new Campaign();
        cp.name='cppname';
        insert cp;
       
        Opportunity opp = new Opportunity();
        opp.name='oppname';
        opp.accountid=ac.id;
        opp.ForecastCategoryName='Commit';
        opp.LeadSource='A001';
        opp.Campaignid=cp.id;
        opp.CloseDate=system.today();
        opp.Current_Processor__c='1st federal financial';
        opp.StageName='closed';
        opp.Renewal_Funded_Amount__c = 1000;
        insert opp;
        
        Green_Tree_Oppy_Extension__c gt=new Green_Tree_Oppy_Extension__c();
        gt.opportunity__c=opp.id;
        gt.Amount__c= 20000;
        gt.Amount_Sold__c= 1000;
        insert gt;
        
        gt.Amount__c= 10000;
        gt.Amount_Sold__c= 1000;
        Update gt;
        
       
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        OppGreenTreeViewController nc= new OppGreenTreeViewController (sc);
        nc.edit();
        nc.onSave();       
        nc.onCancel();
      
        apexpages.currentpage().getparameters().put('Id',opp.id);
        Test.stopTest();
    }
}