Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FederalTaxID__c</fullName>
        <label>Federal Tax ID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Account status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <label>Partners</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Oppr_Offers</relationshipLabel>
        <relationshipName>Oppr_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr_Offer</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppr_Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/Biz2CreditUtils.cls
/*
@Name               : Biz2CreditUtils
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        :  
@Revision History   : Uses of Field Status_Reason__c Commented/Removed By MK Conam 2 Dec 2015
*/

public with sharing class Biz2CreditUtils 
{

    /*COMMNETED DS-CONAM unable to find usage
    public static Account createAccount(Application app) {

        Account acct = new Account();
        acct.name = app.MerchantID;
        acct.BillingCity = app.BusinessCity;
        acct.FederalTaxID__c = app.FederalTaxId;
        insert acct;
        return acct;
    }
    
    public static Contact createContact(Application app) {

        Contact con = new Contact();
        con.FirstName = app.FirstName;
        con.LastName = app.LastName;
        con.MailingCity = app.HomeCity;
        insert con;
        return con;
    }
    */
    public static Opportunity createOpportunity(Application app) {

        Opportunity opp = new Opportunity();
        opp.External_ID__c = app.ExternalID;
        opp.Source_System__c = 'Biz2Credit';
        opp.Status__c = 'Processing';
        // opp.Status_Reason__c = 'Passed';
        opp.Name = app.ExternalID;
        opp.StageName = 'Prospecting';
        opp.CloseDate = system.today();
        insert opp;
        return opp;
    }

    public static Date dateConversion(String conDate) {
        Date d;
        try 
        {
            Integer year = integer.valueOf(conDate.substring(0, 4));
            Integer month = integer.valueOf(conDate.substring(4, 6));
            Integer day = integer.valueOf(conDate.substring(6, 8));
            System.debug('year....' + year + '....month...' + month + '..day..' + day);
            d = Date.newInstance(year, month, day);
        } 
        catch (Exception e) 
        {
            return null;
        }
        return d;
    }

    public static String getInstanceURL() {
        // code for fetch server
        String sfdcUrl;
        String sasf = URL.getSalesforceBaseUrl().getHost();
        Integer endpoint = 0;
        endpoint = sasf.indexOf('.visual.force.');

        Integer startpoint = 0;
        startpoint = sasf.indexOf('.');
        System.debug('endpoint.......' + endpoint + '...........startpoint..' + startpoint);
       /*DS-CONAM
            if (endpoint >= 0 && startpoint >= 0)
            {
                sfdcUrl = 'https://' + sasf.substring(startpoint + 1, endpoint) + '.salesforce.com';
            }
        */
        sfdcUrl=(endpoint >= 0 && startpoint >= 0) ? 'https://' + sasf.substring(startpoint + 1, endpoint) + '.salesforce.com': NULL;
        System.debug('sfdcUrl....' + sfdcUrl);
        System.debug('sasf....' + sasf);

        return sasf;
    }

    public static Campaign createCampaign()
    {
        Campaign cam = new Campaign();
        cam.Name = 'testCom';
        cam.type = 'partners';
        insert cam;
        return cam;
    }
    public static Opportunity createOpportunity() 
    {
        Opportunity opp = new Opportunity();
        opp.Name = 'testOp1';
        opp.LeadSource = 'A001';
        opp.Campaign = Biz2CreditUtils.createCampaign();
        opp.CloseDate = System.today();
        opp.StageName = 'Approved';
        opp.External_ID__c = '123456';
        opp.Status__c = 'Contract Available';
        opp.Source_System__c = 'Biz2Credit';
        opp.Current_Processor__c = 'ABC Global System';
        insert opp;
        return opp;
    }
    
    public static Opportunity createOpportunity_new()
    {
        Opportunity opp = new Opportunity();
        opp.Name = 'testOp1';
        opp.LeadSource = 'A001';
        opp.Campaign = Biz2CreditUtils.createCampaign();
        opp.CloseDate = System.today();
        opp.StageName = 'Approved';
        opp.External_ID__c = '' + System.currentTimeMillis();
        opp.Status__c = 'Contract NOT Available';
        opp.Source_System__c = 'B2C';
        opp.Current_Processor__c = 'ABC Global System';
        insert opp;
        return opp;
    }

    public static Oppr_Document__c createOppDoc(Opportunity opp)
    {
        Oppr_Document__c oppDoc = new Oppr_Document__c();
        oppDoc.Document_Name__c = 'testDoc';
        oppDoc.Additional_Notes__c = 'testDoc';
        oppDoc.Opportunity__c = opp.Id;
        insert oppDoc;
        return oppDoc;
    }
    
    public static Attachment createAttachment(Oppr_Document__c oppDoc)
    {
        Attachment attachment = new Attachment();
        attachment.Body = Blob.valueOf('This is Test.');
        attachment.Name = String.valueOf('test.txt');
        attachment.ParentId = oppDoc.Id;
        insert attachment;
        return attachment;
    }

    public static Oppr_Offer__c createOpprOffer(String oppID) {
        Oppr_Offer__c opprOffer = new Oppr_Offer__c();
        opprOffer.Amount__c = 123;
        opprOffer.Amount_Sold__c = 12;
        opprOffer.Opportunity__c = oppID;
        insert opprOffer;
        Oppr_Offer__c oppr = [select 
                                    id, Status__c, Name 
                                from 
                                    Oppr_Offer__c 
                                where 
                                    Id = : opprOffer.id LIMIT 1];
        update oppr;
        return oppr;
    }

}