Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set-Up</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Option</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Global Payments</fullName>
                </value>
                <value>
                    <fullName>GPS - Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Integrity</fullName>
                </value>
                <value>
                    <fullName>NOVA</fullName>
                </value>
                <value>
                    <fullName>PowerPay</fullName>
                </value>
                <value>
                    <fullName>RapidAdvance Chooses</fullName>
                </value>
                <value>
                    <fullName>University Bank</fullName>
                </value>
                <value>
                    <fullName>RBSLynk</fullName>
                </value>
                <value>
                    <fullName>TSYS</fullName>
                </value>
                <value>
                    <fullName>iPayment</fullName>
                </value>
                <value>
                    <fullName>EVO</fullName>
                </value>
                <value>
                    <fullName>Humboldt</fullName>
                </value>
                <value>
                    <fullName>Cynergy</fullName>
                </value>
                <value>
                    <fullName>ONEPAY</fullName>
                </value>
                <value>
                    <fullName>Merrick</fullName>
                </value>
                <value>
                    <fullName>EPR</fullName>
                </value>
                <value>
                    <fullName>PayProTec</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approved_With_Conditions__c</fullName>
        <label>Approved With Conditions</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DDA_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DDA Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DDA_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DDA Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exception Requested?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Existing_Competitor_Advance2__c</fullName>
        <label>Existing Competitor Advance?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NA RENEWAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>If_no_explain__c</fullName>
        <label>If no, explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>New_Processor_Setup_Completed__c</fullName>
        <label>New Processor Setup Completed:</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Check_Sent__c</fullName>
        <label>Payoff Check Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <inlineHelpText>If updated, update also current processor field</inlineHelpText>
        <label>New Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Bancard Central</fullName>
                </value>
                <value>
                    <fullName>Benchmark</fullName>
                </value>
                <value>
                    <fullName>Card Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Century Bankcard</fullName>
                </value>
                <value>
                    <fullName>Chosen Payment Systems</fullName>
                </value>
                <value>
                    <fullName>CoCard</fullName>
                </value>
                <value>
                    <fullName>Cynergy</fullName>
                </value>
                <value>
                    <fullName>Daily ACH</fullName>
                </value>
                <value>
                    <fullName>Daily Fixed-Amount ACH</fullName>
                </value>
                <value>
                    <fullName>Direct Connect</fullName>
                </value>
                <value>
                    <fullName>Electronic Payments Inc.</fullName>
                </value>
                <value>
                    <fullName>Electronic Processing Services, LLC</fullName>
                </value>
                <value>
                    <fullName>Elite Data-ChasePaymentech</fullName>
                </value>
                <value>
                    <fullName>EVO</fullName>
                </value>
                <value>
                    <fullName>Evolution Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First American Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First Data</fullName>
                </value>
                <value>
                    <fullName>First Data – Omaha</fullName>
                </value>
                <value>
                    <fullName>ForwardLine</fullName>
                </value>
                <value>
                    <fullName>Humboldt Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Integrity</fullName>
                </value>
                <value>
                    <fullName>I-Payment</fullName>
                </value>
                <value>
                    <fullName>IRN Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Lockbox-KBT</fullName>
                </value>
                <value>
                    <fullName>Mercury</fullName>
                </value>
                <value>
                    <fullName>Merrick</fullName>
                </value>
                <value>
                    <fullName>Moneris/Canada</fullName>
                </value>
                <value>
                    <fullName>MPI</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rapid_Funding_Addendum__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rapid Funding Addendum</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Received_Rapid_Funding_Addendum__c</fullName>
        <label>Received Rapid Funding Addendum?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resulting_Process__c</fullName>
        <label>Resulting Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>EPR1 (merchant processing with partner)</fullName>
                </value>
                <value>
                    <fullName>EPR2 (merchant NOT processing with partner)</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>NMA Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Survey_Available_Due_Date__c</fullName>
        <label>Site Survey Expected Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Available__c</fullName>
        <label>Site Survey Available</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Ordered_Due_Date__c</fullName>
        <label>Site Survey Ordered Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Survey_Ordered__c</fullName>
        <label>Site Survey Ordered Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set Up</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPS - Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Rapid Advance Chooses</fullName>
                </value>
                <value>
                    <fullName>EPR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_For_Funding_Approval__c</fullName>
        <label>Submitted For Funding Approval:</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Third_Party_Company_Name__c</fullName>
        <label>Third Party Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Third_Party_Payoff_Amount__c</fullName>
        <label>Third Party Payoff Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Third_Party_Payoff__c</fullName>
        <label>Third Party Payoff?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ProcessorInformation_Ctrl.cls
/*
@Name               : ProcessorInformation_Ctrl
@Author             : DS-CONAM
@Date               : 13 APR 2015
@Revision History   : Added 3 new fields On Hold_Start_Date__c, On Hold_Stop_Date__c and On Hold_Stop_Date__c

@Author             : MK CONAM
@Date               : 2 DEC 2015
@Revision History   : Uses of Field received_rapid_funding_addendum__c,amex only_gcs_mid _2__c,
                      if_no_explain__c Commented/Removed

@Author             : DS-CONAM
@Date               : 22 FEB 2015
@Revision History   : Uses of Field received_rapid_funding_addendum__c,amex only_gcs_mid_ 2__c,
                      if_no_explain__c added back
*/

public class ProcessorInformation_Ctrl 
{
    public Opportunity oppRecord{get; set;}
    public Account accRecord{get; set;}
    
    public ProcessorInformation_Ctrl()
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');        
        if (oppId != null && !oppId.trim().equals(''))
        {
            List<Opportunity> oppList = [SELECT
                                             Id,AccountId,Current_Processor__c, Processor_Name__c,Site_Survey_Ordered_Due_Date__c,
                                             Split_Fund_Set_Up__c, Resulting_Process__c,Site_Survey_Available__c,third_party_company_name__c,
                                             New_Processor_Setup_Completed__c, Site_Survey_Available_Due_Date__c, Approved_With_Conditions__c,
                                             Exception_Requested__c, Site_Survey_Ordered__c, third_party_payoff_amount__c, Submitted_For_Funding_Approval__c, 
                                             Existing_Competitor_Advance2__c,Third_Party_Payoff__c,DDA_Requested__c,DDA_Received__c, Payoff_Amount__c,
                                             Payoff_Check_Sent__c, Processing_Representative__c,Competitor_Advance_Company__c ,
                                             received_rapid_funding_addendum__c, rapid_funding_addendum__c ,if_no_explain__c                         
                                         FROM 
                                             Opportunity 
                                         WHERE 
                                             Id = :oppId LIMIT 1];
             System.debug(oppList.get(0));
                                            
            if (oppList != null && !oppList.isEmpty()) 
            {
                oppRecord = oppList.get(0); 
                List<Account> accountList = [SELECT 
                                                    Id, Name, Number_of_Locations__c,
                                                    Number_of_Terminals_at_Location__c
                                                FROM 
                                                    Account 
                                                WHERE 
                                                    Id =:oppRecord.AccountId];  
                if(accountList != null && !accountList.isEmpty()) 
                {
                    accRecord =   accountList.get(0);
                }                           
            }
        }
        else 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
    
    public PageReference doSave() 
    {           
        try
        {
            upsert oppRecord;
            if(accRecord != null)
            {
                upsert accRecord;
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Processor Information Saved Successfully!'));
        }
        catch(Exception e)
        { 
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    } 
    
}