Rapid Prd/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BusinessType__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Business</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Appliance Store</fullName>
                </value>
                <value>
                    <fullName>Auto Service</fullName>
                </value>
                <value>
                    <fullName>Auto Supply Store</fullName>
                </value>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Bar/Tavern</fullName>
                </value>
                <value>
                    <fullName>Beauty/Nail/Spa Salon</fullName>
                </value>
                <value>
                    <fullName>Bicycle Store</fullName>
                </value>
                <value>
                    <fullName>Book Store</fullName>
                </value>
                <value>
                    <fullName>Camera Store</fullName>
                </value>
                <value>
                    <fullName>Candy Store</fullName>
                </value>
                <value>
                    <fullName>Carwash</fullName>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                </value>
                <value>
                    <fullName>Cell Phone Store</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Clothing Store</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Computer and Software Store</fullName>
                </value>
                <value>
                    <fullName>Consignment/Second Hand Store</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Convenience Store</fullName>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Drug and Vitamin Store</fullName>
                </value>
                <value>
                    <fullName>Drycleaner</fullName>
                </value>
                <value>
                    <fullName>Electronics/TV and Radio Store</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Floor Covering Store</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Sales_Check_List__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Check Lists</relationshipLabel>
        <relationshipName>Sales_Check_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Check List</label>
    <nameField>
        <label>Sales Check List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Check Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestDealTerms_Ctrl.cls
@isTest 

private class TestDealTerms_Ctrl 
{
    public static testMethod void dealTerms_UnitTest() 
    {       
        Test.startTest(); 
        
        // DS-CONAM CALC.apexTesting();
        Account testAccount = new Account(name ='Test Account1',BusinessType__c ='testBusiness');
        insert testAccount;  
        System.Assert(testAccount.Id != null, 'The Test Account did not insert properly, please check validation rules and other mechanisms');           
        
        Campaign  cmObj = new Campaign(Name = 'Test',Type='Internet');
        insert cmObj;
        
        Opportunity opp = new Opportunity(Name = 'testOpportunity',LeadSource = 'web',StageName = 'Prospecting',Current_Processor__c = 'Abanco INTERNATIONAL', CloseDate = System.today() +50,AccountId = testAccount.id,CampaignId = cmObj.Id);
        insert opp;
        
        Opportunity opp1 = new Opportunity(Name = 'testOpportunity1',LeadSource = 'Facebook',StageName = 'Prospecting',Current_Processor__c = 'Abanco INTERNATIONAL1', CloseDate = System.today() +25,AccountId = testAccount.id,CampaignId = cmObj.Id);
        insert opp1;
        
        Sales_Check_List__c scl = new Sales_Check_List__c(name = 'TestSales',Opportunity__c =opp.id);
        insert scl;
        
        PageReference pTemp = Page.DealTermsPage;
        Test.setCurrentPage(pTemp);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
          
        ApexPages.currentPage().getParameters().put('Id', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.currentPage().getParameters().put('opp1Id', opp1.Id);
        
        DealTerms_Ctrl dealObj = new DealTerms_Ctrl();
        dealObj.doSave();        
        try
        {
            if(opp.Id ==Null)
            {
                return ;
            }
        }
        
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }        
        Test.stopTest();     
    }
    
    public static testMethod void dealTerms_UnitTest1() 
    {       
        Test.startTest(); 
        
        // DS-CONAM CALC.apexTesting();
        Account testAccount = new Account(name ='Test Account1',BusinessType__c ='testBusiness');
        insert testAccount;  
        testAccount.Name ='TestUpdate';
        update testAccount;
        
        System.Assert(testAccount.Id != null, 'The Test Account did not insert properly, please check validation rules and other mechanisms');           
        
        Campaign  cmObj = new Campaign(Name = 'Test', Type='Internet');
        insert cmObj;       

        Opportunity opp = new Opportunity(Name = 'testOpportunity',LeadSource = 'web',StageName = 'Prospecting',Current_Processor__c = 'Abanco INTERNATIONAL', CloseDate = System.today() +50,AccountId = testAccount.id,CampaignId = cmObj.Id);
        insert opp;
        
        Opportunity opp1 = new Opportunity(Name = 'testOpportunity1',LeadSource = 'Facebook',StageName = 'Prospecting',Current_Processor__c = 'Abanco INTERNATIONAL1', CloseDate = System.today() +25,AccountId = testAccount.id,CampaignId = cmObj.Id);
        insert opp1;
        
        
        
        PageReference pTemp = Page.DealTermsPage;
        Test.setCurrentPage(pTemp);        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);          
        ApexPages.currentPage().getParameters().put('', opp.Id);
        ApexPages.currentPage().getParameters().put('oppId', opp.Id);
        ApexPages.currentPage().getParameters().put('opp1Id', opp1.Id);
               
        DealTerms_Ctrl dealObj = new DealTerms_Ctrl();  
              
        dealObj.doSave();        
        try
        {
            if(opp.Id !=Null)
            {
                return ;
            }
        }        
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        
        
        
        Test.stopTest();     
    }
}