Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quotes Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Funded - Rapid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Contact_Email__c</fullName>
        <description>contact&apos;s email address</description>
        <label>Campaign Contact Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>BOOP_Status__c</fullName>
        <label>BOOP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Based__c</fullName>
        <label>Home Based?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Marbles</relationshipLabel>
        <relationshipName>Marbles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Waiting on Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Submission</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quote Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>BOC Incomplete</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sent to FundBox</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Presented</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Where_Did_You_Find_This_Client__c</fullName>
        <label>Where Did You Find This Client?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BA Transfer</fullName>
                </value>
                <value>
                    <fullName>Credit Karma</fullName>
                </value>
                <value>
                    <fullName>BOBA Dialer</fullName>
                </value>
                <value>
                    <fullName>Custom List</fullName>
                </value>
                <value>
                    <fullName>Email Blast</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>UW Unqual</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Sr BA Qualified</fullName>
                </value>
                <value>
                    <fullName>Dialer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Home_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home-Based</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marble</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/sendEmailToCampaignContactTest.cls
@isTest
public class sendEmailToCampaignContactTest
{
    @isTest
    public static void sendEmail()
    {
        
        Test.startTest();
        
        Campaign cp = new Campaign(Name = 'abc',Type = 'Internet',Campaign_Contact_Email__c ='test@gmail.com',IsActive=true);
        insert cp;
        
        Campaign campRecord =[select id,Name from Campaign where id =: cp.id];
        System.assertEquals(campRecord.Name, 'abc');

        opportunity opp=new opportunity ();
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today();
        opp.Name = 'Test Opportunity';
        opp.LeadSource = 'Radio';
        opp.ForecastCategoryName = 'Pipeline';
        opp.CampaignId = cp.Id;
        insert opp;
        
        Opportunity oppRecord =[select id,Name from Opportunity where id =: opp.id];
        System.assertEquals(oppRecord.Name, 'Test Opportunity');
        
        Marble__c m = new Marble__c();
        m.Home_Based__c = 'Yes';
        m.Where_Did_You_Find_This_Client__c = 'Renewal';
        m.Name = 'abc';
        m.BOOP_Status__c = 'New';
        m.Opportunity_Reference__c = opp.Id;
        insert m;
        
        Marble__c marbleRecord =[select id,Name from Marble__c where id =:m.id];
        System.assertEquals(marbleRecord.Name, 'abc');
        
        BOOP__c b = new BOOP__c();
        b.Status__c = 'New';
        b.Marble__c = m.Id;
        b.Review_Status__c = true;
        insert b;
        
        BOOP__c boopRecord = [Select Id,Status__c from BOOP__c where Id =: b.Id];
        system.assertEquals(b.Status__c, 'New');
        
        b.Status__c = 'Submitted';
        update b;
        
        BOOP__c bbRecord = [Select Id,Status__c from BOOP__c where Id =: b.Id];
        system.assertEquals(b.Status__c, 'Submitted');
        
        Test.stopTest();
    }
}