Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>BOOP_Status__c</fullName>
        <label>BOOP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/BlankBoopStatusField.cls
public class BlankBoopStatusField
{
    public static void BoopStatusField(List<BOOP__c> lstBoop)
    {
        set<Id> marbleId = new set<Id>();
        for(BOOP__c boopTemp : lstBoop)
        {
            marbleId.add(boopTemp.Marble__c);
        }
        
        List<Marble__c> lstMarble = new List<Marble__c>();
        for(Marble__c marbleTemp : [Select Id,(Select Marble__c from Quotes__r) from Marble__c where Id IN : marbleId])
        {
            if(marbleTemp.Quotes__r.size() <= 0)
            {
                marbleTemp.BOOP_Status__c = Null;
            }
            
            lstMarble.add(marbleTemp);
        }
        
        if(lstMarble.size() > 0)
        update lstMarble;
    }
}