Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Id</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Broker_Out_Op</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quotes Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Funded - Rapid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>BOOP_Status__c</fullName>
        <label>BOOP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Waiting on Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Submission</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quote Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>BOC Incomplete</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sent to FundBox</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Presented</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/UpdateBOOPStatus.cls
public class UpdateBOOPStatus
{
    // Insert and update of BOOP
    public static void updateStatus(List<BOOP__c> lstBoop)
    {
        try{
            set<Id> marbleId = new set<Id>(); 
            for(BOOP__c boopTemp : lstBoop)
            {
                if(boopTemp.status__c != Null && boopTemp.Marble__c != Null)
                {
                    marbleId.add(boopTemp.Marble__c);
                    system.debug('marbleId'+marbleId);
                }   
            }
            
            List<Marble__c> lstMarble = new List<Marble__c>();
            for(Marble__c marbleTemp : [Select Id,BOOP_status__c,(Select Marble__c,Status__c from Quotes__r) from Marble__c where Id IN : marbleId])
            {
                system.debug('marbleTemp '+marbleTemp);
                if(marbleTemp.Quotes__r.size() > 0)
                {
                    system.debug('Inside if');
                    for(BOOP__c boopTemp : marbleTemp.Quotes__r)
                    {
                        marbleTemp.Boop_status__c = boopTemp.Status__c;
                    }
                    
                }
                lstMarble.add(marbleTemp);
            }
            
            if(lstMarble.size() > 0)
            update lstMarble;
        }
        catch(Exception e){}
    }
    
    // Delete of BOOP
    public static void BoopStatusField(List<BOOP__c> lstBoop)
    {
        try{
            set<Id> marbleId = new set<Id>();
            for(BOOP__c boopTemp : lstBoop)
            {
                marbleId.add(boopTemp.Marble__c);
            }
            
            List<Marble__c> lstMarble = new List<Marble__c>();
            for(Marble__c marbleTemp : [Select Id,(Select Marble__c from Quotes__r) from Marble__c where Id IN : marbleId])
            {
                if(marbleTemp.Quotes__r.size() <= 0)
                {
                    marbleTemp.BOOP_Status__c = Null;
                }
                
                lstMarble.add(marbleTemp);
            }
            
            if(lstMarble.size() > 0)
            update lstMarble;
        }
        catch(Exception e){}
    }
    
    
    public static void populateMarbleOwnerId(List<BOOP__c> lstBoop)
    {
        try{
            Set<Id> marbleId = new Set<Id>();
            for(BOOP__c boopTemp : lstBoop)
            {
                if(boopTemp.Marble__c != Null)
                    marbleId.add(boopTemp.Marble__c);
            }
            
            
            if(marbleId.Size()> 0){
                Map<Id,Marble__c> marbleMap = new Map<Id,Marble__c>([Select Id,OwnerId FROM Marble__c WHERE ID IN : marbleId]);
                
                for(BOOP__c boopTemp  : lstBoop)
                {
                    boopTemp.OwnerId__c = marbleMap.get(boopTemp.Marble__c).OwnerId;
                }
            }
        }catch(Exception e){}  
    }
}