Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Accountable_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accountable Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quotes Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Funded - Rapid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Submission_Count__c</fullName>
        <description>This field has been created as per Task 314 to capture the total Count of Submission done.</description>
        <label>Total Submission Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>BOOP_Status__c</fullName>
        <label>BOOP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Based__c</fullName>
        <label>Home Based?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Waiting on Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Submission</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quote Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>BOC Incomplete</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sent to FundBox</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Presented</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Where_Did_You_Find_This_Client__c</fullName>
        <label>Where Did You Find This Client?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BA Transfer</fullName>
                </value>
                <value>
                    <fullName>Credit Karma</fullName>
                </value>
                <value>
                    <fullName>BOBA Dialer</fullName>
                </value>
                <value>
                    <fullName>Custom List</fullName>
                </value>
                <value>
                    <fullName>Email Blast</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>UW Unqual</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Sr BA Qualified</fullName>
                </value>
                <value>
                    <fullName>Dialer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/BOOPTriggerHandlerTest.cls
/*
@Name               : BOOPTriggerHandlerTest
@Author             : DS-Conam
@Date               : 6 March 2018
@Description        : Calculate submission count on Boop
@Class         : BOOPTriggerHandler, BOOPTriggerHelper
*/
@isTest
public class BOOPTriggerHandlerTest
{
    @isTest
    public static void submissionOnInsert()
    {
        Test.startTest();
        Marble__c marble = new Marble__c();
        marble.Home_Based__c = 'Yes';
        marble.Where_Did_You_Find_This_Client__c = 'Renewal';
        marble.Name = 'abc';
        marble.BOOP_Status__c = 'New';
        insert marble;    
        
        BOOP__c newRecord = new BOOP__c();
        newRecord.Status__c = 'New';
        newRecord.Marble__c = marble.Id;
        newRecord.Accountable_Submitted__c=true;
        insert newRecord;
        
        List<BOOP__c> bTemp=[Select id, Total_Submission_Count__c,Accountable_Submitted__c from BOOP__c where id=:newRecord.id];
        System.assertEquals(1,bTemp.get(0).Total_Submission_Count__c );
        
        newRecord.Accountable_Submitted__c=false;
        update newRecord;
        
        bTemp=[Select id, Total_Submission_Count__c,Accountable_Submitted__c from BOOP__c where id=:newRecord.id];
        System.assertEquals(0,bTemp.get(0).Total_Submission_Count__c );
        Test.stopTest();
    } 
}