Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quotes Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Funded - Rapid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Contact_Email__c</fullName>
        <description>contact&apos;s email address</description>
        <label>Campaign Contact Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>Opportunity_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Marbles</relationshipLabel>
        <relationshipName>Marbles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Waiting on Documents</fullName>
                </value>
                <value>
                    <fullName>Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Submission</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quote Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>BOC Incomplete</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Sent to FundBox</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Application</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>In-Process</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Presented</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Marble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marble</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/SendEmailToCampaignContact.cls
public class SendEmailToCampaignContact
{
    public static void sentOutEmail(List<BOOP__c> ListBoop, Map<Id,BOOP__c> OldBoopMap)
    {
        if(CheckRecursive.runOnce())
        {
            Map<Id,String> mapMarbleIdRecord = new Map<Id,String>();
            Set<Id> marbleId = new Set<Id>();
            for(BOOP__c boopTemp : ListBoop)
            {
                BOOP__c oldBoopRecord =  OldBoopMap.get(boopTemp.Id);
                if(oldBoopRecord.Status__c != boopTemp.Status__c)
                {
                    marbleId.add(boopTemp.Marble__c);
                }
            }
            if(marbleId.size() >0)
            {
                List<Marble__c> lstMarble = [Select Id,Opportunity_Reference__r.Campaign.Campaign_Contact_Email__c from Marble__c where Id IN : marbleId];
                List<String> StrList =  new List<String>();
                for(Marble__c marbleTemp : lstMarble)
                {
                    if(marbleTemp.Opportunity_Reference__r.Campaign.Campaign_Contact_Email__c != null){
                        mapMarbleIdRecord.put(marbleTemp.Id,marbleTemp.Opportunity_Reference__r.Campaign.Campaign_Contact_Email__c);
                    }
                }
                
                String msgbody ='';
                Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    
                for(BOOP__c boopTemp : ListBoop)
                {
                   
                    BOOP__c oldBoopRecord =  OldBoopMap.get(boopTemp.Id);
                    if(oldBoopRecord.Status__c != boopTemp.Status__c && mapMarbleIdRecord.ContainsKey(boopTemp.Marble__c))
                    {
                        system.debug('mapMarbleIdRecord.get(boopTemp.Marble__c)@@@'+mapMarbleIdRecord.get(boopTemp.Marble__c));
                        
                        String contactEmail = mapMarbleIdRecord.get(boopTemp.Marble__c);
                        
                        for(String str : contactEmail.split(';')){
                             
                            String emailRegex = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';
                            Pattern MyPattern = Pattern.compile(emailRegex);
                        
                            Matcher MyMatcher = MyPattern.matcher(str);
                        
                            if(MyMatcher.matches()){
                                StrList.add(str);
                            }  
                        }
                        system.debug('=======StrList.size()'+StrList.size());
                        if(mapMarbleIdRecord.get(boopTemp.Marble__c) != Null && mapMarbleIdRecord.get(boopTemp.Marble__c) != '' && StrList.size() > 0)
                        {
                            //message.toAddresses = new String[] { mapMarbleIdRecord.get(boopTemp.Marble__c)};
                            system.debug('=========insideemail');
                            message.setToAddresses(StrList);
                            message.subject = 'BOOP status has been changed';
                            msgbody +='Hi,<br/>';
                            msgbody += 'BOOP Status is updated from <b>'+oldBoopRecord.Status__c+'</b> to <b>'+boopTemp.Status__c+'</b><br/>';
                            msgbody += 'View BOOP <a href=https://na33.salesforce.com/'+boopTemp.Id+'>click here.</a>';
                            message.setHtmlBody(msgbody);
                            if(msgbody != Null && msgbody != '')
                            {
                                messages.add(message);
                            }
                            
                        }
                        system.debug('======messages'+messages);
                    }
                }
                if(messages.size() > 0)
                {
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
                }
            }
        }
    }
    
    public static void emailValidation(List<BOOP__c> ListBoop, Map<Id,BOOP__c> OldBoopMap)
    {
        
        Map<Id,String> mapMarbleIdRecord = new Map<Id,String>();
        Set<Id> marbleId = new Set<Id>();
        for(BOOP__c boopTemp : ListBoop)
        {
            BOOP__c oldBoopRecord =  OldBoopMap.get(boopTemp.Id);
            if(oldBoopRecord.Status__c != boopTemp.Status__c)
            {
                marbleId.add(boopTemp.Marble__c);
            }
        }
        if(marbleId.size() >0)
        {
            List<Marble__c> lstMarble = [Select Id,Opportunity_Reference__r.Campaign.Campaign_Contact_Email__c from Marble__c where Id IN : marbleId];
            for(Marble__c marbleTemp : lstMarble)
            {
                mapMarbleIdRecord.put(marbleTemp.Id,marbleTemp.Opportunity_Reference__r.Campaign.Campaign_Contact_Email__c);
            }
            for(BOOP__c boopTemp : ListBoop)
            {
               
                BOOP__c oldBoopRecord =  OldBoopMap.get(boopTemp.Id);
                if(oldBoopRecord.Status__c != boopTemp.Status__c && mapMarbleIdRecord.ContainsKey(boopTemp.Marble__c))
                {
                    if(mapMarbleIdRecord.get(boopTemp.Marble__c) == Null || mapMarbleIdRecord.get(boopTemp.Marble__c) == '')
                    {
                        boopTemp.addError('In order to modify the status, please make sure that Marble should have Primary contact email.');
                    }
                }
            }
        }
    }
}