Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Marble__c</fullName>
        <label>Marble</label>
        <referenceTo>Marble__c</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Submission_Count__c</fullName>
        <description>This field has been created as per Task 314 to capture the total Count of Submission done.</description>
        <label>Total Submission Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>Where_Did_You_Find_This_Client__c</fullName>
        <label>Where Did You Find This Client?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BA Transfer</fullName>
                </value>
                <value>
                    <fullName>Credit Karma</fullName>
                </value>
                <value>
                    <fullName>BOBA Dialer</fullName>
                </value>
                <value>
                    <fullName>Custom List</fullName>
                </value>
                <value>
                    <fullName>Email Blast</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>UW Unqual</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Sr BA Qualified</fullName>
                </value>
                <value>
                    <fullName>Dialer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/BatchCalculateSubmissionCountTest.cls
/*
@Name               : BatchCalculateSubmissionCountTest
@Author             : RS-Conam
@Date               : 16 March 2018
@Description        : Test class for BatchCalculateSubmissionCount
*/
@isTest
public class BatchCalculateSubmissionCountTest
{
    @isTest
    public static void calculateCount()
    {
        List<string> fieldNamesLst = BOOPTriggerHelper.getSubmittedFieldAPINames();
        Set<String> countApiNames = new Set<String>();
        
        List<Boop__c> boopList = new List<Boop__c>();
        
        Marble__c m = new Marble__c();
        m.Name = 'Test Marble';
        m.Where_Did_You_Find_This_Client__c = 'Credit Karma';
        insert m;
        
        Marble__c marble = [SELECT Id,Name FROM Marble__c WHERE Id =: m.Id];
        System.assertEquals(marble.Name , 'Test Marble');
        
        for(Integer i=0;i<100;i++)
        {
            Boop__c newRecord = new Boop__c();
            for(String apiNames : fieldNamesLst)
            {
                newRecord.put(apiNames,true);
                countApiNames.add(apiNames);
            }
            newRecord.Marble__c = m.Id;
            boopList.add(newRecord);
            
         }
        insert boopList;
        
        Boop__c boopCount = [SELECT Id,Total_Submission_Count__c FROM Boop__c where Id =: boopList[0].Id];
        System.assertEquals(countApiNames.size(),boopCount.Total_Submission_Count__c);
        
        System.debug('Size of Map@@@'+countApiNames.size());
        
        Test.startTest();
        BatchCalculateSubmissionCount subCount = new  BatchCalculateSubmissionCount();
        Database.executeBatch(subCount,100);
        Test.stopTest();
    }
}