Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Review_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ReviewBoopStatusAlert.cls
public class ReviewBoopStatusAlert {

    public Id currentId = ApexPages.currentPage().getParameters().get('id');
    public BOOP__c boopRecord = [Select Id,Review_Status__c from BOOP__c where Id =: currentId];
    
    public ReviewBoopStatusAlert(ApexPages.StandardController controller)
    {

        if(boopRecord.Review_Status__c)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'Please Review the Status'));
        }
     }
    public void onLoad()
    {
        boopRecord.Review_Status__c = false;
        update boopRecord;
    }
}