Rapid Prd/src/objects/BOOP__c.object
<CustomObject>
    <description>Marble Quotes</description>
    <fields>
        <fullName>Review_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Quotes Received</fullName>
                </value>
                <value>
                    <fullName>Quotes Sold</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Funded</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Funded - Rapid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Broker Out Op</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BOOP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Out Op</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ReviewStatusOnBOOP.cls
public class ReviewStatusOnBOOP
{
    public static void reviewStatus(List<BOOP__c> LstBoop , Map<Id,BOOP__c> OldMapBoop)
    {
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType boopSchema = schemaMap.get('BOOP__c');
        Map<String, Schema.SObjectField> fieldMap = boopSchema.getDescribe().fields.getMap();
        
        Boolean stopRecursion = false;
            
        for(BOOP__c boopTemp : LstBoop)
        {
            BOOP__c oldBOOP =  OldMapBoop.get(boopTemp.Id);
            if(stopRecursion == false)
            {
                for(String APIName : fieldMap.keySet())
                {
                    if(boopTemp.get(APIName) != oldBOOP.get(APIName) && APIName != 'Status__c' && APIName != 'Review_Status__c' )
                    {
                        boopTemp.Review_Status__c = true;
                        stopRecursion = true;
                    }
                }
            }
        }
    }
}