Rapid Prd/src/objects/CalcLeadCreator__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CalcLeadCreator</label>
</CustomObject>

Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Default_Lead_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CampaignsleadOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CampaignsAssociated</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name_Upload__c</fullName>
        <label>Campaign Name Upload</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestLeadOwnerFromCampaignForCalcLeads.cls
@isTest(SeeAllData=true)
//(SeeAllData=true) is only to access custom settings
private class TestLeadOwnerFromCampaignForCalcLeads
{
	static testmethod void testLead()
    {
		User u=[select id from user where profile.name ='System Administrator' and isactive=true Limit 1];
        List<CalcLeadCreator__c> lCreator=[select name from CalcLeadCreator__C limit 1];
        System.debug(lCreator);
        
        CALC.ApexTesting();   
        Campaign cTest=new Campaign(name='Test Campagin',type='Internet',default_opportunity_owner__C=u.id,default_lead_owner__c=u.id);
        insert cTest;
                
        User uNew=[select id from user where id=:lCreator[0].name];
         
		System.runAs(uNew ) {
		Lead lTest=new Lead();
		lTest.Status='Calling - No Contact Made';
		lTest.LeadSource='Partner-Web';
		lTest.Company='test company';
		lTest.Phone='415789415';
		lTest.Lastname='lastname';
		lTest.Campaign_Name_Upload__c=cTest.id;     
		insert lTest;

        }
    
    }

}