Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Sales_Team_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set Up</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rapid Advance Chooses</fullName>
                </value>
                <value>
                    <fullName>GPS - Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>EPR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Calculate_Due_Dates__c</fullName>
        <label>Calculate Due Dates</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Opportunity record is a clone from a previous opportunity, the link to that original opportunity will be here.  No one has to fill this in manually.</inlineHelpText>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <inlineHelpText>If updated, update also current processor field</inlineHelpText>
        <label>New Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Bancard Central</fullName>
                </value>
                <value>
                    <fullName>Benchmark</fullName>
                </value>
                <value>
                    <fullName>Card Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Century Bankcard</fullName>
                </value>
                <value>
                    <fullName>Chosen Payment Systems</fullName>
                </value>
                <value>
                    <fullName>CoCard</fullName>
                </value>
                <value>
                    <fullName>Cynergy</fullName>
                </value>
                <value>
                    <fullName>Daily ACH</fullName>
                </value>
                <value>
                    <fullName>Daily Fixed-Amount ACH</fullName>
                </value>
                <value>
                    <fullName>Direct Connect</fullName>
                </value>
                <value>
                    <fullName>Electronic Payments Inc.</fullName>
                </value>
                <value>
                    <fullName>Electronic Processing Services, LLC</fullName>
                </value>
                <value>
                    <fullName>Elite Data-ChasePaymentech</fullName>
                </value>
                <value>
                    <fullName>EVO</fullName>
                </value>
                <value>
                    <fullName>Evolution Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First American Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First Data</fullName>
                </value>
                <value>
                    <fullName>First Data – Omaha</fullName>
                </value>
                <value>
                    <fullName>ForwardLine</fullName>
                </value>
                <value>
                    <fullName>Humboldt Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Integrity</fullName>
                </value>
                <value>
                    <fullName>I-Payment</fullName>
                </value>
                <value>
                    <fullName>IRN Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Lockbox-KBT</fullName>
                </value>
                <value>
                    <fullName>Mercury</fullName>
                </value>
                <value>
                    <fullName>Merrick</fullName>
                </value>
                <value>
                    <fullName>Moneris/Canada</fullName>
                </value>
                <value>
                    <fullName>MPI</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Re_Decision_Date__c</fullName>
        <description>Decision for this deal has been changed.</description>
        <label>Re-Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Split_Fund_Set_Up__c</fullName>
        <label>Split Fund Set Up</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GPS - Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Rapid Advance Chooses</fullName>
                </value>
                <value>
                    <fullName>EPR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_to_Sales_Assistant__c</fullName>
        <label>Submit to Sales Assistant</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TriggerTests.cls
/*

Modified
DS-CONAM - 03/04/2015
Version 10 to 32
Added @istest Annotation
Added Test.startTest() and Test.stopTest() to both methods
*/


@istest
public class TriggerTests {
    static testMethod void myTest() {
         Test.startTest(); 
        testOppDates();
        testRenewalClone();
        Test.stopTest();
    }

    static void testRenewalClone() {
        
        User u = [select id from user where isactive = true limit 1];
        Opportunity o = new Opportunity(name='Test Opportunity 12345',closedate = system.today(), stagename = 'Closed Deal', calculate_due_dates__c = system.now());
        insert o;

        opportunityteammember newotm = new opportunityteammember();
        newotm.OpportunityId = o.id;
        newotm.UserId = u.id;
        newotm.TeamMemberRole = 'Partner Sales Representative';
        //newotm.OpportunityAccessLevel = otm.OpportunityAccessLevel;
        insert newotm;
                
        Opportunity o2 = new Opportunity(name='Test Opportunity 12345',closedate = system.today(), stagename = 'Closed Deal', calculate_due_dates__c = system.now());
        o2.previous_opportunity__c = o.id;
        insert o2;
     }   
    static void testOppDates() {
        
        User u = [select id from user where isactive = true limit 1];

        Campaign c = new campaign();
        c.name = 'test';
        c.Sales_Team_Member_1__c = u.id;
        c.Sales_Team_Member_2__c = u.id;
        c.Sales_Team_Member_3__c = u.id;
        c.Sales_Team_Member_4__c = u.id;
        c.Sales_Team_Member_5__c = u.id;
        c.Sales_Team_Member_6__c = u.id;
        insert c;
        
        Opportunity o = new Opportunity(name='Test Opportunity 12345',closedate = system.today(), stagename = 'Closed Deal', calculate_due_dates__c = system.now());
        o.campaignid = c.id;
        o.Decision_Date__c = system.now(); 
        o.submit_to_sales_assistant__c = system.now();
        o.re_decision_date__c = system.now(); 

        insert o;
           
        o.Split_Fund_Set_Up__c  = 'GPS - Rocky Mountain' ;
        update o;

        o.Split_Fund_Set_Up__c  = 'Rapid Advance Chooses'; 
        update o;

        o.Split_Fund_Set_Up__c  = 'xxx'; 
        o.Current_Processor__c = 'Nova'; 
        o.Processor_Name__c = 'Nova';
        update o;

        o.Current_Processor__c = 'Nova'; 
        o.Processor_Name__c = 'xxy';
        update o;

    }


    
}