Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestSendDocuments.cls
@isTest

private class TestSendDocuments 
{
    static testMethod void myUnitTest() 
    {
        Test.startTest();
        Opportunity opp = Biz2CreditUtils.createOpportunity();
        Oppr_Document__c OppDoc = Biz2CreditUtils.createOppDoc(opp);
        Attachment att = Biz2CreditUtils.createAttachment(OppDoc);
        // Request 1 
        sendDocuments.sendDocuments(opp.External_ID__c, opp.Source_System__c, OppDoc.Id, OppDoc.Name, att.Body, 'txt');
        // Request 2
        sendDocuments.sendDocuments(opp.External_ID__c, '', OppDoc.Id, OppDoc.Name, att.Body, 'txt');
        // Request 3        
        sendDocuments.sendDocuments('', '', att.Id, att.Name, att.Body, 'txt');
        Test.stopTest();

    }  
     
    static testMethod void myUnitTest1() 
    {
        Test.startTest();
        Opportunity opp = new Opportunity();
        opp.Name = 'testOp1';
        opp.LeadSource = 'A001';
        opp.Campaign = Biz2CreditUtils.createCampaign();
        opp.CloseDate = System.today();
        opp.StageName = 'STATUS_RECIEVED';
        opp.External_ID__c = '';
        opp.Status__c = '';
        opp.Source_System__c = 'B2C';
        opp.Current_Processor__c = 'ABC Global System';
        insert opp;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'testOp1';
        opp1.LeadSource = 'A001';
        opp1.Campaign = Biz2CreditUtils.createCampaign();
        opp1.CloseDate = System.today();
        opp1.StageName = 'STATUS_RECIEVED';
        opp1.External_ID__c = '' + System.currentTimeMillis();
        opp1.Status__c = 'TestStatus';
        opp1.Source_System__c = 'B2C';
        opp1.Current_Processor__c = 'ABC Global System';
        insert opp1;
        
        opp1.Status__c ='status';
        update opp1;

        Oppr_Document__c oppDoc = new Oppr_Document__c();
        oppDoc.Document_Name__c = 'TestName';
        oppDoc.Additional_Notes__c = 'testDoc';
        oppDoc.Opportunity__c = opp.Id;
        insert oppDoc;        
                
        Oppr_Document__c oppDoc1 = new Oppr_Document__c();
        oppDoc1.Document_Name__c = 'STATUS_RECIEVED';
        oppDoc1.Additional_Notes__c = 'testDoc';
        oppDoc1.Opportunity__c = opp1.Id;
        insert oppDoc1;
        
        oppDoc1.Document_Name__c = 'test1';
        update oppDoc1;        
        
        Attachment att = new Attachment();
        att.Body = Blob.valueOf('This is Test.');
        att.Name = String.valueOf('STATUS_RECIEVED.txt');
        att.ParentId = oppDoc.Id;
        insert att;      
        
        // Request 1 
        sendDocuments.sendDocuments(opp1.External_ID__c, opp1.Source_System__c, OppDoc1.Id, OppDoc1.Name, att.Body, 'txt');
        // Request 2
        sendDocuments.sendDocuments(opp1.External_ID__c, '', OppDoc1.Id, OppDoc1.Name, att.Body, 'txt');  
        
        //  SendDocuments.returnOppDoc(oppdoc,'STATUS_RECIEVED');
        //  SendDocuments.returnOppDoc(oppdoc,null); 
        Test.stopTest();
       
    }  
}