Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Partner_Campaign_Team__c</fullName>
        <label>Partner Campaign Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <inlineHelpText>How the partner is compensated for leads or funded deals.</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pay-Per-Funding</fullName>
                </value>
                <value>
                    <fullName>Pay-Per-Lead</fullName>
                </value>
                <value>
                    <fullName>No Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestCampaignMemberTgrHandler.cls
@isTest
public class TestCampaignMemberTgrHandler{
   
   public static testMethod void  populatLeadInfoTest()
   {
       Campaign cTest=new Campaign(name='Test Campagin',type='Internet',Payment_Type__c='Pay-Per-Lead'
           ,Partner_Campaign_Team__c='testData');
       insert cTest;
       
       Lead lTest=new Lead(Status='Calling - No Contact Made',LeadSource='Radio',Company='test company',Phone='415789415',Lastname='lastname'
                          );
       insert lTest;
       
       CampaignMember newMember = new CampaignMember (campaignid=cTest.id, leadid=lTest.id);
       insert newMember;
   }
}