Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Partner_Campaign_Team__c</fullName>
        <label>Partner Campaign Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DMSDocsFirstRoundComplete__c</fullName>
        <label>DMS Docs First Round Complete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tiger_Team_1_Counter__c</fullName>
        <label>Tiger Team 1 Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tiger_Team_2_Counter__c</fullName>
        <label>Tiger Team 2 Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tiger_Team_3_Counter__c</fullName>
        <label>Tiger Team 3 Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partners</fullName>
        <active>true</active>
        <businessProcess>Partner Registration Process</businessProcess>
        <label>Partners</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_1_Counter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 1 Counter</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_2_Counter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 2 Counter</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Team_3_Counter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Number__c</fullName>
        <label>Partner Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tiger Team 3 Counter</label>
</CustomObject>

Rapid Prd/src/objects/Tiger_Teams__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tiger_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BA Exclusion</label>
    <nameField>
        <displayFormat>U{000000}</displayFormat>
        <label>TT Exclusion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA Exclusions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/partnerAutoIncrementUpdatetest.cls
@isTest
public class partnerAutoIncrementUpdatetest{
    @testSetup
    public static void setup(){
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
        LastName = 'last',
        Email = 'puser000@amamama.com',
        Username = 'puser000@amamama.com' + System.currentTimeMillis(),
        CompanyName = 'TEST',
        Title = 'title',
        Alias = 'alias',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        isactive =  true
        );
        insert u;
        
        Tiger_Teams__c tt = new Tiger_Teams__c();
        tt.User__c = u.id;
        insert tt;
        
        
        
        Lead lTemp2= new Lead();
        lTemp2.Company ='partner2Lead';
        lTemp2.Email='Test@test.com';
        lTemp2.FirstName='test';
        lTemp2.LastName='lastname';  
        insert lTemp2;
        System.debug('lTemp2>>>>'+lTemp2);
        
        Tiger_Team_1_Counter__c objTeam1 = new Tiger_Team_1_Counter__c();
        objTeam1.Name = 'Tiger Team 1 Counter';
        objTeam1.Partner_Number__c = 1;
        insert objTeam1;
        
        Tiger_Team_2_Counter__c objTeam2 = new Tiger_Team_2_Counter__c();
        objTeam2.Name = 'Tiger Team 2 Counter';
        objTeam2.Partner_Number__c = 1;
        insert objTeam2;
        
        Tiger_Team_3_Counter__c objTeam3 = new Tiger_Team_3_Counter__c();
        objTeam3.Name = 'Tiger Team 3 Counter';
        objTeam3.Partner_Number__c = 1;
        insert objTeam3;
        
        Campaign camp = new Campaign();
        camp.Name = 'Green Tree Funding';
        camp.type = 'Partners';
        camp.IsActive = true;
        camp.Partner_Campaign_Team__c = 'T1';
        insert camp;
    }
    
    @isTest
    public static void partnerAutoIncrementUpdatetest1()
    { 
        /*
        Tiger_Team_1_Counter__c objTeam1 = new Tiger_Team_1_Counter__c();
        objTeam1.Name = 'Tiger Team 1 Counter';
        objTeam1.Partner_Number__c = 1;
        insert objTeam1;
        */
        /*
        Campaign camp = new Campaign();
        camp.Name = 'Green Tree Funding';
        camp.type = 'Partners';
        camp.IsActive = true;
        camp.Partner_Campaign_Team__c = 'T1';
        insert camp;
        */
        Campaign objCampaign = [select id from campaign];
        
        Lead objLead = [select id from lead];

        CampaignMember newMember = new CampaignMember (campaignid=objCampaign.id, leadid=objLead.id,status='Completed');
        insert newMember;
        
        objLead.DMSDocsFirstRoundComplete__c = System.today();
        update objLead;
        System.debug('partnerAutoIncrementUpdatetest1>>>>objLead>>>'+objLead);
        
    }
    
    @isTest
    public static void partnerAutoIncrementUpdatetest2()
    { 
        /*
        Tiger_Team_2_Counter__c objTeam2 = new Tiger_Team_2_Counter__c();
        objTeam2.Name = 'Tiger Team 2 Counter';
        objTeam2.Partner_Number__c = 1;
        insert objTeam2;
        
        Campaign camp = new Campaign();
        camp.Name = 'Green Tree Funding';
        camp.type = 'Partners';
        camp.IsActive = true;
        camp.Partner_Campaign_Team__c = 'T2';
        insert camp;
        */
        Campaign objCampaign = [select id from campaign];
        objCampaign.Partner_Campaign_Team__c = 'T2';
        
        Lead objLead = [select id from lead]; 
        
        CampaignMember newMember = new CampaignMember (campaignid=objCampaign.id, leadid=objLead.id,status='Completed');
        insert newMember;
        
        objLead.DMSDocsFirstRoundComplete__c = System.today();
        update objLead;
        System.debug('partnerAutoIncrementUpdatetest2>>>>objLead>>>'+objLead);
    }
    
    

    @isTest
    public static void partnerAutoIncrementUpdatetest3()
    { 
        /*
        Tiger_Team_3_Counter__c objTeam3 = new Tiger_Team_3_Counter__c();
        objTeam3.Name = 'Tiger Team 3 Counter';
        objTeam3.Partner_Number__c = 1;
        insert objTeam3;
        
        Campaign camp = new Campaign();
        camp.Name = 'Green Tree Funding';
        camp.type = 'Partners';
        camp.IsActive = true;
        camp.Partner_Campaign_Team__c = 'T3';
        insert camp;
        */
        Campaign objCampaign = [select id from campaign];
        objCampaign.Partner_Campaign_Team__c = 'T3';
        update objCampaign;
        
        Lead objLead = [select id from lead];   

        CampaignMember newMember = new CampaignMember (campaignid=objCampaign.id, leadid=objLead.id,status='Completed');
        insert newMember;
            
        objLead.DMSDocsFirstRoundComplete__c = System.today();
        update objLead;
        System.debug('partnerAutoIncrementUpdatetest3>>>>objLead>>>'+objLead);
    }
}