Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Green_Tree_Oppy_Extension__c.object
<CustomObject>
    <description>This object has been created to capture the required field details for Green Tree Opportunity and is a related child record of opportunity used only in the case of opportunity records having record type as -Green Tree.</description>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Green_Tree</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Green Tree Oppy Extension</label>
    <nameField>
        <displayFormat>G{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Green Tree Oppy Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Renewal_Funded_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Funded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestGTOppyExtnTrgHandler.cls
@isTest

private class TestGTOppyExtnTrgHandler {
    static testmethod void initialCommissionAmtTest() {
        Test.startTest();
        
        Campaign campTemp = new Campaign(Name = 'Green Tree Funding', IsActive = True, Status = 'Sent');
            insert campTemp;
        
        Opportunity oppt1 = new Opportunity(Name ='Test GTF1',
                            StageName = 'Customer Won',
                            Amount = 10000,
                            CloseDate = System.today()  ,
                            LeadSource = 'Radio' ,
                            CampaignId =  campTemp.Id , 
                            Renewal_Funded_Amount__c =  1000
                            );
                            
        insert oppt1;
        
                            
        Opportunity oppt2 = new Opportunity(Name ='Test GTF2',
                            StageName = 'Customer Won',
                            Amount = 10000,
                            CloseDate = System.today()  ,
                            LeadSource = 'Radio' ,
                            CampaignId =  campTemp.Id , 
                            Renewal_Funded_Amount__c =  1000
                            ); 
                            
        insert oppt2;
                            
        Opportunity oppt3 = new Opportunity(Name ='Test GTF3',
                            StageName = 'Customer Won',
                            Amount = 10000,
                            CloseDate = System.today()  ,
                            LeadSource = 'Radio' ,
                            CampaignId =  campTemp.Id , 
                            Renewal_Funded_Amount__c =  1000
                            );  

        insert oppt3;  
        
        Opportunity oppt4 = new Opportunity(Name ='Test GTF4',
                            StageName = 'Customer Won',
                            Amount = 10000,
                            CloseDate = System.today()  ,
                            LeadSource = 'Radio' ,
                            CampaignId =  campTemp.Id , 
                            Renewal_Funded_Amount__c =  1000
                            );  

        insert oppt4;         
                         
        Green_Tree_Oppy_Extension__c gtoppExtnTemp1 = new Green_Tree_Oppy_Extension__c(Amount_Sold__c = 14000 , 
                                                        Amount__c = 1000, Opportunity__c = oppt1.id);
                                                        
        insert gtoppExtnTemp1;
        
        gtoppExtnTemp1.Amount_Sold__c = 15000 ;
        
        Update gtoppExtnTemp1;
                                                        
        Green_Tree_Oppy_Extension__c gtoppExtnTemp2 = new Green_Tree_Oppy_Extension__c(Amount_Sold__c = 14000 , 
                                                        Amount__c = 1000, Opportunity__c = oppt2.id);
                                                        
        insert gtoppExtnTemp2;
        
        gtoppExtnTemp2.Amount_Sold__c = 15000 ;
        
        Update gtoppExtnTemp2;
                                                             
        Green_Tree_Oppy_Extension__c gtoppExtnTemp3 = new Green_Tree_Oppy_Extension__c(Amount_Sold__c = 14000 , 
                                                        Amount__c = 1000, Opportunity__c = oppt3.id);   
                                                        
        insert gtoppExtnTemp3;
        
        gtoppExtnTemp3.Amount_Sold__c = 15000 ;
        
        Update gtoppExtnTemp3;
        
        Green_Tree_Oppy_Extension__c gtoppExtnTemp4 = new Green_Tree_Oppy_Extension__c(Amount_Sold__c = 14000 , 
                                                        Amount__c = 1000, Opportunity__c = oppt4.id);   
                                                        
        insert gtoppExtnTemp4;
        
        gtoppExtnTemp3.Amount_Sold__c = 16000 ;
        
        Update gtoppExtnTemp4;   
                
        Test.stopTest();
    }
}