Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Sales_Team_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member #6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns6</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Calculate_Due_Dates__c</fullName>
        <label>Calculate Due Dates</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Re_Decision_Date__c</fullName>
        <description>Decision for this deal has been changed.</description>
        <label>Re-Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submit_to_Sales_Assistant__c</fullName>
        <label>Submit to Sales Assistant</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Underwriting_Approval__c</fullName>
        <label>Underwriting Decision</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved by Credit Committee</fullName>
                </value>
                <value>
                    <fullName>Approved by Credit Committee with conditions</fullName>
                </value>
                <value>
                    <fullName>Auto Approved</fullName>
                </value>
                <value>
                    <fullName>Auto Declined</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Declined by Credit Committee</fullName>
                </value>
                <value>
                    <fullName>Declined - Pending Management Review</fullName>
                </value>
                <value>
                    <fullName>Pending Management Review</fullName>
                </value>
                <value>
                    <fullName>Pending management review returned to u/w</fullName>
                </value>
                <value>
                    <fullName>Rescinded by Processing</fullName>
                </value>
                <value>
                    <fullName>Rescinded by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Comp. Pay Off too High - Reconsider Later</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Will Not Reconsider</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Will Reconsider in the Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestMasterOpportunityTrigger5.cls
@isTest

private class TestMasterOpportunityTrigger5
{  
    static testMethod voId unitTestOpportunityCampaign()
    {
        Test.startTest(); 
        try{ 
            testOppDates();
        }
        catch(Exception e)
        {
        }
        Test.stopTest();
    }
    static voId testOppDates() 
    {        
        // DS-CONAM CALC.ApexTesting();        
        User u = [SELECT 
                        Id 
                    FROM 
                        User 
                    WHERE 
                        isActive = true 
                    AND 
                        profile.Name='System administrator' LIMIT 1];

        Campaign camp = new campaign();
        camp.name = 'test';
        camp.Sales_Team_Member_1__c = u.Id;
        camp.Sales_Team_Member_2__c = u.Id;
        camp.Sales_Team_Member_3__c = u.Id;
        camp.Sales_Team_Member_4__c = u.Id;
        camp.Sales_Team_Member_5__c = u.Id;
        camp.Sales_Team_Member_6__c = u.Id;
        insert camp;
        
        Campaign campOther = new campaign();
        campOther.name = 'campOther';
        campOther.Sales_Team_Member_1__c = u.Id;
        campOther.Sales_Team_Member_2__c = u.Id;
        campOther.Sales_Team_Member_3__c = u.Id;
        campOther.Sales_Team_Member_4__c = u.Id;
        campOther.Sales_Team_Member_5__c = u.Id;
        campOther.Sales_Team_Member_6__c = u.Id;
       
        insert campOther;
        
        Opportunity opp = new Opportunity(name='Test Opportunity 12345',closedate = system.today(), 
                                            stagename = 'Closed Deal', 
                                            calculate_due_dates__c = system.now());
        opp.campaignId = camp.Id;
        opp.Decision_Date__c = system.now(); 
        opp.submit_to_sales_assistant__c = system.now();
        opp.re_decision_date__c = system.now(); 
        insert opp;
        
        opp.Renewal__c = true;
        update opp;
        
        opp.Underwriting_Approval__c = 'Declined' ;
        update opp;
        
        opp.Underwriting_Approval__c = 'Auto Declined';
        update opp;
                
        opp.campaignId=campOther.Id;
        update opp;  
    }
}