Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Default_Opportunity_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CampaignsAssociated</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Percent_Paid_Off__c</fullName>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Of_Location__c</fullName>
        <label>State Of Location</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit_to_UW_Processing__c</fullName>
        <label>Submit to UW &amp; Processing</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/TestUpdateOpportunityOwner.cls
@isTest
private class TestUpdateOpportunityOwner  {

    static testMethod void myUnitTest() { 
       
       User u=[select id from user where profile.name ='System Administrator' and isactive=true Limit 1];
    
        CALC.ApexTesting();   
        Campaign cTest=new Campaign(name='Test Campagin',type='Internet',default_opportunity_owner__C=u.id);
        insert cTest;
         
         
      Profile p = [SELECT Id FROM Profile WHERE Name='system administrator']; 
      User uNew = new User(Alias = 'standt', Email='standarduser@ra.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = p.Id, 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@ra.com');

      System.runAs(uNew ) {

      
        Opportunity opp=new Opportunity();
        opp.name='testopp';
        opp.StageName = 'Open';
        opp.CloseDate = Date.today();
        opp.Submit_to_UW_Processing__c=System.now();
        opp.Product__c='Loan';
        opp.Percent_Paid_Off__c=55;
        opp.State_Of_Location__c='CT';    
        opp.CampaignId=ctest.id;
        insert opp;
      }
        
        
          

       

    }
}