Rapid Prd/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Additional_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Owner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>User Type must be Standard SalesForce.</errorMessage>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <filterItems>
                <field>User.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.OwnerId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Funded_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Funded Deal</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Most Recent Funded Deal</relationshipLabel>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <formula>Text( ISO_Account__r.Partner_Channel__c )</formula>
        <label>Partner Channel</label>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Deal_Signed_Email_Notification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <label>Partner Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Email__c</fullName>
        <label>Salesforce User Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Deal Signed Email Notification</label>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <formula>Text(Account.Partner_Channel__c)</formula>
        <label>Partner Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signed_Contract_Received__c</fullName>
        <label>Signed Contract Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UCC_Date__c</fullName>
        <label>UCC Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UCC_Filing_Reason__c</fullName>
        <label>UCC Filing Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Credit Committee</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Pay-off</fullName>
                </value>
                <value>
                    <fullName>Renewal Decline</fullName>
                </value>
                <value>
                    <fullName>Risk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UCC_Filing__c</fullName>
        <label>UCC Filing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full UCC-1</fullName>
                </value>
                <value>
                    <fullName>Notification UCC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/OpportunityTriggerHandlerPart2.cls
public class OpportunityTriggerHandlerPart2
{
    public static void auSetUCCFiling(Map<id,Opportunity> oldOMap,Map<id,Opportunity> newOMap)
    {
        Set<id> iSet=new Set<id>();
        List<Opportunity> oppList=new List<Opportunity>();
                
        for(id iTemp : newOMap.keyset())
        {
            if((newOMap.get(iTemp).StageName!=oldOMap.get(iTemp).StageName) && (newOMap.get(iTemp).StageName=='Closed Won'))
            {
                if(newOMap.get(iTemp).Product__c!=null)
                {
                    if((String.valueOf(newOMap.get(iTemp).Product__c).indexOf('Loan')!=-1) && (newOMap.get(iTemp).Renewal__c==false))
                        iSet.add(iTemp);
                }             
            }
        }
        if(iSet.size()>0)
        {
            for(Opportunity oppTemp : [Select id, UCC_Filing__c, UCC_Filing_Reason__c,UCC_Date__c from opportunity where id in : iSet])
            {
                oppTemp.UCC_Filing__c='Full UCC-1';
                oppTemp.UCC_Filing_Reason__c='Loan';
                oppTemp.UCC_Date__c=System.today();
                oppList.add(oppTemp);
            }
            
            if(oppList.size()>0)
            {
                try
                {
                    Database.update(oppList,false);
                }
                catch(Exception e)
                {
                    System.debug('An exception has occurred - '+e.getMessage()+'-'+e.getLinenumber());
                }
            }
        }
    }
    
    public static void sendEmailNotifcationOnSignedDeal(Map<id,Opportunity> oldOMap,Map<id,Opportunity> newOMap)
    {
        //send email notification to campaign owner(s) when a deal is signed
        
        Map<Id,Opportunity> oppMap=new Map<Id,Opportunity>(); //k=>Opp.Id, V=> Opp
        Map<String,List<String>> notificationMap=new Map<String,List<String>>();
        Map<Id,id> campaignIdMap=new Map<Id,id>();
        Set<id> userId=new Set<id>();
        

        for(Deal_Signed_Email_Notification__c dTemp : [select Partner_Channel__c,Salesforce_User_Email__c from Deal_Signed_Email_Notification__c ])
        {
            if(notificationMap.containsKey(dTemp.Partner_Channel__c.toLowercase()))
                notificationMap.get(dTemp.Partner_Channel__c.toLowercase()).add(dTemp.Salesforce_User_Email__c );
            
            notificationMap.put(dTemp.Partner_Channel__c.toLowercase(),new List<String>{dTemp.Salesforce_User_Email__c });
        }

        for(Id iTemp : newOMap.keyset())
        {
            if((newOMap.get(iTemp).Signed_Contract_Received__c!=oldOmap.get(iTemp).Signed_Contract_Received__c) && newOMap.get(iTemp).Signed_Contract_Received__c!=null)
            {
                oppMap.put(iTemp,newOMap.get(iTemp));
                campaignIdMap.put(newOMap.get(iTemp).campaignID,iTemp);
                userId.add(newOMap.get(iTemp).ownerId);
            }
        }
        
        Map<id,Campaign> allCampaign=new Map<id, Campaign>([Select name,Additional_Owner__c,Additional_Owner__r.email,type from campaign where id in :campaignIdMap.keyset() and type='Partners']);
        System.debug(allCampaign);
        
        if(oppMap.size()>0)
        {
            Map<Id,User> userMap=new Map<Id,User>([Select id,name from user where id in :userId]);
            List<Messaging.SingleEmailMessage> msgList=new List<Messaging.SingleEmailMessage>();
            
            List<EmailTemplate> eId=[Select id,HtmlValue,subject from emailtemplate where IsActive=true and developername='Signed_Contract_Notification_for_BD_team'];
            if(eId!=null && eId.size()>0)
            {
                for(Id iTemp : oppMap.keyset())
                {
                    Opportunity opp=oppMap.get(iTemp);
                    System.debug(opp.Partner_Channel__c);
                    List<String> emailAddress=new List<String>();
                    
                    if(opp.Partner_Channel__c!=null)
                    {
                        if(notificationMap.get(opp.Partner_Channel__c.toLowerCase())!=null)
                        {
                            emailAddress=notificationMap.get(opp.Partner_Channel__c.toLowerCase());
                            if(allCampaign.containsKey(opp.campaignId))
                            {
                                System.debug(opp.campaignId);
                                System.debug(allCampaign.get(opp.campaignId));
                                System.debug(allCampaign.get(opp.campaignId).Additional_Owner__c);
                                System.debug(emailAddress);
                                
                                if(allCampaign.get(opp.campaignId).Additional_Owner__c!=null)
                                    emailAddress.add(allCampaign.get(opp.campaignId).Additional_Owner__c);
                            }
                        }
                        
                        if(emailAddress.size()>0)
                        {
                            String emailBody=eId.get(0).HtmlValue.replace('contractDate', opp.Signed_Contract_Received__c.format())
                                                                  .replace('opp.Name',opp.Name)
                                                                  .replace('opp.Amount',String.valueOf(opp.amount));
                            if(allCampaign.get(opp.campaignID)!=null)
                            {
                                emailBody=emailBody.replace('opp.LeadSource',opp.leadsource)
                                                    .replace('opp.Campaign',allCampaign.get(opp.campaignID).name)
                                                    .replace('opp.Renewal',opp.renewal__c==true?'Yes':'No')
                                                    .replace('Pay_Back_Amount__c',String.valueOf(opp.Pay_Back_Amount__c))
                                                    .replace('Salesrep',userMap.get(opp.ownerID).name)
                                                    .replace('Percent_Payback__c',String.valueOf(opp.Percent_Payback__c))
                                                    .replace(']]>','');
                                
                                Messaging.SingleEmailMessage msg=new Messaging.SingleEmailMessage();
                                msg.setSubject(eId.get(0).subject.replace('{!Opportunity.Name}',opp.Name));
                                msg.setToAddresses(emailAddress);
                                msg.setWhatId(iTemp);
                                msg.setHtmlBody(emailBody);
                                msg.setSaveAsActivity(false);
                                msgList.add(msg);
                            }
                        }
                    }   
                }
            }
            
            if(msgList.size()>0)
                Messaging.sendEmail(msgList);
        }       
    }

    public static void updateCampaignWithLatestFunded(Map<id,Opportunity> oldOMap,Map<id,Opportunity> newOMap)
    {
        Map<Id,Id> campOppMap=new Map<Id,Id>();
        List<Campaign> campList=new List<Campaign>();
        
        for(id iTemp : newOMap.keyset())
        {
            if((newOMap.get(iTemp).StageName!=oldOMap.get(iTemp).StageName) && (newOMap.get(iTemp).StageName=='Closed Won'))
            {
                //populate campaign with the latest funded deal information
                if(newOMap.get(iTemp).CampaignId!=null)
                {
                    campOppMap.put(newOMap.get(iTemp).CampaignId,iTemp);
                }   
            }
        }
        
        if(campOppMap.size()>0)
        {
            for(Campaign cTemp : [Select id,Most_Recent_Funded_Deal__c from Campaign where id in : campOppMap.keyset()])
            {
                if(campOppMap.containsKey(cTemp.id))
                {
                    cTemp.Most_Recent_Funded_Deal__c=  campOppMap.get(cTemp.id);
                    campList.add(cTemp);
                }
            }
            
            if(campList.size()>0)
                update campList;
        }
    }
}