Rapid Prd/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactID__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Does_the_Merchant__c</fullName>
        <label>Does the Merchant</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnershipPercentage__c</fullName>
        <label>Ownership Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Principal_2_First_Name__c</fullName>
        <label>Principal 2 First Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Mobile__c</fullName>
        <label>Principal 2 Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Principal_Home_Phone__c</fullName>
        <label>Principal Home Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant_2_FICO__c</fullName>
        <label>Applicant #2 FICO</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRR</label>
        <referenceTo>Credit_Related_Reporting__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactID__c</fullName>
        <formula>Contact__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Does_the_Merchant__c</fullName>
        <label>Does the Merchant Own Their Home</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual_Bankruptcies__c</fullName>
        <label>Bankruptcy Filings In The Last Year:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Judgements_Open__c</fullName>
        <label>Judgements Open</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$5k-$15k</fullName>
                </value>
                <value>
                    <fullName>$15-$30k</fullName>
                </value>
                <value>
                    <fullName>$30k-$50k</fullName>
                </value>
                <value>
                    <fullName>$50k and up</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manual_Applicant_1_FICO_Score__c</fullName>
        <label>Manual Applicant 1 FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manual_Applicant_2_FICO_Score__c</fullName>
        <label>Manual Applicant 2 FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mortgage_Delinquent__c</fullName>
        <label>Mortgage Delinquent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30 DPD</fullName>
                </value>
                <value>
                    <fullName>60 DPD</fullName>
                </value>
                <value>
                    <fullName>90 DPD</fullName>
                </value>
                <value>
                    <fullName>120 DPD</fullName>
                </value>
                <value>
                    <fullName>150 DPD</fullName>
                </value>
                <value>
                    <fullName>180 DPD</fullName>
                </value>
                <value>
                    <fullName>FORECLOSURE &lt; 1 YEAR</fullName>
                </value>
                <value>
                    <fullName>FORECLOSURE STARTED</fullName>
                </value>
                <value>
                    <fullName>MODIFICATION AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_FICO__c</fullName>
        <label>Previous Applicant #1 FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Opportunity record is a clone from a previous opportunity, the link to that original opportunity will be here.  No one has to fill this in manually.</inlineHelpText>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Liens_Open__c</fullName>
        <label>Tax Liens Open</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>$1-$25k</fullName>
                </value>
                <value>
                    <fullName>$25k-$50k</fullName>
                </value>
                <value>
                    <fullName>$50k-75k</fullName>
                </value>
                <value>
                    <fullName>$75k and Above</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ApplicantCredit_Ctrl.cls
/**
*********************************************************************************************************************
* Module Name   :   ApplicantCredit_Ctrl 
* Description   :   This class is a controller for ApplicantCreditPage and is used to displays the Applicant and Credit information 
                    for an opportunity alongwith the 2 principal contact of the opportunity if present.
* Organization  :   ConAm Technologies Pvt. Ltd.

* Revision History:-
* Version  Date           Author           WO#         Description of Action
* 1.0      08/06/2015     MKConAm                      Modify
*   
*******************************************************************************************************************
**/
/*
@Name               : ApplicantCredit_Ctrl 
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        :  
@Revision History   : Uses of Field confirmed information_from_qc__c Commented/Removed By MK Conam 2 Dec 2015
*/
public class ApplicantCredit_Ctrl {

    public Opportunity oppRecord {get;set;}
    public Contact conRecord {get;set;}
    public Contact pricipal1Record {get;set;}
    public Contact pricipal2Record {get;set;}
    public Decimal applicant1FICO { get;private set;}
    public Decimal applicant1PrevFICO { get;private set;}
    public String creditBureauSummary { get;private set;}
   // public String equityInHome {get;private set;}

    public ApplicantCredit_Ctrl()
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');
        conRecord = new Contact();

        if (oppId != null && oppId.trim() != '') {
            List <Opportunity> oppList = [SELECT
                                                Id, AccountId, Manual_Applicant_1_FICO_Score__c,
                                                Mortgage_Delinquent__c, Tax_Liens_Open__c, Judgements_Open__c, Previous_FICO__c,
                                                Individual_Bankruptcies__c, Does_the_Merchant__c, 
                                                CRR__c, Contact__c, Applicant_2_FICO__c, Previous_Opportunity__r.Applicant_2_FICO__c, 
                                                Contact__r.Name, ContactID__c, Manual_Applicant_2_FICO_Score__c
                                            FROM
                                                Opportunity
                                            WHERE
                                                Id = : oppId LIMIT 1];

            if (!oppList.isEmpty())
            {
                oppRecord = oppList.get(0);
                Map <ID, String> contactRoleMap = new Map <ID, String> ();
                Set <String> roleSet = new Set <String> ();

                List <OpportunityContactRole> oppRoleList = [SELECT
                                                                    ContactId, Role
                                                                FROM
                                                                    OpportunityContactRole
                                                                WHERE
                                                                    OpportunityId = : oppRecord.Id
                                                                AND
                                                                    Contact.IsDeleted = false
                                                                AND
                                                                    (Role = 'Principal 1'
                                                                or 
                                                                    Role = 'Principal 2')];


                for (OpportunityContactRole oppRole: oppRoleList) 
                {
                    if ((!roleSet.contains(oppRole.Role)) && (!contactRoleMap.containsKey(oppRole.ContactId))) {
                        contactRoleMap.put(oppRole.ContactId, oppRole.Role);
                        roleSet.add(oppRole.Role);
                    }
                }

                if (!contactRoleMap.IsEmpty())
                {
                    List <Contact> contactList = [SELECT
                                                            c.Id, c.Name, c.ContactID__c, c.AccountId,
                                                            c.Principal_Home_Phone__c,
                                                            c.Principal_2_Mobile__c, c.OwnershipPercentage__c,
                                                            c.MobilePhone, c.MailingStreet,
                                                            c.MailingState, c.MailingPostalCode,
                                                            c.MailingCity, c.Fax, c.Email, c.Date_of_Birth__c
                                                    FROM
                                                            Contact c
                                                    WHERE
                                                            Id
                                                    IN      : contactRoleMap.keySet()];
                    if (!contactList.isEmpty())
                    {
                        for (Contact cTemp: contactList) 
                        {
                            if (contactRoleMap.get(cTemp.Id) == 'Principal 1') 
                            {
                                pricipal1Record = cTemp;
                            } 
                            else if (contactRoleMap.get(cTemp.Id) == 'Principal 2')
                            {
                                pricipal2Record = cTemp;
                            }
                        }
                    }
                }

                applicant1FICO = FormulaFieldUtility.ccApplicant1FICO;
                applicant1PrevFICO = FormulaFieldUtility.applicant1PrevFICO;
                creditBureauSummary = FormulaFieldUtility.creditBureauSummary;
               // equityInHome = FormulaFieldUtility.equityInHome;
            }
        } 
        else
         {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
        }
    }



    public PageReference doSave() {
        try {
            /* if(conRecord != null && conRecord.AccountId == null) {
                    conRecord.AccountId = oppRecord.AccountId;  
                }
                System.debug('>>>>' + conRecord.Principal_2_First_Name__c);
                upsert conRecord;  
                
                if(conRecord.Id != null && oppRecord.Contact__c == null) {
                    oppRecord.Contact__c = conRecord.Id;   
                }*/

            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'Applicant & Credit Information Saved Successfully!'));
            } 
            catch (Exception e) 
            {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            }
        return null;
    }

}