Rapid Prd/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OwnershipPercentage__c</fullName>
        <label>Ownership Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Principal_1_City__c</fullName>
        <label>Principal 1 City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_State__c</fullName>
        <label>Principal 1 State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_1_Street_Address__c</fullName>
        <label>Principal 1 Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_1_Zip__c</fullName>
        <label>Principal 1 Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_City__c</fullName>
        <label>Principal 2 City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_Email__c</fullName>
        <label>Principal 2 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Principal_2_First_Name__c</fullName>
        <label>Principal 2 First Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Last_Name__c</fullName>
        <label>Principal 2 Last Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Mobile__c</fullName>
        <label>Principal 2 Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Principal_2_Percent_Ownership__c</fullName>
        <label>Principal 2 Percent Ownership</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Principal_2_Phone__c</fullName>
        <label>Principal 2 Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Principal_2_State__c</fullName>
        <label>Principal 2 State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_2_Street_Address__c</fullName>
        <label>Principal 2 Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_2_Zip__c</fullName>
        <label>Principal 2 Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_Home_Phone__c</fullName>
        <label>Principal Home Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Merchant__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_length_of_time_with_processor__c</fullName>
        <label>Confirm length of time with processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 to 3 months</fullName>
                </value>
                <value>
                    <fullName>4 to 6 months</fullName>
                </value>
                <value>
                    <fullName>7 to 12 months</fullName>
                </value>
                <value>
                    <fullName>&gt; 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Merchants</relationshipLabel>
        <relationshipName>Merchants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Balance_With_Competitor_RA__c</fullName>
        <label>Current Balance With Competitor/RA</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Monthly_Sales_of_the_Business__c</fullName>
        <label>Gross Monthly Sales of the Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$2,500 to $10,000</fullName>
                </value>
                <value>
                    <fullName>$10,000 to $25,000</fullName>
                </value>
                <value>
                    <fullName>$25,001 to $50,000</fullName>
                </value>
                <value>
                    <fullName>$50,001 to $100,000</fullName>
                </value>
                <value>
                    <fullName>&gt; $100,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_businesses_are_nearby__c</fullName>
        <label>What businesses are nearby?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>What_do_you_plan_to_use_the_money_for__c</fullName>
        <label>What do you plan to use the money for?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>What_hours_are_you_open__c</fullName>
        <label>What hours are you open?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>What_is_your_busy_season__c</fullName>
        <label>What is your busy season?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spring</fullName>
                </value>
                <value>
                    <fullName>Summer</fullName>
                </value>
                <value>
                    <fullName>Fall</fullName>
                </value>
                <value>
                    <fullName>Winter</fullName>
                </value>
                <value>
                    <fullName>Consistent year round</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_your_home_phone_number__c</fullName>
        <label>What is your home phone number?</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>What_is_your_mobile_phone_number__c</fullName>
        <label>What is your mobile phone number?</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>What_type_of_Business_Location__c</fullName>
        <label>What type of Business Location?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mall</fullName>
                </value>
                <value>
                    <fullName>Office Space</fullName>
                </value>
                <value>
                    <fullName>Shopping Center</fullName>
                </value>
                <value>
                    <fullName>Stand Alone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_type_of_Business_is_it__c</fullName>
        <label>What type of Business is it?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Antiques/Collectibles</fullName>
                </value>
                <value>
                    <fullName>Appliance Stores</fullName>
                </value>
                <value>
                    <fullName>Arrangements</fullName>
                </value>
                <value>
                    <fullName>Art Galleries</fullName>
                </value>
                <value>
                    <fullName>Audio Equipment</fullName>
                </value>
                <value>
                    <fullName>Automobile Dealerships New/Used</fullName>
                </value>
                <value>
                    <fullName>Automotive - Body Repair, Collision, Painting</fullName>
                </value>
                <value>
                    <fullName>Automotive - Brake and Muffler</fullName>
                </value>
                <value>
                    <fullName>Automotive - General Repair, Truck, RV</fullName>
                </value>
                <value>
                    <fullName>Automotive - Parts, Accessories</fullName>
                </value>
                <value>
                    <fullName>Automotive - Quick Sevice, Lube, Tune-Up</fullName>
                </value>
                <value>
                    <fullName>Automotive - Tire, Glass</fullName>
                </value>
                <value>
                    <fullName>Automotive - Towing &amp; Emergency Road Service</fullName>
                </value>
                <value>
                    <fullName>Automotive - Transmission</fullName>
                </value>
                <value>
                    <fullName>Bar</fullName>
                </value>
                <value>
                    <fullName>Barber Shop</fullName>
                </value>
                <value>
                    <fullName>Billing Services</fullName>
                </value>
                <value>
                    <fullName>Boating/Marina</fullName>
                </value>
                <value>
                    <fullName>Book and Stationary</fullName>
                </value>
                <value>
                    <fullName>Bowling</fullName>
                </value>
                <value>
                    <fullName>Bridal Shop</fullName>
                </value>
                <value>
                    <fullName>Car Alarm Supplier</fullName>
                </value>
                <value>
                    <fullName>Carpet Store</fullName>
                </value>
                <value>
                    <fullName>Car Wash</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Check Cashing Companies</fullName>
                </value>
                <value>
                    <fullName>Clothing &amp; Apparel</fullName>
                </value>
                <value>
                    <fullName>Clothing - Shoe Store</fullName>
                </value>
                <value>
                    <fullName>Coffee Shop</fullName>
                </value>
                <value>
                    <fullName>Comedy Clubs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>When_did_you_purchase_start_the_business__c</fullName>
        <label>When did you purchase/start the business</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>When_does_your_lease_expire__c</fullName>
        <label>When does your lease expire?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 to 6 months</fullName>
                </value>
                <value>
                    <fullName>7 to 11 months</fullName>
                </value>
                <value>
                    <fullName>1 yr</fullName>
                </value>
                <value>
                    <fullName>2 yrs</fullName>
                </value>
                <value>
                    <fullName>3 yrs</fullName>
                </value>
                <value>
                    <fullName>4 yrs</fullName>
                </value>
                <value>
                    <fullName>5 yrs+</fullName>
                </value>
                <value>
                    <fullName>Month to Month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>When_was_business_opened__c</fullName>
        <label>When was business opened?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Will_the_business_close_for_any_reason__c</fullName>
        <label>Will the business close for any reason?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Merchant</label>
    <nameField>
        <displayFormat>Merchant-{0000}</displayFormat>
        <label>Merchant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Confirmed_wire_amount_with__c</fullName>
        <label>Confirmed wire amount with:</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interview_Additional_Comments__c</fullName>
        <label>Interview Additional Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Landlord_Address__c</fullName>
        <label>Landlord Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Landlord_Contact_Name__c</fullName>
        <label>Landlord Contact Name:</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Landlord_Interview_Complete__c</fullName>
        <description>Landlord Interview Completed Date (date and time stamp)</description>
        <label>Landlord Interview Complete</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Landlord_Phone_Number__c</fullName>
        <label>Landlord Phone Number:</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Merchant_website__c</fullName>
        <label>Merchant website?</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Notes_from_Prefunding_Call__c</fullName>
        <label>Notes from Prefunding Call</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processing_and_or_Origination_Fee_s__c</fullName>
        <label>Processing and/or Origination Fee(s):</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Landlord__c</fullName>
        <label>Type of Landlord:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Management Company</fullName>
                </value>
                <value>
                    <fullName>Private Party</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Relative/Family</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wire_Amount__c</fullName>
        <label>Wire Amount:</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/LandlordInterview_Ctrl.cls
/**
*********************************************************************************************************************
* Module Name   :   LandlordInterview_Ctrl
* Description   :   Controller for LandlordInterviewPage and is responsible capturing details from the business owner.
                    It is used for inserting / updating the Merchant Interview, Landlord Interview, Pre-Funding Call 
                    and Additional Location information regarding the Landlord
* 
*  
* Revision History:-
* Organization  : ConAm Technologies Pvt. Ltd.
* Version  Date           Author           Description of Action
* 1.0      08/07/2015     DS-CONAM         
*   
*******************************************************************************************************************
**/


public class LandlordInterview_Ctrl {

    public Opportunity oppRecord {get;set;}
    public Merchant__c objMerchant {get;set;}
    public Contact objContact {get;set;}
    public String primaryContactInfo {get;private set;}
    public String additionalContactInfo {get;private set;}

    public LandlordInterview_Ctrl() 
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');

        if (oppId != null && oppId.trim() != '')
        {
            List < Opportunity > oppList = [SELECT 
                                                    Id, Type_of_Landlord__c, Landlord_Address__c, Confirmed_wire_amount_with__c,Notes_from_Prefunding_Call__c,
                                                    Landlord_Phone_Number__c, Landlord_Contact_Name__c,
                                                    Processing_and_or_Origination_Fee_s__c, Wire_Amount__c,  
                                                    Merchant_Website__c, Interview_Additional_Comments__c, Account.Id, Contact__r.Name, Landlord_Interview_Complete__c
                                            FROM 
                                                    Opportunity
                                            WHERE 
                                                    Id = : oppId LIMIT 1];
            if (!oppList.isEmpty())
            {
                oppRecord = oppList.get(0);
            }

            List <Contact> objContacts = [SELECT FirstName, LastName, OwnershipPercentage__c, Principal_1_Street_Address__c, Principal_1_City__c,
                                                Principal_1_State__c, Principal_1_Zip__c, Principal_Home_Phone__c, MobilePhone, Fax, Email,
                                                Principal_2_First_Name__c, Principal_2_Last_Name__c, Principal_2_Street_Address__c, Principal_2_City__c,
                                                Principal_2_State__c, Principal_2_Zip__c, Principal_2_Phone__c, Principal_2_Mobile__c, Principal_2_Email__c,
                                                Principal_2_Percent_Ownership__c
                                        FROM 
                                                Contact 
                                        WHERE 
                                                AccountId = : oppRecord.Account.Id];
            if (!objContacts.isEmpty())
            {
                objContact = objContacts.get(0);
            } 
            else
            {
                objContact = new Contact();
            }

            list <Merchant__c> objMerchants = [SELECT 
                                                        Current_Balance_With_Competitor_RA__c, Gross_Monthly_Sales_of_the_Business__c,
                                                        Confirm_length_of_time_with_processor__c, Will_the_business_close_for_any_reason__c,
                                                        When_was_business_opened__c, When_does_your_lease_expire__c, What_type_of_Business_is_it__c,
                                                        When_did_you_purchase_start_the_business__c, What_type_of_Business_Location__c,
                                                        What_is_your_mobile_phone_number__c, What_is_your_busy_season__c,What_businesses_are_nearby__c, 
                                                        What_hours_are_you_open__c, What_do_you_plan_to_use_the_money_for__c,What_is_your_home_phone_number__c,
                                                        SystemModstamp, OwnerId, Opportunity__c, Name, Merchant_Interview_Phone_Number__c,
                                                        Merchant_Interview_Completed_Date__c, Is_this_business_a_franchise__c,
                                                        IsDeleted, Id, How_much_of_the_business_do_you_own__c,
                                                        How_many_square_feet_is_the_business__c, How_many_part_time_employees_do_you_have__c,
                                                        How_many_locations_for_this_business__c, How_long_have_you_used_current_processor__c,
                                                        Have_you_had_a_cash_advance_before__c,  Do_you_plan_to_sell_the_business_soon__c,
                                                        Do_you_own_any_other_businesses__c, Contact__c, Are_you_late_with_any_of_your_vendors__c,
                                                        if_other_locat_of_terminals_at_each_c__c, Comments_on_Business_Sale_Response__c,
                                                        Do_you_have_contracts_with_customers__c, Number_of_Full_Time_Employees__c,
                                                        How_much_is_the_rent_for_the_business__c, If_closing_in_the_next_year_what_period__c,
                                                        If_so_are_you_current_on_franchise_dues__c, If_so_then_what_type__c, Late_w_Vendors_Details__c,
                                                        Overall_Merchant_Interview_Assessment__c, What_is_your_current_balance__c,Additional_References__c,
                                                        What_is_your_email_address__c, What_is_your_slow_season__c, of_cc_card_terminal_at_this_location__c
                                                FROM 
                                                        Merchant__c
                                                WHERE 
                                                        Opportunity__c = : oppId];
            if (objMerchants != null && !objMerchants.isEmpty())
            {
                objMerchant = objMerchants.get(0);
                oppId = objMerchant.Opportunity__c;
            }
            else
            {
                objMerchant = new Merchant__c();
                objMerchant.Opportunity__c = OppId;
            }
            primaryContactInfo = FormulaFieldUtility.primaryContactInfo;
            additionalContactInfo = FormulaFieldUtility.additionalContactInfo;
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
        }
    }

    public PageReference doSave() 
    {
        Savepoint sp = Database.setSavepoint();
        try
        {
            if (oppRecord != null) 
                upsert oppRecord;

            if (objMerchant != null) 
                upsert objMerchant;

            if (objContact != null) 
                upsert objContact;

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'Interview Information Saved Successfully!'));
        } 
        catch (Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            Database.rollback(sp);
        }
        return null;
    }
}