Rapid Prd/src/objects/Five9Task2OppMappings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Five9Disposition__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Five9Disposition</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Five9 Call Activity to Opportunity Map</label>
</CustomObject>

Rapid Prd/src/classes/TestFive9Opportunity2Task.cls
@istest
public class TestFive9Opportunity2Task
{
    public static testMethod void unitTest()
    {
        Test.startTest();
        //DS-CONAM CALC.ApexTesting();
        Five9Task2OppMappings__c val=new Five9Task2OppMappings__c();
        val.Five9Disposition__c='Opp- No Contact – No VM Left';
        val.name='1';
        /*val.stageName='No contact Made';*/
        insert val;
        
        Account acc=TestUtils.createAccount();
        Campaign cTemp=TestUtils.createCampaign();
        Opportunity opp=TestUtils.createOpportunity(acc,cTemp);
        Task tTemp=new Task();
        tTemp.subject='Call';
        tTemp.CallDisposition='Opp- No Contact – No VM Left';
        tTemp.whatId=opp.id;
        insert tTemp;
        system.debug(opp.StageName);        
        Test.stopTest();
        
    }    
}