Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DNC_Response__c</fullName>
        <label>DNC Response</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InValid_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is to track records which have invalid numbers as per DNC once the batch is done this field can be deleted</description>
        <label>InValid Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LengthOfPhone__c</fullName>
        <formula>Len(Phone)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LengthOfPhone</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrubbed_With_DNC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scrubbed With DNC</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Limit_batch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Limit batch</label>
</CustomObject>

Rapid Prd/src/classes/BatchDNCScrubAllLead14asc.cls
public class BatchDNCScrubAllLead14asc implements DataBase.Batchable<SObject>, Database.AllowsCallouts
{   
    public DataBase.QueryLocator start(DataBase.BatchableContext bc)
    {
        String limits=String.valueOf(Limit_batch__c.getValues('BatchLeadDNC').Limit__c);
        //String phlimit=String.valueOf(Limit_batch__c.getValues('LengthOfPhone').Limit__c);
        String query='Select id, Scrubbed_With_DNC__c,phone, DNC_Response__c from Lead where isConverted=false and dnc_response__c=null  ';
        query+=' and Scrubbed_With_DNC__c=false and Phone!=null and Phone!=\'0\' and LengthOfPhone__c=14 and id!=\'00Q7000000nJtkcEAC\' ';
        query+=' and InValid_Number__C=false Order by createddate asc limit '+limits;

        return DataBase.getQueryLocator(query);
    }
    
    public void execute(DataBase.BatchableContext bc, List<Lead> scope)
    {
    try
        {
            String phoneList='';
            DNCLeadHandler dTemp =new DNCLeadHandler ();
            dTemp.eventType='Batch';
            for(Lead lTemp : scope)
            {
                if((lTemp.phone!=null)&&(lTemp.phone!=''))
                {
                    phoneList=phoneList+lTemp.phone+',';
                }
            }
             if(phoneList.length()>0)
            {
                phoneList=phoneList.subString(0,phoneList.length()-1);
                dTemp.phoneList=phoneList;
                System.enqueueJob(dtemp);
                
            }
        }
        catch(Exception e)
        {
            System.debug('An exception has occurred '+e.getMessage()+' at '+ e.getLineNumber());
        }
        
    }
    
    public void finish(DataBase.BatchableContext bc)
    {
    }
}