Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Average_dollar_amount_funded__c</fullName>
        <description>Label change from Average dollar amount funded per month? to Dollar amount funded per month 02/21/17</description>
        <label>Dollar amount funded per month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Campaign_Name_Upload__c</fullName>
        <label>Campaign Name Upload</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Agent/MLS-US</fullName>
                </value>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Banks</fullName>
                </value>
                <value>
                    <fullName>Broker/Intermediary</fullName>
                </value>
                <value>
                    <fullName>Cash Brokers</fullName>
                </value>
                <value>
                    <fullName>Commercial Real Estate</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Credit Unions</fullName>
                </value>
                <value>
                    <fullName>CUSO</fullName>
                </value>
                <value>
                    <fullName>Economic Development</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Government Contractor</fullName>
                </value>
                <value>
                    <fullName>High Quality Originator</fullName>
                </value>
                <value>
                    <fullName>High Volume Originator</fullName>
                </value>
                <value>
                    <fullName>Inventory Fianncing</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-CANADA</fullName>
                </value>
                <value>
                    <fullName>ISO/MSP-US</fullName>
                </value>
                <value>
                    <fullName>Lead Generator</fullName>
                </value>
                <value>
                    <fullName>Networking/COI</fullName>
                </value>
                <value>
                    <fullName>Purchase Order Finance</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnerships</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <description>Label - removed ? mark (02/21/17)</description>
        <label>How did you hear about us</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current Customer</fullName>
                </value>
                <value>
                    <fullName>Internet Search</fullName>
                </value>
                <value>
                    <fullName>Mag/Newspaper Ad</fullName>
                </value>
                <value>
                    <fullName>Mailer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Post Card</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Statement/Bill Insert</fullName>
                </value>
                <value>
                    <fullName>TV Commercial</fullName>
                </value>
                <value>
                    <fullName>QLMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_services_offered__c</fullName>
        <description>Label change from &quot;What other services do they offer?&quot; to &quot;What other services do you offer&quot; 02/2117</description>
        <label>What other services do you offer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paper_they_concentrate_on__c</fullName>
        <description>Label change from &quot;Paper they concentrate on?&quot; to &quot;Paper you concentrate on&quot;</description>
        <label>Paper you concentrate on</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>A/B</fullName>
                </value>
                <value>
                    <fullName>A/B/C</fullName>
                </value>
                <value>
                    <fullName>B/C</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Channel__c</fullName>
        <label>Partner Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Based Lending</fullName>
                </value>
                <value>
                    <fullName>Credit Card Processors</fullName>
                </value>
                <value>
                    <fullName>Equipment Leasing</fullName>
                </value>
                <value>
                    <fullName>Banks</fullName>
                </value>
                <value>
                    <fullName>Credit Unions</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Strategic Partnership</fullName>
                </value>
                <value>
                    <fullName>Financial Institutions Group</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Ext__c</fullName>
        <label>Phone Ext</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Partner_Category__c.object
<CustomObject>
    <description>This object holds the categories selected for each Partner Channel Account.</description>
    <fields>
        <fullName>Partner_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Partner_Account_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/PartnerCategoryLead__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting For Lead</description>
    <label>PartnerCategoryLead</label>
</CustomObject>

Rapid Prd/src/classes/LeadCloneController.cls
public with sharing class LeadCloneController{

    public PageReference onCancel() {
        PageReference  p = new PageReference ('/00Q/o');
        return p;
    }
    
    ApexPages.StandardController leadController;
    public SelectOption[] leftOptions { get;set;}
    public SelectOption[] rightOptions { get;set;}
    public CampaignMember tempMember { get;set;}
    public SelectOption[] selectedLCats { get;set;}
    public SelectOption[] allLCats { get;set;}
    public Lead parentDetails{ get;set;}
    public String rId;
    
    public LeadCloneController()
    {
        
        rId = Apexpages.currentPage().getParameters().get('parentId'); // Lead Id
        parentDetails=new Lead();
        
        
        if(rId !=null)
        {
            parentDetails=[SELECT 
                                    id,name, Company, Status,FirstName, Salutation, Leadsource, LastName,
                                    HasOptedOutOfFax, Email, Phone, HasOptedOutOfEmail, Phone_Ext__c,
                                    Campaign_Name_Upload__c, MobilePhone, Street, City, State,category__c,
                                    postalcode,Country, Partner_Channel__c,How_did_you_hear_about_us__c,
                                    Other_services_offered__c, Paper_they_concentrate_on__c, Average_dollar_amount_funded__c,
                                    NumberOfEmployees, Rating, Fax 
                           from
                                   Lead
                           where
                                   id=: rId  Limit 1];

        }
        
              
       // leadController = controller;
        generateData();
        rightOptions=new List<SelectOption>();
        leftOptions=new List<SelectOption>();
     
         String str1='';
         for(PartnerCategoryLead__c cTemp :[SELECT Name, id FROM PartnerCategoryLead__c])
         {
             leftOptions.add(new Selectoption(cTemp.name, cTemp.name));
             if(str1=='')
                 str1=str1+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             else
                 str1=str1+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             
         }
         
         leftOptionsHidden=str1;
         System.debug('str1' +leftOptionsHidden);
         if(rId!=null)
         {
             str1='';
             for(Partner_Category__c cTemp :[select name from Partner_Category__c where Partner_Lead__c = : rId])
             {
                 rightOptions.add(new Selectoption(cTemp.name, cTemp.name));
                 if(str1=='')
                     str1=str1+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
                 else
                     str1=str1+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             } 
             rightOptionsHidden=str1;
             System.debug('str1' +rightOptionsHidden);
         } 
         
         
         generateData();  
    }
    
    public LeadCloneController(ApexPages.StandardController controller) 
    {
        rId = Apexpages.currentPage().getParameters().get('parentId'); // Lead Id
        parentDetails=new Lead();
        
        
        if(rId !=null)
        {
            parentDetails=[SELECT 
                                    id,name, Company, Status,FirstName, Salutation, Leadsource, LastName,
                                    HasOptedOutOfFax, Email, Phone, HasOptedOutOfEmail, Phone_Ext__c,
                                    Campaign_Name_Upload__c, MobilePhone, Street, City, State,category__c,
                                    postalcode,Country, Partner_Channel__c,How_did_you_hear_about_us__c,
                                    Other_services_offered__c, Paper_they_concentrate_on__c, Average_dollar_amount_funded__c,
                                    NumberOfEmployees, Rating
                           from
                                   Lead
                           where
                                   id=: rId  Limit 1];

        }
        
              
        leadController = controller;
        generateData();
        rightOptions=new List<SelectOption>();
        leftOptions=new List<SelectOption>();
     
         String str1='';
         for(PartnerCategoryLead__c cTemp :[SELECT Name, id FROM PartnerCategoryLead__c])
         {
             leftOptions.add(new Selectoption(cTemp.name, cTemp.name));
             if(str1=='')
                 str1=str1+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             else
                 str1=str1+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             
         }
         
         leftOptionsHidden=str1;
         System.debug('str1' +leftOptionsHidden);
         if(rId!=null)
         {
             str1='';
             for(Partner_Category__c cTemp :[select name from Partner_Category__c where Partner_Lead__c = : rId])
             {
                 rightOptions.add(new Selectoption(cTemp.name, cTemp.name));
                 if(str1=='')
                     str1=str1+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
                 else
                     str1=str1+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8')+'&'+EncodingUtil.urlEncode(cTemp.name,'UTF-8');
             } 
             rightOptionsHidden=str1;
             System.debug('str1' +rightOptionsHidden);
         }   
 
    }
    /** Commented By -MK Conam 18 Nov 2015 **/
   /**  private void setOptions(SelectOption[] options, String value)
    {
        options.clear();
        String[] parts = value.split('&');

        for (Integer i = 0; i <parts.size() / 2; i++)
        {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }
    }
    **/
    // Backing for hidden text field containing the options from the left list
    public String leftOptionsHidden {
        get;
        set {
            system.debug('left 1' +value + ' '+leftOptions);
            
            leftOptionsHidden = value;
           // setOptions(leftOptions, value);
        }
    }

    // Backing for hidden text field containing the options from the right list
    public String rightOptionsHidden {
        get;
        set {
            system.debug('right 1' +value + ' '+rightOptionsHidden );
            rightOptionsHidden = value;
            //setOptions(rightOptions, value);
        }
    }

    public void generateData() {
    
       tempMember = new CampaignMember();

        if (rId != null)
        {
           // leadObj  = [SELECT Id, Partner_Channel__c FROM Lead where id = : rId ];
            selectedLCats = new List <SelectOption> ();
            List <String> LCategories = generateList([SELECT Name, id FROM PartnerCategoryLead__c]);
            List <String> CategoryByLead = generateList([select name from Partner_Category__c where Partner_Lead__c = : rId ]);

            //create set to remove selected element
            Set <String> setLCats = new Set <String> ();
            setLCats.addAll(LCategories);
            
            Set <String> setCatByLead = new Set <String> ();
            
            setCatByLead.addAll(CategoryByLead);
            
            setLCats.removeAll(setCatByLead);
            
            allLCats = new List <SelectOption> ();
            
            for (String c: setLCats) {
                allLCats.add(new SelectOption(c, c));
            }
            
            for (String c: setCatByLead) {
                selectedLCats.add(new SelectOption(c, c));
            }


        }

       leftOptions = allLCats;
        System.debug('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX '+allLCats);
        System.debug('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX '+selectedLCats);
        rightOptions = selectedLCats;

    }

     private List <String> generateList(List <sobject> sobj) 
    {
        System.debug(sobj);
        List <String> retStr = new List <String> ();
        for (sobject sTemp: sobj) 
        {
            if (sTemp.getSObjectType() == Partner_Category__c.sObjectType) 
            {
                sTemp = (Partner_Category__c) sTemp;
            } 
            else if (sTemp.getSObjectType() == PartnerCategoryLead__c.sObjectType) 
            {

                sTemp = (PartnerCategoryLead__c) sTemp;
            }

            retStr.add(String.valueOf(sTemp.get('Name')));
        }
        return retStr;
    }  

    public PageReference onSave() 
    {
        PageReference p=null;
        SavePoint sp = Database.setSavePoint();
        try
        {
            
            sp=Database.setSavePoint();
            Lead newLead=new Lead();
            
            newLead.Company=parentDetails.Company;
            newLead.Status=parentDetails.Status;
            newLead.FirstName=parentDetails.FirstName; 
            newLead.Salutation=parentDetails.Salutation; 
            newLead.Leadsource=parentDetails.LeadSource; 
            newLead.LastName=parentDetails.Lastname;               
            newLead.HasOptedOutOfFax=parentDetails.HasOptedOutOfFax; 
            newLead.Email=parentDetails.email;
            newLead.Phone=parentDetails.phone; 
            newLead.HasOptedOutOfEmail=parentDetails.HasOptedOutOfEmail; 
            newLead.Phone_Ext__c=parentDetails.Phone_Ext__c;
            newLead.MobilePhone=parentDetails.MobilePhone; 
            newLead.Street=parentDetails.Street; 
            newLead.City=parentDetails.City; 
            newLead.State=parentDetails.State;
            newLead.category__c=parentDetails.category__c;
            newLead.postalcode=parentDetails.postalcode;
            newLead.Country=parentDetails.Country; 
            newLead.Partner_Channel__c=parentDetails.Partner_Channel__c;
            newLead.How_did_you_hear_about_us__c=parentDetails.How_did_you_hear_about_us__c;
            newLead.Other_services_offered__c=parentDetails.Other_services_offered__c; 
            newLead.Paper_they_concentrate_on__c=parentDetails.Paper_they_concentrate_on__c; 
            newLead.Average_dollar_amount_funded__c=parentDetails.Average_dollar_amount_funded__c;
            newLead.NumberOfEmployees=parentDetails.NumberOfEmployees; 
            newLead.Rating=parentDetails.Rating;
            
                                    
            insert newLead;
            
            CampaignMember cml = new CampaignMember();
            cml.campaignid = tempMember.campaignId;
            cml.leadid =newLead.id;
            insert cml ;
            
            List <SelectOption> options = new List <SelectOption> ();
            
            String[] parts = rightOptionsHidden.split('&');
    
            system.debug('rightOptionsHidden' +rightOptionsHidden);
            for (Integer i = 0; i <parts.size() / 2; i++) {
                options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
                EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
            }
            system.debug('options is ' +options );
            List <Partner_Category__c> newRecordsList = new List <Partner_Category__c> ();
   
            String message='';
            integer sortOrderL = 0;
            for (SelectOption so: options) 
            {
                sortOrderL++;
                Partner_Category__c newRecord = new Partner_Category__c();
                
                newRecord.Partner_Lead__c = newLead.id;
                newRecord.Name = so.getLabel();
                newRecord.Sort_Order__c = sortOrderL;
                newRecordsList.add(newRecord); 
                message=message+';'+so.getLabel();
                
            }
             system.debug('newRecordsList is ' +newRecordsList);
              system.debug('rId is ' +rId);
           system.debug('message is ' +message);
           system.debug('newRecordsList is ' +newRecordsList.size());
            if (newRecordsList.size()> 0)
            {
                newLead.Category__c = message;
                update newLead;
                insert newRecordsList;
            } 
            
            p=new PageReference('/'+newLead.id) ;  

        }
        catch(Exception e)
        {
            ApexPages.Message msg=new ApexPages.Message(ApexPages.Severity.Fatal,e.getMessage()+'@'+e.getLineNumber());
            ApexPages.addMessage(msg);
            Database.Rollback(sp);
            p=null;
        }
        return p;

    }
}