Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadID__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LeadID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Ownership_Change__c.object
<CustomObject>
    <description>Custom object to track changes in ownership/assignment for Leads and Opportunities. Will be retroactive to encompass &quot;original&quot; Lead IDs for converted Leads.</description>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Ownership Changes</relationshipLabel>
        <relationshipName>Ownership_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_OwnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>New Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ownership_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Old_OwnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ownership_Changes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ownership Change</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Change Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/OwnerAssignments.cls
public class OwnerAssignments {
   public static void Record(String[] Ids, String[] OldOwners, String[] NewOwners) {
      List<Ownership_Change__c> toInsert = new List<Ownership_Change__c>();
      Integer counter = 0;
      for (String id : Ids) {
         Ownership_Change__c oc = new Ownership_Change__c (
            Old_OwnerId__c = OldOwners[counter],
            New_OwnerId__c = NewOwners[counter]
         );
         if (id.substring(0, 3) == '006') {   // Carry out additional instructions for Opps
         }
         else { oc.LeadId__c = id; }   // Populate Lead Id
         toInsert.add(oc);
         counter++;
      }  // end for
      if (toInsert.size() > 0) {
         try { insert toInsert; }
         catch (DMLException e) {   }
      }
   }     // end Record method
}    // end class