Rapid Prd/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>RC_Status__c</fullName>
        <description>External status as reported from Rock Connections</description>
        <label>RC Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Attempted to Contact</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Sleeping</fullName>
                </value>
                <value>
                    <fullName>Pitched</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Follow-Up</fullName>
                </value>
                <value>
                    <fullName>Converted to Opportunity</fullName>
                </value>
                <value>
                    <fullName>Installed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Transferred to 3rd party</fullName>
                </value>
                <value>
                    <fullName>Signature Received - Scheduled Install</fullName>
                </value>
                <value>
                    <fullName>Profile Call Complete</fullName>
                </value>
                <value>
                    <fullName>Profile Statements Received</fullName>
                </value>
                <value>
                    <fullName>Presentation Complete</fullName>
                </value>
                <value>
                    <fullName>Folder Documents Received</fullName>
                </value>
                <value>
                    <fullName>Signature Received</fullName>
                </value>
                <value>
                    <fullName>Folder Complete</fullName>
                </value>
                <value>
                    <fullName>Calling - No Contact Made</fullName>
                </value>
                <value>
                    <fullName>Initial Call Needed</fullName>
                </value>
                <value>
                    <fullName>Contact - Pending Profile Call</fullName>
                </value>
                <value>
                    <fullName>Pending Bank Card Statements</fullName>
                </value>
                <value>
                    <fullName>Pending Folder Document</fullName>
                </value>
                <value>
                    <fullName>Pending Presentation</fullName>
                </value>
                <value>
                    <fullName>Pending Profile</fullName>
                </value>
                <value>
                    <fullName>Pending Signature</fullName>
                </value>
                <value>
                    <fullName>Folder Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/RC_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Rock Connections&apos; Status to our Lead Status</description>
    <fields>
        <fullName>Local_Status__c</fullName>
        <description>Local value of the Status field to use</description>
        <label>Local Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Rock Connections Status</label>
</CustomObject>

Rapid Prd/src/objects/User_Default__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of default values to be used for Apex code</description>
    <fields>
        <fullName>UserID__c</fullName>
        <description>18 character ID value for the requested User</description>
        <label>User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>User Defaults</label>
</CustomObject>

Rapid Prd/src/classes/TestLeads.cls
@isTest

// Test class for Lead triggers/classes

private class TestLeads {

   private static testMethod void testLead_Insert() {
      /* COMMENTED BY DS-CONAM 
      LeadUtils.setTesting();   // Mark this is an Apex test
      */   // Mark this is an Apex test
      Test.startTest();
      User u = new User();
      u.Alias = 'rc';
      u.Username = 'rc@test.com';
      u.FirstName = 'Test';
      u.LastName = 'Testo';
      u.Email = 'rc@test.com';
      u.EmailEncodingKey = 'UTF-8';
      u.LanguageLocaleKey = 'en_US';
      u.LocaleSidKey = 'en_US';
      u.TimeZoneSidKey = 'America/New_York';
      u.ProfileId='00e30000000h0BsAAI';
      u.UserPermissionsMarketingUser = true;
      u.UserPermissionsOfflineUser = true;
      u.IsActive = true;
      Database.SaveResult sr = Database.insert(u);
      String UserId = sr.getId();
      
      User_Default__c ud = new User_Default__c();
      ud.Name = 'Rock Connections';
      ud.UserId__c = UserId;
      insert ud;

      // Test LeadSharing afterInsert trigger
      Lead l = new Lead(
         FirstName = 'Test',
         LastName  = 'Testofferson',
         Company   = 'Test Industries LLC',
         Email     = 'test@test.com',
         Phone     = '1-800-555-TEST'
      );
      
      l.OwnerId    = '00570000001B1yvAAC';
      l.LeadSource = 'Lead Generation';
      insert l;
      Test.stopTest();
   }  // end testLeadSharing_Insert method
   
   private static testMethod void testLead_Update() {
      /* COMMENTED BY DS-CONAM 
      LeadUtils.setTesting();   // Mark this is an Apex test
      */    // Mark this is an Apex test
      Test.startTest();
      User u = new User();
      u.Alias = 'rc';
      u.Username = 'rc@test.com';
      u.FirstName = 'Test';
      u.LastName = 'Testo';
      u.Email = 'rc@test.com';
      u.EmailEncodingKey = 'UTF-8';
      u.LanguageLocaleKey = 'en_US';
      u.LocaleSidKey = 'en_US';
      u.TimeZoneSidKey = 'America/New_York';
      u.ProfileId='00e30000000h0BsAAI';
      u.UserPermissionsMarketingUser = true;
      u.UserPermissionsOfflineUser = true;
      u.IsActive = true;
      Database.SaveResult sr = Database.insert(u);
      String UserId = sr.getId();
      
      User_Default__c ud = new User_Default__c();
      ud.Name = 'Rock Connections';
      ud.UserId__c = UserId;
      insert ud;

      // Test LeadSharing afterInsert trigger
      Lead l = new Lead(
         FirstName = 'Test',
         LastName  = 'Testofferson',
         Company   = 'Test Industries LLC',
         Email     = 'test@test.com',
         Phone     = '1-800-555-TEST'
      );
      
      l.LeadSource = 'Lead Generation';
      sr = Database.insert(l);
      
      l.Id = sr.getId();
      l.OwnerId = '00570000001B1yvAAC';
      update l;
      Test.stopTest();
   }  // end testLeadSharing_Update method
   
   private static testMethod void testRC_Status() {
      // Test to see if a Lead gets the proper status update via Rock Connections
      
      Test.startTest();
      RC_Status__c test_status = new RC_Status__c();
      test_status.Name = 'RC Open';
      test_status.Local_Status__c = 'Rock Connections Test';
      insert test_status;
      
      RC_Status__c test_rcs = new RC_Status__c();
      test_rcs = RC_Status__c.getInstance('RC Open');
      system.debug(' *** ' + test_rcs.Local_Status__c);
      
      Lead l = new Lead(
         FirstName = 'Test',
         LastName  = 'Testofferson',
         Company   = 'Test Industries LLC',
         Email     = 'test@test.com',
         Phone     = '1-800-555-TEST',
         RC_Status__c = 'RC Open',
         Status = 'Test'
      );
      Database.SaveResult sr = Database.insert(l);
      
      Lead l_check = [SELECT Id,Status FROM Lead WHERE Email='test@test.com' LIMIT 1];
      System.assertEquals('Rock Connections Test',l_check.Status);
      Test.stopTest();
   }

}