Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>Opportunity_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Marbles</relationshipLabel>
        <relationshipName>Marbles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Marble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marble</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marbles__c</fullName>
        <formula>IF(AND(OR( ISPICKVAL( StageName , &quot;Unqualified&quot;)), Channel_Logic_for_Reporting__c = &quot;Direct&quot;),
IF(AND( CALC_FICO__c &gt;= 600,(TODAY()- Business_Open_Date__c)&gt;= (365*2)),&quot;SmartBiz&quot;,&quot;Not Applicable&quot;),&quot;Not Applicable&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marbles</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/updateMarbleCheckboxOnOpp.cls
public class updateMarbleCheckboxOnOpp
{
    public static void deleteScanerio(List<Marble__c> lstMarble)
    {
        set<Id> oppId = new set<Id>();
        
        for(Marble__c marbTemp : lstMarble)
        {
            {
                oppId.add(marbTemp.Opportunity_Reference__c);
            }                
            
        }
        
        List<Opportunity> oppList = new List<Opportunity>();
        for(Opportunity oppTemp : [Select Id,(Select Opportunity_Reference__c from Marbles__r) from Opportunity where Id IN : oppId])
        {
            if(oppTemp.Marbles__r.size() <= 0)
            {
                oppTemp.Marble__c = false;
                
            }
            
            oppList.add(oppTemp);
        }
        
        if(!oppList.isEmpty()) update oppList;
    }    
}