Rapid Prd/src/objects/Marble__c.object
<CustomObject>
    <description>Custom Object to house all our Broker Out Leads / Opportunities</description>
    <fields>
        <fullName>BOOP_Status__c</fullName>
        <label>BOOP Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Based__c</fullName>
        <label>Home Based?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Marbles</relationshipLabel>
        <relationshipName>Marbles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Where_Did_You_Find_This_Client__c</fullName>
        <label>Where Did You Find This Client?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BA Transfer</fullName>
                </value>
                <value>
                    <fullName>Credit Karma</fullName>
                </value>
                <value>
                    <fullName>BOBA Dialer</fullName>
                </value>
                <value>
                    <fullName>Custom List</fullName>
                </value>
                <value>
                    <fullName>Email Blast</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>UW Unqual</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Sr BA Qualified</fullName>
                </value>
                <value>
                    <fullName>Dialer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Marble</label>
    <nameField>
        <label>Marble Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marbles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Home_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home-Based</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marble__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marble</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/updateMarbleCheckboxOnOppTest.cls
@isTest
public class updateMarbleCheckboxOnOppTest
{
    @isTest
    public static void updateMarbleCheckbox()
    {
        Test.startTest();
        
        opportunity opp=new opportunity ();
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today();
        opp.Name = 'Test Opportunity';
        opp.LeadSource = 'Radio';
        opp.ForecastCategoryName = 'Pipeline';
        insert opp;
        
        Opportunity oppRecord =[select id,Name from Opportunity where id =: opp.id];
        System.assertEquals(oppRecord.Name, 'Test Opportunity');
        
        Marble__c m = new Marble__c();
        m.Home_Based__c = 'Yes';
        m.Where_Did_You_Find_This_Client__c = 'Renewal';
        m.Name = 'abc';
        m.BOOP_Status__c = 'New';
        m.Opportunity_Reference__c = opp.Id;
        insert m;
        
        Marble__c marbleRecord =[select id,Name from Marble__c where id =:m.id];
        System.assertEquals(marbleRecord.Name, 'abc');    
        
        delete m;
        
        Test.stopTest();
     } 
        
        
}