Rapid Prd/src/objects/Merchant__c.object
<CustomObject>
    <label>Merchant</label>
    <nameField>
        <displayFormat>Merchant-{0000}</displayFormat>
        <label>Merchant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Opp_RD_Permission_Set__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in New Opp Tab</description>
    <fields>
        <fullName>Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Qual__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre-Qual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processing_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processing/CS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Promac_UW__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promac - UW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QC_Exuser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>QC team restricted access for 1.       Main Business

2.       Applicant &amp; Credit

3.       Statements

4.       Business Review

5.       Site Surveys

6.       RADocs</description>
        <label>QC Exuser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tab_Order__c</fullName>
        <label>Tab Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Underwriting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Underwriting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vf_Page_Name__c</fullName>
        <label>Vf Page Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opp RD Permission Set</label>
</CustomObject>

Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Underwriting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriting</label>
        <referenceTo>Underwriting__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Sales_Check_List__c.object
<CustomObject>
    <label>Sales Check List</label>
    <nameField>
        <label>Sales Check List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Check Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Underwriting__c.object
<CustomObject>
    <label>Underwriting</label>
    <nameField>
        <displayFormat>U# {000000000}</displayFormat>
        <label>Underwriting ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/MainClass3.cls
public class MainClass3 {

    public OppObject_Detail objOppDetail {get;set;}
    public Opportunity opp {get;set;}
    public Merchant__c mer {get;set;}
    public Sales_Check_List__c salesCheckList {get;set;}
    public list <OpportunityDetailTabs> objOpportunityDetail {get;set;}


    public MainClass3() 
    {
        InitializeClass();
    }

    public MainClass3(ApexPages.StandardController controller) 
    {
        InitializeClass();
    }

    public void InitializeClass() 
    {
        ID OppId = ApexPages.CurrentPage().getParameters().get('Id');
        objOppDetail = new OppObject_Detail('Opportunity Details', OppId);
        objOpportunityDetail = new list <OpportunityDetailTabs> ();

        List <PermissionSetAssignment> userPSA = [Select
                                                            Id, PermissionSetId, AssigneeId, SystemModstamp
                                                    From
                                                            PermissionSetAssignment
                                                    Where
                                                            AssigneeId = : UserInfo.getUserId()
                                                    AND
                                                            PermissionSet.profileId = NULL];
        if (userPSA.size()> 0)
        {
            List <PermissionSet> pSet = [Select
                                                Id, Label
                                        FROM
                                                PermissionSet
                                        Where
                                                Id = : userPSA[0].PermissionSetId];
                                    
            for (Opp_RD_Permission_Set__c orps: Opp_RD_Permission_Set__c.getAll().values())
            {
                if (IsPermissionsMatch(pSET[0].Label, orps))
                {
                    objOpportunityDetail.add(new OpportunityDetailTabs(orps.Vf_Page_Name__c, orps.Name, orps.tab_order__c));
                }
            }
            objOpportunityDetail.sort();

        }
        else 
        {
            objOpportunityDetail.add(new OpportunityDetailTabs('ErrorPage', 'Error Message', 0));
        }
    }

    private boolean IsPermissionsMatch(String permissionLabel, Opp_RD_Permission_Set__c orps) {
        boolean matched = false;
        System.debug(permissionLabel + ' pmkil ' + orps.QC_Exuser__c);
        if ((permissionLabel == 'Operations - Management (All)' && orps.Management__c == true) || 
            (permissionLabel == 'Operations - Pre-Qual' && orps.Pre_Qual__c == true) || 
            (permissionLabel == 'Operations - Processing' && orps.Processing_CS__c == true) || 
            (permissionLabel == 'Operations - QC' && orps.QC__c == true) || 
            (permissionLabel == 'Operations - UW' && orps.Underwriting__c == true) || 
            (permissionLabel == 'Promac - UW' && orps.Promac_UW__c == true) || 
            (permissionLabel == 'Operations - QC ExUser' && orps.QC_Exuser__c == true))
                matched = true;

        return matched;
    }

    public class OpportunityDetailTabs implements Comparable {
        public String oppId {get;set;}
        public String tabName {get;set;}
        public String vfPageName {get;set;}
        public Decimal tabOrder {get;set;}
        
        public OpportunityDetailTabs(String vfPageName, String tabName, Decimal tabOrder) {
            this.vfPageName = vfPageName;
            this.tabName = tabName;
            this.oppId = apexpages.currentpage().getparameters().get('Id');
            this.tabOrder = tabOrder;
        }

        public Integer compareTo(Object compareTo) {
            Integer result = 0;
            OpportunityDetailTabs oppTab = (OpportunityDetailTabs) compareTo;
            
            result=(this.tabOrder == oppTab.tabOrder) ? 0 : (this.tabOrder > oppTab.tabOrder) ? 1 : -1;
            return result; 

        }
    }
}