Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>If_Renewal_Preceding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>If Renewal, Preceding Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Renewal_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Balance__c</fullName>
        <formula>If_Renewal_Preceding_Opportunity__r.Remaining_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Sold Remaining (PO)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/Previous_Balance_Ctrl.cls
public with sharing class Previous_Balance_Ctrl 
{
    public Opportunity oppRecord{get; set;}     
    public Previous_Balance_Ctrl()
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');        
        if (oppId != null && oppId.trim() != '')
        {
             List<Opportunity> oppList = [SELECT 
                                                 Id,If_Renewal_Preceding_Opportunity__c,Previous_Balance__c 
                                         FROM 
                                                 Opportunity 
                                         WHERE 
                                                 Id = :oppId LIMIT 1];
                                            
            if (!oppList.isEmpty()) 
            {
                oppRecord = oppList.get(0);
            }
        }
        else 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
    
    public PageReference doSave() 
    {
           
        try
        {
            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Previous Balance Information Saved Successfully!'));
        }
        catch(Exception e)
        { 
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    } 
}