Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Days_to_Repay__c</fullName>
        <label>Estimated Days to Complete</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Term_Days__c</fullName>
        <label>Business Days to Collect (Loan)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RequiredDoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RequiredDoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daily_Percentage__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumOfPayments__c</fullName>
        <label>Number Of Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Oppr_Offers</relationshipLabel>
        <relationshipName>Oppr_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product 1</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr_Offer</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppr_Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/SendAcceptedOffers.cls
/**
 *********************************************************************************************************************
 * Module Name   : SendAcceptedOffers Webservice
 * Description   :  This method will get Opp Offers for Biz2Credit
 * Throws        : <Any Exceptions/messages thrown by this class/triggers>
 * Calls         : <Any classes/utilities called by this class | None if it does not call>
 * Test Class    :
 *
 * Organization  : Rainmaker Associates LLC
 *
 * Revision History:-
 * Version  Date           Author           WO#         Description of Action
 * 1.0      12/19/2012     Milligan                 Initial Version
 *******************************************************************************************************************
 **/
 @RestResource(urlMapping = '/SendAcceptedOffers/*')
global with sharing class SendAcceptedOffers {

    @HttpPost
    global static ReturnSendOfferDetails doPost(OpportunityOffer ofr) {

        RestResponse res = RestContext.response;

        Oppr_Offer__c oppOffer = new Oppr_Offer__c();
        if (ofr.Source == 'B2C') {
            ofr.Source = 'Biz2Credit';
        }
        if (ofr.Source != null && ofr.Source != 'Biz2Credit') {
            res.StatusCode = 400;
            res.addHeader('Error', 'Invalid Source System - HTTP Error 400');
            return new ReturnSendOfferDetails('false', 'Invalid Source System - HTTP Error 400', 'Null');
        }

        if (ofr != null && (ofr.ExternalID <> NULL && ofr.ExternalID <> '')) {

            String id = ofr.ExternalID;
            System.debug('SendAcceptedOffers WS OffierID==>' + ofr.OfferID);
            System.debug('SendAcceptedOffers WS id==>' + id);

            Opportunity opp = new Opportunity();

            opp = [SELECT 
                        id, external_id__c, status__c 
                    FROM 
                        Opportunity 
                    WHERE 
                        Source_System__c = 'Biz2Credit'
                    AND 
                        External_ID__c = : id LIMIT 1];


            if (opp.id <> null)
            {
                try
                {
                    System.debug('XXXXXXXXxxxxxxxxxx '+ofr.OfferID);
                    oppOffer = [select 
                                        id, Status__c 
                                from 
                                        Oppr_Offer__c 
                                where 
                                        name = : ofr.OfferID LIMIT 1];
                    oppOffer.Status__c = 'Accepted';
                    opp.Amount = oppOffer.Amount__c;
                    opp.Percent_Payback__c = oppOffer.Daily_Percentage__c;
                    opp.Pay_Back_Amount__c = oppOffer.Amount_Sold__c;
                    opp.Estimated_Days_to_Repay__c = oppOffer.Duration__c;
                    opp.Product__c = oppOffer.Product__c;
                    opp.Loan_Term_Days__c = oppOffer.NumOfPayments__c;
                    upsert oppOffer;
                }
                catch (QueryException ex)
                {
                    System.debug('Exception ex...' + ex.getMessage());
                    res.StatusCode = 400;
                    res.addHeader('Error', 'Invalid Offer ID');
                    return new ReturnSendOfferDetails('false', 'Invalid Offer ID', 'Null');

                }
                // Validation Rule 5a                   
                if (opp.Status__c == 'Qualified Offer') {

                    List <Oppr_Document__c> odcList = new List <Oppr_Document__c> ();
                    odcList = [SELECT 
                                        id 
                                FROM 
                                        Oppr_Document__c 
                                WHERE 
                                        RequiredDoc__c = true 
                                AND 
                                        status__c in ('Requested', 'Rejected') 
                                And 
                                        Opportunity__c = : opp.id];
                    System.debug('SendAcceptedOffers WS odc ==>' + odcList.size());

                    if (!odcList.IsEmpty()) {
                        opp.status__c = 'Documents Requested';
                    } else {
                        opp.status__c = 'Reviewing Documents';
                    }
                }
                try
                {
                    update opp;
                }
                catch (QueryException ex)
                {
                    System.debug('Exception ex...' + ex.getMessage());
                }
            }

        }
        return new ReturnSendOfferDetails('true', 'Success', oppOffer.id);
    }


    global class ReturnSendOfferDetails {

        global Integer totalSize = 0;
        global String message;
        global String oppOfferCreatedID;

        global ReturnSendOfferDetails(String success, String message, String oppOfr) {
            this.totalSize = 1;
            this.message = message;
            this.oppOfferCreatedID = oppOfr;

        }
    }
}