Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Document__c.object
<CustomObject>
    <description>Opportunity Document will hold the list of documents requested and Contract details related to the Opportunity</description>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Additional Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opprtunity_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr Document</label>
    <nameField>
        <displayFormat>D-{000000000}</displayFormat>
        <label>Doccument Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rapid Prd/src/classes/GetDocumentList.cls
/***********************************************************************************************************************
* Module Name   : GetDocumentList Webservice
* Description   :  This method will  find  Oppr_Doc__c   for Biz2Credit 
* Throws        : <Any Exceptions/messages thrown by this class/triggers>
* Calls         : <Any classes/utilities called by this class | None if it does not call>
* Test Class    :  
* 
* Organization  : Rainmaker Associates LLC
*
* Revision History:-
* Version  Date           Author           WO#         Description of Action
* 1.0      12/16/2012     Milligan                 Initial Version
*******************************************************************************************************************
**/ 
@RestResource(urlMapping='/GetDocumentList/*')
global with sharing class GetDocumentList 
{
    
    @HttpGet
    global static ReturnDocmentListDetails doGet() 
    { 
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;   
            
        List<Oppr_Document__c> oppDocRows = new List<Oppr_Document__c>();
        List<OpportunityDocs> oppDocList = new List<OpportunityDocs>();     
        
              
        String externalId = '';
            
         if(RestContext.request.params.get('id') != null && RestContext.request.params.get('SourceSystem') != null)
         {    
        
            externalId = RestContext.request.params.get('id');
            String source = RestContext.request.params.get('SourceSystem');
            
            if ('B2C'.equals(source)) 
            {
                source = 'Biz2Credit';
            }
            
            if (!'Biz2Credit'.equals(source)) 
            {
                res.StatusCode  = 400;
                res.addHeader('Error','Invalid Source System!');                   
                return new ReturnDocmentListDetails('false', 'Invalid Source System!', oppDocList);
            }
            
          
                    
            Opportunity opp = new Opportunity();
        
                opp = [SELECT 
                          id, external_id__c, Status__c 
                       FROM 
                          Opportunity 
                       WHERE  
                          Source_System__c =: source 
                       AND 
                          External_ID__c =: externalId limit 1]; 
 
           
                oppDocRows = [SELECT 
                                Id, Name, Document_Name__c,Additional_Notes__c,Description__c, Status__c 
                              FROM 
                                Oppr_Document__c  
                              WHERE 
                                opportunity__c=:opp.id 
                              AND 
                                Status__c in ('Requested','Rejected')];
                
           
            if(!oppDocRows.IsEmpty()){
                
                for(Oppr_Document__c oList: oppDocRows)
                {
                     OpportunityDocs od = new OpportunityDocs();
                     od.DocumentID =  oList.Name;
                     od.DocumentName = oList.Document_Name__c;
                     od.AdditionalNotes = oList.Additional_Notes__c;
                     od.Description = oList.Description__c;
                     od.Status = oList.Status__c;
                     oppDocList.add(od);
                    
                }
                
            } 
            else
            {
                res.StatusCode  = 400;
                    res.addHeader('Error','No documents found!');                   
                return new ReturnDocmentListDetails('false', 'No documents found!', oppDocList);
            }

        } 
        else 
        {
            res.StatusCode  = 400;
                res.addHeader('Error','ExternalID or Source System is missing!');           
            return new ReturnDocmentListDetails('false', 'ExternalID or Source System is missing!', oppDocList);
            
        }
        return new ReturnDocmentListDetails('Success', externalId , oppDocList);

    }
    
        
    global class ReturnDocmentListDetails 
    {
    
        global Integer totalSize = 0;
        global String message;
        global List<OpportunityDocs> oppDocListRecords;
    
        global ReturnDocmentListDetails(String success, String message, List<OpportunityDocs> records) 
        {
            
            if(records.size() > 0)
                this.totalSize = records.size();
                this.message = message;
                this.oppDocListRecords = records;
        }
    }    


}