Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_CC_sales_Avg_4_Mo_times_12__c</fullName>
        <label>Annual CC sales (Avg 4 Mo. times 12):</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Gross_sales_Avg_2_Mo_times_12__c</fullName>
        <label>Annual Gross sales (Avg 2 Mo. times 12):</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Category__c</fullName>
        <inlineHelpText>If updated with new category, add similar to &quot;What type of Business is it?&quot; in UW Object.</inlineHelpText>
        <label>Business Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Antiques/Collectibles</fullName>
                </value>
                <value>
                    <fullName>Appliance Stores</fullName>
                </value>
                <value>
                    <fullName>Arrangements</fullName>
                </value>
                <value>
                    <fullName>Art Galleries</fullName>
                </value>
                <value>
                    <fullName>Audio Equipment</fullName>
                </value>
                <value>
                    <fullName>Automobile Dealerships New/Used</fullName>
                </value>
                <value>
                    <fullName>Automotive - Body Repair, Collision, Painting</fullName>
                </value>
                <value>
                    <fullName>Automotive - Brake and Muffler</fullName>
                </value>
                <value>
                    <fullName>Automotive - General Repair, Truck, RV</fullName>
                </value>
                <value>
                    <fullName>Automotive - Parts, Accessories</fullName>
                </value>
                <value>
                    <fullName>Automotive - Quick Sevice, Lube, Tune-Up</fullName>
                </value>
                <value>
                    <fullName>Automotive - Tire, Glass</fullName>
                </value>
                <value>
                    <fullName>Automotive - Towing &amp; Emergency Road Service</fullName>
                </value>
                <value>
                    <fullName>Automotive - Transmission</fullName>
                </value>
                <value>
                    <fullName>Bar</fullName>
                </value>
                <value>
                    <fullName>Barber Shop</fullName>
                </value>
                <value>
                    <fullName>Bicycle Repair</fullName>
                </value>
                <value>
                    <fullName>Bicycles/Motorcycles Shops</fullName>
                </value>
                <value>
                    <fullName>Bicycle Sales</fullName>
                </value>
                <value>
                    <fullName>Billing Services</fullName>
                </value>
                <value>
                    <fullName>Boating/Marina</fullName>
                </value>
                <value>
                    <fullName>Book and Stationary</fullName>
                </value>
                <value>
                    <fullName>Bowling</fullName>
                </value>
                <value>
                    <fullName>Bridal Shop</fullName>
                </value>
                <value>
                    <fullName>Car Alarm Supplier</fullName>
                </value>
                <value>
                    <fullName>Carpet Store</fullName>
                </value>
                <value>
                    <fullName>Car Wash</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Check Cashing Companies</fullName>
                </value>
                <value>
                    <fullName>Cigar Cigarette &amp; Tobacco Dealer-Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <label>Business Status:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dissolved</fullName>
                </value>
                <value>
                    <fullName>Good Standing</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>Not In good Standing</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Canada Not Available</fullName>
                </value>
                <value>
                    <fullName>Delinquent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Tax_Lien_Date_Filed__c</fullName>
        <inlineHelpText>If entering a single date use the format: &quot;MM/DD/YYYY&quot;
If entering multiple dates use a semicolon &apos;;&apos; and a space &apos; &apos; to seperate the dates. E.G.: &quot;MM/DD/YYYY; MM/DD/YYYY; MM/DD/YYYY....&quot;</inlineHelpText>
        <label>Date(s) Lien Filed</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRR</label>
        <referenceTo>Credit_Related_Reporting__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC_Company_in_business_6_months__c</fullName>
        <label>Company in business &lt; 1 year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Yes Starter</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_UCC_Filings__c</fullName>
        <label>Other UCC Filings:</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processor_Name__c</fullName>
        <inlineHelpText>If updated, update also current processor field</inlineHelpText>
        <label>New Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Bancard Central</fullName>
                </value>
                <value>
                    <fullName>Benchmark</fullName>
                </value>
                <value>
                    <fullName>Card Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Century Bankcard</fullName>
                </value>
                <value>
                    <fullName>Chosen Payment Systems</fullName>
                </value>
                <value>
                    <fullName>CoCard</fullName>
                </value>
                <value>
                    <fullName>Cynergy</fullName>
                </value>
                <value>
                    <fullName>Daily ACH</fullName>
                </value>
                <value>
                    <fullName>Daily Fixed-Amount ACH</fullName>
                </value>
                <value>
                    <fullName>Direct Connect</fullName>
                </value>
                <value>
                    <fullName>Electronic Payments Inc.</fullName>
                </value>
                <value>
                    <fullName>Electronic Processing Services, LLC</fullName>
                </value>
                <value>
                    <fullName>Elite Data-ChasePaymentech</fullName>
                </value>
                <value>
                    <fullName>EVO</fullName>
                </value>
                <value>
                    <fullName>Evolution Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First American Payment Systems</fullName>
                </value>
                <value>
                    <fullName>First Data</fullName>
                </value>
                <value>
                    <fullName>First Data – Omaha</fullName>
                </value>
                <value>
                    <fullName>ForwardLine</fullName>
                </value>
                <value>
                    <fullName>Humboldt Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Integrity</fullName>
                </value>
                <value>
                    <fullName>I-Payment</fullName>
                </value>
                <value>
                    <fullName>IRN Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Lockbox-KBT</fullName>
                </value>
                <value>
                    <fullName>Mercury</fullName>
                </value>
                <value>
                    <fullName>Merrick</fullName>
                </value>
                <value>
                    <fullName>Moneris/Canada</fullName>
                </value>
                <value>
                    <fullName>MPI</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIC_CODE__c</fullName>
        <label>SIC CODE</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Entity__c</fullName>
        <label>Type of Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Partnership</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Unable To Confirm by QC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/BusinessReview_Ctrl.cls
/*
@Name               : BusinessReview_Ctrl 
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        :  
@Revision History   : Uses of Field onfirmed_business_information_from_qc__c Commented/Removed By MK Conam 2 Dec 2015
*/

public class BusinessReview_Ctrl 
{

     public Opportunity oppRecord{get; set;}
     public Account accRecord{get; set;}
     public String CreditAlert{get; private set;} 
     public String SCFAlert{get; private set;} 
     public String BusinessCategoryAlert{get; private set;}
     public String BusinessAlertCount{get; private set;}
     public String CriteriaDecision{get; private set;}
     public String isTheBusinessTypeConsideredLuxury{get; private set;}
     
     
     public BusinessReview_Ctrl(){
         String oppId = ApexPages.currentPage().getParameters().get('Id');
        
        if (oppId != null && oppId.trim() != ''){
            List<Opportunity> oppList = [SELECT 
                                                Id,Type_of_Entity__c, Business_Status__c, AccountId, Other_UCC_Filings__c, 
                                                EC_Company_in_business_6_months__c, Business_Tax_Lien_Date_Filed__c, 
                                                Annual_CC_sales_Avg_4_Mo_times_12__c, Current_Processor__c, 
                                                Annual_Gross_sales_Avg_2_Mo_times_12__c, Processor_Name__c, SIC_CODE__c,
                                                Business_Category__c,CRR__c, CRR__r.FICO__c, Merchant_Website__c
                                        FROM 
                                                Opportunity 
                                        WHERE 
                                                Id = :oppId LIMIT 1];
                                            
            if (!oppList.isEmpty()) {
                oppRecord = oppList.get(0); 
            }
            // Business Alerts
            creditAlert = FormulaFieldUtility.QCConditionalCriteria;
            SCFAlert =  FormulaFieldUtility.QCSCFAlert;
            BusinessCategoryAlert = FormulaFieldUtility.QCBusinessCategoryAlert;
            BusinessAlertCount = FormulaFieldUtility.BABusinessAlertCount;
            CriteriaDecision = FormulaFieldUtility.ECCriteriaDecision;
            isTheBusinessTypeConsideredLuxury = FormulaFieldUtility.BAIsTheBusinessTypeConsideredLuxury;
               
            
        }else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
     
     
    
    public PageReference doSave() {
           
        try{
            if(oppRecord != null) {
                upsert oppRecord;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Business Review Information Saved Successfully!'));
            }
        }catch(Exception e){

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    } 
    
}