Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Processing_Representative__c</fullName>
        <description>What RapidAdvance Processing Rep has this account?</description>
        <label>Processing Representative</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atiya</fullName>
                </value>
                <value>
                    <fullName>Cassandra</fullName>
                </value>
                <value>
                    <fullName>Destinie</fullName>
                </value>
                <value>
                    <fullName>Mark Deputy</fullName>
                </value>
                <value>
                    <fullName>Shawntavia</fullName>
                </value>
                <value>
                    <fullName>Tina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Employee__c</fullName>
        <label>Risk Employee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deborah Oliver</fullName>
                </value>
                <value>
                    <fullName>Gil Bowen</fullName>
                </value>
                <value>
                    <fullName>Marlowe Rogers</fullName>
                </value>
                <value>
                    <fullName>Tony Brown</fullName>
                </value>
                <value>
                    <fullName>Vanessa Waller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Risk_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fires off a workflow to send an Email notification</description>
        <label>Send Risk Alert</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/User_Lookup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Quick reference list of emails associated with particular strings, for conversion from Picklist values.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>User Lookup</label>
</CustomObject>

Rapid Prd/src/classes/TestRiskAlert.cls
@isTest

private class TestRiskAlert 
{

   static testMethod void testRiskAlert() 
   {  
      Test.startTest();
      User_Lookup__c test1 = new User_Lookup__c(Name = 'test1', Email__c = 'test@test.com');
      insert test1;
      User_Lookup__c test2 = new User_Lookup__c(Name = 'test2', Email__c = 'test2@test.com');
      insert test2;
      
      Opportunity o = new Opportunity();
      o.Name = 'Test Opp';
      o.CloseDate = Date.today();
      o.stageName='Prospecting';
      Database.SaveResult sr = Database.insert(o);
      
      String oppId = sr.GetId();
      o.Processing_Representative__c = 'test1';
      o.Risk_Employee__c = 'test2';
      update o;
      
      Opportunity[] o_query = [SELECT 
                                      Id,Send_Risk_Alert__c 
                                  FROM 
                                      Opportunity 
                                  WHERE 
                                      Id=: oppId];
      Test.stopTest();
   }
}