Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CRR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRR</label>
        <referenceTo>Credit_Related_Reporting__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactID__c</fullName>
        <formula>Contact__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/CBRTesting_Ctrl.cls
//existing Test Class TestPreQual_ctrl

public class CBRTesting_Ctrl {

    public Opportunity oppRecord {get;set;}

    public CBRTesting_Ctrl() 
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');

        if (oppId != null && oppId.trim() != '') 
        {
            List <Opportunity> oppList = [SELECT 
                                                Id, CRR__c, ContactID__c
                                          FROM
                                                Opportunity 
                                          WHERE 
                                                Id = : oppId LIMIT 1];

            if (!oppList.isEmpty()) 
            {
                oppRecord = oppList.get(0);
            }
        } 
        else 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Id Does not Exist!'));
        }
    }


    public PageReference doSave() 
    {
        try 
        {
            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'CBR Testing Saved Successfully!'));
        } 
        catch (Exception e) 
        {
            System.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }
/* commented out DS-CONAM- 07/30/2015
    public PageReference doCBRIntegration() 
    {
        try 
        {
            // have to add code             
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm, 'CBR Integrate successfully.'));
        } catch (Exception e) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }

*/

}