Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pre_Qual_Decision_Date__c</fullName>
        <label>Pre-Qual Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Qual_Decision__c</fullName>
        <label>Pre-Qual Decision</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FAIL</fullName>
                    <color>#FF0000</color>
                </value>
                <value>
                    <fullName>PASS</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>PASS CREDIT ONLY REQUEST</fullName>
                </value>
                <value>
                    <fullName>Pending Management Review</fullName>
                    <color>#F3D904</color>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Qual_FAIL_Reason__c</fullName>
        <label>Pre-Qual FAIL Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adverse Filing - Bankruptcy No Discharge</fullName>
                </value>
                <value>
                    <fullName>Adverse Filing - High Competitor Balance</fullName>
                </value>
                <value>
                    <fullName>BAM - Match</fullName>
                </value>
                <value>
                    <fullName>BS - Avg. &lt;5x DRA</fullName>
                </value>
                <value>
                    <fullName>BS - Avg. Daily Balance &lt;$5000</fullName>
                </value>
                <value>
                    <fullName>BS - Competitor NSFs</fullName>
                </value>
                <value>
                    <fullName>BS - MCA &gt;3 unpaid competitor NSFs</fullName>
                </value>
                <value>
                    <fullName>BS - MCA Negative MEB</fullName>
                </value>
                <value>
                    <fullName>BS - MoM decline in gross sales</fullName>
                </value>
                <value>
                    <fullName>BS - Non factoring company &lt;5 deposits</fullName>
                </value>
                <value>
                    <fullName>BS - YoY decline in gross sales</fullName>
                </value>
                <value>
                    <fullName>Bus - Below min. Loan Amount $15,001</fullName>
                </value>
                <value>
                    <fullName>Bus - Below min. Loan Amount $5,001</fullName>
                </value>
                <value>
                    <fullName>Bus - Documentation Discrepencies</fullName>
                </value>
                <value>
                    <fullName>Bus - Inconsistent Fluctuation/Seasonal</fullName>
                </value>
                <value>
                    <fullName>Bus - Open Tax Liens w/o payment plan</fullName>
                </value>
                <value>
                    <fullName>Bus - Prohibited List</fullName>
                </value>
                <value>
                    <fullName>Bus - State Law Requirements</fullName>
                </value>
                <value>
                    <fullName>CC - &lt;12 batches</fullName>
                </value>
                <value>
                    <fullName>CC - High Risk Tender Shift</fullName>
                </value>
                <value>
                    <fullName>CC - MoM decline in volume</fullName>
                </value>
                <value>
                    <fullName>CC - YoY decline in Volume</fullName>
                </value>
                <value>
                    <fullName>Competitor Balance- 40% Rule</fullName>
                </value>
                <value>
                    <fullName>Construction - No Tax liens No Pymt plan</fullName>
                </value>
                <value>
                    <fullName>Credit - Bankruptcy Filed w/No Discharge</fullName>
                </value>
                <value>
                    <fullName>Credit - Bankruptcy filing w/in 1yr</fullName>
                </value>
                <value>
                    <fullName>Credit - Does not meet FICO score req.</fullName>
                </value>
                <value>
                    <fullName>Credit - Does not meet Product Req.</fullName>
                </value>
                <value>
                    <fullName>Credit - Multiple Bankruptcies Filings</fullName>
                </value>
                <value>
                    <fullName>Credit- No Fico Score</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Qual_Pending_Date__c</fullName>
        <label>Pre-Qual Pending Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Qual_Person__c</fullName>
        <label>Pre-Qual Person</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aisha T</fullName>
                </value>
                <value>
                    <fullName>Alexandra P</fullName>
                </value>
                <value>
                    <fullName>Alex S</fullName>
                </value>
                <value>
                    <fullName>Andre P</fullName>
                </value>
                <value>
                    <fullName>Donte B</fullName>
                </value>
                <value>
                    <fullName>Dylan M</fullName>
                </value>
                <value>
                    <fullName>Eric A</fullName>
                </value>
                <value>
                    <fullName>Ericka H</fullName>
                </value>
                <value>
                    <fullName>Evan C</fullName>
                </value>
                <value>
                    <fullName>Greg D</fullName>
                </value>
                <value>
                    <fullName>John A</fullName>
                </value>
                <value>
                    <fullName>Kayla Larson</fullName>
                </value>
                <value>
                    <fullName>Kris Johnson</fullName>
                </value>
                <value>
                    <fullName>LaMesa Logan</fullName>
                </value>
                <value>
                    <fullName>Marilyn M</fullName>
                </value>
                <value>
                    <fullName>Mark D</fullName>
                </value>
                <value>
                    <fullName>Mauricio S</fullName>
                </value>
                <value>
                    <fullName>Pamela S</fullName>
                </value>
                <value>
                    <fullName>Shawntavia T</fullName>
                </value>
                <value>
                    <fullName>Theresa D</fullName>
                </value>
                <value>
                    <fullName>Vashia U</fullName>
                </value>
                <value>
                    <fullName>Veronica W</fullName>
                </value>
                <value>
                    <fullName>Windy C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Qual_Unqualified_Reasons__c</fullName>
        <label>Pre-Qual Unqualified Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;12 separate daily deposits per month</fullName>
                </value>
                <value>
                    <fullName>Administratively Dissolved</fullName>
                </value>
                <value>
                    <fullName>Bank Statement(s) not legible</fullName>
                </value>
                <value>
                    <fullName>Business Inactive</fullName>
                </value>
                <value>
                    <fullName>Business is for sale</fullName>
                </value>
                <value>
                    <fullName>Business Not on Good Standing</fullName>
                </value>
                <value>
                    <fullName>Business Suspended</fullName>
                </value>
                <value>
                    <fullName>Credit Card Statement(s) not legible</fullName>
                </value>
                <value>
                    <fullName>Current Advance Payoff Too High</fullName>
                </value>
                <value>
                    <fullName>Does Not Meet Minimum Monthly Credit Card Volume</fullName>
                </value>
                <value>
                    <fullName>Drop in CC Sales Month over Month</fullName>
                </value>
                <value>
                    <fullName>Drop in CC Sales Year over Year</fullName>
                </value>
                <value>
                    <fullName>LESS THAN $2500 PER MONTH IN CREDIT CARD PROCESSING</fullName>
                </value>
                <value>
                    <fullName>LESS THAN $3500 PER MONTH IN CREDIT CARD PROCESSING</fullName>
                </value>
                <value>
                    <fullName>Less than 12 deposits per day</fullName>
                </value>
                <value>
                    <fullName>LESS THAN 1 YEAR IN BUSINESS</fullName>
                </value>
                <value>
                    <fullName>Less than 6 months in business</fullName>
                </value>
                <value>
                    <fullName>Less than 9 months remaining on lease</fullName>
                </value>
                <value>
                    <fullName>Low Advance Amount Loan Product</fullName>
                </value>
                <value>
                    <fullName>Merchant applying does not have majority ownership</fullName>
                </value>
                <value>
                    <fullName>Merchant couldn&apos;t/wouldn&apos;t produce docs</fullName>
                </value>
                <value>
                    <fullName>Minimum advance amount $2500</fullName>
                </value>
                <value>
                    <fullName>Minimum advance amount $5000</fullName>
                </value>
                <value>
                    <fullName>Monitor Processing</fullName>
                </value>
                <value>
                    <fullName>Moving Location</fullName>
                </value>
                <value>
                    <fullName>No Payment Plan</fullName>
                </value>
                <value>
                    <fullName>On prohibited list</fullName>
                </value>
                <value>
                    <fullName>PRE EXISTING PAYOFF FIGURES BALANCE &gt;$50K</fullName>
                </value>
                <value>
                    <fullName>Significant Decrease in Credit Card Volume</fullName>
                </value>
                <value>
                    <fullName>Time in business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/PreQual_Ctrl.cls
public class PreQual_Ctrl 
{
    public Opportunity oppRecord{get; set;}
    
    public PreQual_Ctrl()
    {
        String oppId = ApexPages.currentPage().getParameters().get('Id');        
        if (oppId != null && oppId.trim() != '')
        {
            List<Opportunity> oppList = [SELECT 
                                                Id, Pre_Qual_Person__c, Pre_Qual_Decision__c, Pre_Qual_Pending_Date__c,
                                                Pre_Qual_Decision_Date__c, Pre_Qual_FAIL_Reason__c, Pre_Qual_Unqualified_Reasons__c                                             
                                           FROM 
                                                Opportunity 
                                           WHERE 
                                                Id = :oppId LIMIT 1];
                                            
            if (!oppList.isEmpty()) 
            {
                oppRecord = oppList.get(0);               
            }
        }
        else 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));   
        }    
    }
    
    public PageReference doSave() 
    {           
        try
        {
            upsert oppRecord;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Pre-Qual Information Saved Successfully!'));
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    }
}