Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Processor__c</fullName>
        <inlineHelpText>If updated, update also new processor field</inlineHelpText>
        <label>Current Processor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1st federal financial</fullName>
                </value>
                <value>
                    <fullName>1st First Source Bank</fullName>
                </value>
                <value>
                    <fullName>Abanco INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>ABC Global Systems</fullName>
                </value>
                <value>
                    <fullName>Advanced Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alliant Financial Services</fullName>
                </value>
                <value>
                    <fullName>Allied Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Alpha Card</fullName>
                </value>
                <value>
                    <fullName>Alpine Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Ameribank National</fullName>
                </value>
                <value>
                    <fullName>American Credit Card Processing, Corp</fullName>
                </value>
                <value>
                    <fullName>American Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAVINGS BANK</fullName>
                </value>
                <value>
                    <fullName>AmeriMerchant Payment Systems</fullName>
                </value>
                <value>
                    <fullName>AMI-Merchant Solutions</fullName>
                </value>
                <value>
                    <fullName>Approval Payment Solutions</fullName>
                </value>
                <value>
                    <fullName>Appstar Financial</fullName>
                </value>
                <value>
                    <fullName>Atlantic Stewardship Bank</fullName>
                </value>
                <value>
                    <fullName>Authorize Net</fullName>
                </value>
                <value>
                    <fullName>AVFUEL</fullName>
                </value>
                <value>
                    <fullName>Axia Corp.</fullName>
                </value>
                <value>
                    <fullName>Bancard Payment Systems</fullName>
                </value>
                <value>
                    <fullName>Bancfirst</fullName>
                </value>
                <value>
                    <fullName>BanCorpSouth</fullName>
                </value>
                <value>
                    <fullName>BankCard Central</fullName>
                </value>
                <value>
                    <fullName>Bank Card Depot</fullName>
                </value>
                <value>
                    <fullName>Bank Card Services</fullName>
                </value>
                <value>
                    <fullName>Bankcard USA</fullName>
                </value>
                <value>
                    <fullName>Banker&apos;s Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Bank of America Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Blue Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>If_Renewal_Preceding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>If Renewal, Preceding Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Renewal_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/classes/ContactRolesOppr_UnitTest.cls
/*******************************************************************************************************************
** Module Name   : ContactRolesOppr
** Description   : Test class to cover ContactRolesOppr 
** Throws        : NA
** Calls         : NA
** Test Class    : it is a test class
** 
** Organization  : Algoworks
**
** Revision History:-
** Version             Date            Author           WO#         Description of Action
** 1.0                                   RainMaker                        Initial Version
******************************************************************************************************************/
/*
Modified
DS-CONAM - 03/04/2015
@isTest(SeeAllData = TRUE) TO false
changed Version from 16 to 32

*/


@isTest(SeeAllData = FALSE)
public with sharing class ContactRolesOppr_UnitTest 
{
    Static TestMethod Void estMethod1()
    {
        Test.startTest();
        CALC.ApexTesting();
        RecordType rt = [SELECT id FROM RecordType WHERE sobjecttype = 'Opportunity' AND name = 'New Opportunity' LIMIT 1 ];
        Campaign camp = new Campaign();
        camp.Name = 'TestCamp';
        camp.Type = 'Internet';
        Insert camp;
        system.debug('>>>camp>>>'+camp);
        
        Account Acc = TestUtils.createAccount();
        system.debug('>>>Acc>>>'+Acc);
        Contact con = TestUtils.createContact(Acc);
        system.debug('>>con>>>>'+con);
                
        Opportunity opp = new Opportunity();
        opp.Name = 'TestingOpp';
        opp.LeadSource = 'A001';
        opp.CampaignId = camp.id;
        opp.CloseDate = date.newInstance(2007, 5, 5);
        opp.StageName = 'Prospecting';
        opp.Current_Processor__c = 'Blue Pay';
       
       //added DS-CONAM
        opp.accountid=acc.id;
        insert opp;
        system.debug('>>>opp>>>'+opp);
        
        OpportunityContactRole oppConRole = TestUtils.createOpportunityContactRole(con, opp);
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'TestingOpp';
        opp1.LeadSource = 'A001';
        opp1.CampaignId = camp.id;
        opp1.CloseDate = date.newInstance(2007, 5, 5);
        opp1.StageName = 'Prospecting';
        opp1.Current_Processor__c = 'Blue Pay';
        opp1.If_Renewal_Preceding_Opportunity__c = opp.id;
        
        //added DS-CONAM
        opp1.accountid=acc.id;
        insert opp1;
        system.debug('>>>opp1>>>'+opp);
        
        Test.stopTest();
        
    }

}