Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System</description>
        <label>Source System</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QC in Progress</fullName>
                </value>
                <value>
                    <fullName>File Review</fullName>
                </value>
                <value>
                    <fullName>Qualified Offer</fullName>
                </value>
                <value>
                    <fullName>No Offer Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Documents</fullName>
                </value>
                <value>
                    <fullName>Documents Requested</fullName>
                </value>
                <value>
                    <fullName>Contract Available</fullName>
                </value>
                <value>
                    <fullName>Reviewing Contract</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Funding In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed - Funded</fullName>
                </value>
                <value>
                    <fullName>Offer Rescinded</fullName>
                </value>
                <value>
                    <fullName>File Accepted</fullName>
                </value>
                <value>
                    <fullName>Submitted For Funding Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Oppr_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Sold__c</fullName>
        <label>Amount Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daily_Payment__c</fullName>
        <label>Daily Payment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daily_Percentage__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOC_Drawterm__c</fullName>
        <label>LOC Drawterm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOC_Fee__c</fullName>
        <label>LOC Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LOC_Limit__c</fullName>
        <label>LOC Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LOC_totalterm__c</fullName>
        <label>LOC Totalterm</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumOfPayments__c</fullName>
        <label>Number Of Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Oppr_Offers</relationshipLabel>
        <relationshipName>Oppr_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product 1</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Oppr_Offer</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oppr_Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/GetOffers.cls
/**
*********************************************************************************************************************
* Module Name   : GetOffers Webservice
* Description   :  This method will   
* Throws        : <Any Exceptions/messages thrown by this class/triggers>
* Calls         : <Any classes/utilities called by this class | None if it does not call>
* Test Class    :  
* 
* Organization  : Rainmaker Associates LLC
*
* Revision History:-
* Version  Date           Author           WO#         Description of Action
* 1.0      12/16/2012     Milligan                 Initial Version
*******************************************************************************************************************
**/ 
@RestResource(urlMapping='/GetOffers/*')
global with sharing class GetOffers 
{
    
    @HttpGet
    global static  ReturnOfferDetails  doGet() 
    { 
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        List<Oppr_Offer__c> oppOfferRows = new List<Oppr_Offer__c>();
        List<OpportunityOffer> oppOfferList = new List<OpportunityOffer>();     
        
         if(RestContext.request.params.get('id') != null && RestContext.request.params.get('SourceSystem') != null)
         {    
        
            String id = RestContext.request.params.get('id');
            String source = RestContext.request.params.get('SourceSystem');
        
            if (source == 'B2C') 
            {
                source = 'Biz2Credit';
            }
            Opportunity opp = new Opportunity();
                opp = [SELECT 
                           id, external_id__c, Status__c 
                       FROM 
                           Opportunity 
                       WHERE  
                           Source_System__c =: source 
                       AND 
                           External_ID__c =: id limit 1]; 
 
                if(opp.id <> null)
                {
                    oppOfferRows = [SELECT 
                                        Product__c, OwnerId, Opportunity__c, NumOfPayments__c,Notes__c, Name, Id, 
                                        Duration__c, Daily_Percentage__c,Daily_Payment__c, CreatedDate,
                                        Amount__c, Amount_Sold__c, 
                                        LOC_Drawterm__c, LOC_Fee__c, LOC_Limit__c, 
                                        LOC_totalterm__c 
                                    FROM 
                                        Oppr_Offer__c 
                                    WHERE  
                                        opportunity__c =: Opp.id];
                }
                
                if(!oppOfferRows.IsEmpty())
                {
                
                    if(opp.Status__c != 'Qualified Offer' && opp.Status__c != 'Reviewing Documents')
                    {
                        res.StatusCode  = 400;
                        res.addHeader('Error','Offers not available. HTTP Error 400');                  
                        return new ReturnOfferDetails('false', 'Offers not available. HTTP Error 400', oppOfferList);
                    }
            
                    for(Oppr_Offer__c oppf: oppOfferRows)
                    {
                    
                        OpportunityOffer oppOff = new OpportunityOffer();
                    
                        oppOff.OfferID = oppf.Name;
                        oppOff.Amount = oppf.Amount__c;
                        oppOff.Notes = oppf.Notes__c;
                        oppOff.DailyCollection = oppf.Daily_Percentage__c;
                        oppOff.Duration = oppf.Duration__c;
                        oppOff.ProductName = oppf.Product__c;
                        oppOff.Purchase =  oppf.Amount_Sold__c; 
                        oppOff.DailyPayment = oppf.Daily_Payment__c; 
                        oppOff.LOC_Fee = oppf.LOC_Drawterm__c;
                        oppOff.LOC_Limit = oppf.LOC_Fee__c;
                        oppOff.LOC_Drawterm = oppf.LOC_Limit__c;
                        oppOff.LOC_totalterm = oppf.LOC_totalterm__c;
                        oppOff.NumOfPayments = oppf.NumOfPayments__c;                   
                        
                        oppOfferList.add(oppOff);
                    
                   }
            
            }
        }
        else
        {
            res.StatusCode  = 400;
            res.addHeader('Error','No Results Found');              
            return new ReturnOfferDetails('false', 'No Results Found', oppOfferList);           
        }
        
        return new ReturnOfferDetails('true', 'Success', oppOfferList);
    }
    
    global class ReturnOfferDetails 
    {
    
        global Integer totalSize = 0;
        global String message;
        global List<OpportunityOffer> offerOverrideList;
    
        global ReturnOfferDetails(String success, String message, List<OpportunityOffer> records) 
        {
            if(records.size() > 0)
                this.totalSize = records.size();
                this.message = message;
                this.offerOverrideList = records;
        }
    }   
    

}