Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AE_Calculator_Average__c</fullName>
        <label>AE Calculator Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Advance_ID__c</fullName>
        <externalId>true</externalId>
        <label>Advance ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Average_Daily_Repay__c</fullName>
        <label>Avg. Daily Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_Advance_Company__c</fullName>
        <description>Who does the merchant have an advance with now or in the past?</description>
        <label>Competitor Advance Company</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_ROI__c</fullName>
        <label>Current % ROI</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Est_Days_to_Repay__c</fullName>
        <label>Est. Days to Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Days_to_Repay__c</fullName>
        <label>Estimated Days to Complete</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Daily_Repay__c</fullName>
        <label>Expected Daily Pay</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_monthly_sales__c</fullName>
        <label>AE Calculator Gross Monthly Sales</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>If_Renewal_Preceding_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>If Renewal, Preceding Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Opportunities</relationshipLabel>
        <relationshipName>Renewal_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Term_Days__c</fullName>
        <label>Business Days to Collect (Loan)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Advance_Amount__c</fullName>
        <label>New Advance Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Advance_Price__c</fullName>
        <label>New Advance Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Payback_Price__c</fullName>
        <label>New Amount Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Percent_Payback__c</fullName>
        <label>New Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>New_Split__c</fullName>
        <label>New Split %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Paid_Off_Letter_Rec_d__c</fullName>
        <label>Paid Off Letter Rec&apos;d</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pay_Back_Amount__c</fullName>
        <label>Amount Sold</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payoff_Amount__c</fullName>
        <label>Payoff Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Paid_Off__c</fullName>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Payback__c</fullName>
        <label>Daily Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pre_Qual_Decision_Date__c</fullName>
        <label>Pre-Qual Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Previous_Balance__c</fullName>
        <formula>If_Renewal_Preceding_Opportunity__r.Remaining_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Sold Remaining (PO)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_FICO__c</fullName>
        <label>Previous Applicant #1 FICO</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Decline Program</fullName>
                </value>
                <value>
                    <fullName>High Risk Loan</fullName>
                </value>
                <value>
                    <fullName>Line of Credit</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Loan w/MCA pricing</fullName>
                </value>
                <value>
                    <fullName>Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Preferred Loan</fullName>
                </value>
                <value>
                    <fullName>Premium MCA</fullName>
                </value>
                <value>
                    <fullName>SBA Bridge Loan</fullName>
                </value>
                <value>
                    <fullName>Select Loan</fullName>
                </value>
                <value>
                    <fullName>Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication ACH Fixed</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/MCA Pricing</fullName>
                </value>
                <value>
                    <fullName>Syndication MCA</fullName>
                </value>
                <value>
                    <fullName>Syndication Starter Program</fullName>
                </value>
                <value>
                    <fullName>Syndication Loan w/ True-Up</fullName>
                </value>
                <value>
                    <fullName>Syndication Premium MCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Amount Sold (Previous Deal)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Funds__c</fullName>
        <label>Purpose of Funds</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buyout a partner</fullName>
                </value>
                <value>
                    <fullName>Expand business</fullName>
                </value>
                <value>
                    <fullName>Improvements</fullName>
                </value>
                <value>
                    <fullName>Marketing expense, promotion</fullName>
                </value>
                <value>
                    <fullName>Open a new location</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Past due Mortgage</fullName>
                </value>
                <value>
                    <fullName>Past due Rent</fullName>
                </value>
                <value>
                    <fullName>Past due vendor</fullName>
                </value>
                <value>
                    <fullName>Pay bills</fullName>
                </value>
                <value>
                    <fullName>Pay down Judgment</fullName>
                </value>
                <value>
                    <fullName>Pay down Tax Lien</fullName>
                </value>
                <value>
                    <fullName>Paying Off Third Party</fullName>
                </value>
                <value>
                    <fullName>Paying Off Third Party and Other</fullName>
                </value>
                <value>
                    <fullName>Pay off a tax lien</fullName>
                </value>
                <value>
                    <fullName>Payoff competitor and other</fullName>
                </value>
                <value>
                    <fullName>Payoff Judgment</fullName>
                </value>
                <value>
                    <fullName>Purchase new equipment, inventory</fullName>
                </value>
                <value>
                    <fullName>Renovations Business Remains Open</fullName>
                </value>
                <value>
                    <fullName>Seasonal - surplus cash for off-season</fullName>
                </value>
                <value>
                    <fullName>Working Capital</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QC_Calculator_Average__c</fullName>
        <label>QC Calculator Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QC_Gross_Monthly_Sales__c</fullName>
        <label>QC Calculator Gross Monthly Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Amount Sold Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renewal_Number__c</fullName>
        <label>Renewal Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tentative_Funding_Date__c</fullName>
        <description>This is the date we believe the deal will be funded.  When a date is put into this field, and auto email will go to the AE and the Partner if applicable.</description>
        <label>Tentative Funding Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Third_Party_Company_Name__c</fullName>
        <label>Third Party Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Third_Party_Payoff_Amount__c</fullName>
        <label>Third Party Payoff Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Repay_Amount__c</fullName>
        <label>Total Transactions Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UCC_Acknowledgement_Date__c</fullName>
        <label>UCC Acknowledgement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UCC_File_Number__c</fullName>
        <label>UCC File Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underwriting_Approval__c</fullName>
        <label>Underwriting Decision</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved by Credit Committee</fullName>
                </value>
                <value>
                    <fullName>Approved by Credit Committee with conditions</fullName>
                </value>
                <value>
                    <fullName>Auto Approved</fullName>
                </value>
                <value>
                    <fullName>Auto Declined</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Declined by Credit Committee</fullName>
                </value>
                <value>
                    <fullName>Declined - Pending Management Review</fullName>
                </value>
                <value>
                    <fullName>Pending Management Review</fullName>
                </value>
                <value>
                    <fullName>Pending management review returned to u/w</fullName>
                </value>
                <value>
                    <fullName>Rescinded by Processing</fullName>
                </value>
                <value>
                    <fullName>Rescinded by Underwriting</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Comp. Pay Off too High - Reconsider Later</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Will Not Reconsider</fullName>
                </value>
                <value>
                    <fullName>Unqualified - Will Reconsider in the Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X20_Day_Average_Daily_Repay__c</fullName>
        <label>20 Day Average Daily Transactions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Sales_Check_List__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Advance_Company__c</fullName>
        <label>Competitor Advance Company</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Check Lists</relationshipLabel>
        <relationshipName>Sales_Check_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Check List</label>
    <nameField>
        <label>Sales Check List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Check Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/DealTerms_Ctrl.cls
/*
@Name               : DealTerms_Ctrl 
@Author             : MK CONAM
@Date               : 2 DEC 2015
@Description        : 
@Revision History   : Uses of Field visa info__c,ucc_acknowledgement_date__c,Commented/Removed By MK Conam 2 Dec 2015
*/
public class DealTerms_Ctrl 
{
     public Opportunity oppRecord{get; set;}
     public String fundedAmount{get; private set;}
     public String EstimatedDailyTransactions{get; private set;}
     public string Percentage_comp{get;set;}
     public Sales_Check_List__c SalesChkFld{get;set;}
     List<Opportunity> oppList;
     String oppId;
     public DealTerms_Ctrl()
     {
        oppId = ApexPages.currentPage().getParameters().get('Id');
        
        if (oppId != null && oppId.trim() != '')
        {
            oppList = getOppList();
            if (!oppList.isEmpty()) 
            {
                        oppRecord = oppList.get(0);
                        
                        if(!oppRecord.Sales_Check_Lists__r.isEmpty())
                        {  
                            SalesChkFld = oppRecord.Sales_Check_Lists__r.get(0);
                        }
            }
            fundedAmount = FormulaFieldUtility.fundedAmount;
            if(FormulaFieldUtility.estimatedDailyRepay != null && !FormulaFieldUtility.estimatedDailyRepay.equals(''))
            {
                EstimatedDailyTransactions = ((Decimal.valueof(FormulaFieldUtility.estimatedDailyRepay)).setScale(2))+'';
            }
        }
        else 
        {  
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Id Does not Exist!'));  
        }    
    }
    
    public PageReference doSave()
    {           
        try
        {
            upsert oppRecord;
            List<Opportunity> tempOppList = getOppList();
            if(null != tempOppList)
            {
                oppRecord = tempOppList.get(0);
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Deal Terms Information Saved Successfully!'));
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
        }
        return null;
    }
    
    private list<Opportunity> getOppList(){
        return new list<Opportunity>{[SELECT 
                                                Id, Amount, Percent_Payback__c,Paid_Off_Letter_Rec_d__c, Pay_Back_Amount__c,Estimated_Days_to_Repay__c,Previous_FICO__c,
                                                Loan_Term_Days__c,QC_Calculator_Average__c, AE_Calculator_Average__c, Gross_monthly_sales__c,
                                                QC_Gross_Monthly_Sales__c,Remaining_Balance__c, Percent_Paid_Off__c,Competitor_Advance_Company__c,
                                                X20_Day_Average_Daily_Repay__c, Current_ROI__c, Total_Repay_Amount__c, 
                                                Purpose_of_Funds__c, New_Percent_Payback__c,ucc_file_number__c, New_Payback_Price__c, Product__c,ucc_acknowledgement_date__c,
                                                Average_Daily_Repay__c, Tentative_Funding_Date__c, Expected_Daily_Repay__c,  If_Renewal_Preceding_Opportunity__c,
                                                If_Renewal_Preceding_Opportunity__r.Current_ROI__c,third_party_company_name__c, If_Renewal_Preceding_Opportunity__r.Average_Daily_Repay__c,
                                                If_Renewal_Preceding_Opportunity__r.Total_Repay_Amount__c, If_Renewal_Preceding_Opportunity__r.Expected_Daily_Repay__c,
                                                If_Renewal_Preceding_Opportunity__r.Purchase_Amount__c,third_party_payoff_amount__c,Underwriting_Approval__c,
                                                If_Renewal_Preceding_Opportunity__r.Advance_ID__c, 
                                                If_Renewal_Preceding_Opportunity__r.X20_Day_Average_Daily_Repay__c,If_Renewal_Preceding_Opportunity__r.Renewal_Number__c,
                                                If_Renewal_Preceding_Opportunity__r.Remaining_Balance__c, If_Renewal_Preceding_Opportunity__r.Percent_Paid_Off__c,
                                                If_Renewal_Preceding_Opportunity__r.Pay_Back_Amount__c, Previous_Balance__c, New_Split__c, New_Advance_Amount__c,
                                                Est_Days_to_Repay__c,New_Advance_Price__c,Pre_Qual_Decision_Date__c, Existing_Competitor_Advance2__c, Payoff_Amount__c,
                                                Payoff_Check_Sent__c, Pre_Qual_Pending_Date__c,   Initial_File_Review_Complete__c, Approved_With_Conditions__c, 
                                                Third_Party_Payoff__c,QC_Decision__c,Pre_Qual_Decision__c, UCC_Filing__c, UCC_Date__c, Pre_Qual_Unqualified_Reasons__c,
                                                UCC_Filing_Reason__c, UCC_Ordered__c, Pre_Qual_FAIL_Reason__c, Decision_Date__c,QC_Decision_Date__c, 
                                                Re_Decision_Date__c, Decline_Reason__c, Rescind_Reason__c, Unqualified_Reason__c, Exceptions__c, Underwriter_s_Score__c,
                                                Underwriter_Assigned__c,Pre_Qual_Person__c, Site_Survey_Ordered__c, Site_Survey_Ordered_Due_Date__c, Site_Survey_Available__c,
                                                Site_Survey_Available_Due_Date__c, Initial_File_Review2__c,DS_Start_Date_Time__c,DS_Person__c,DS_Retrieved_All_Conditions__c,   
                                                Manual_Applicant_1_FICO_Score__c,Manual_Applicant_2_FICO_Score__c, CALC_FICO__c, cc_Applicant_1_FICO__c, Applicant_2_FICO__c,Manual_Applicant_1_FICO__c, 
                                                Purchase_Amount__c, QC_Person__c, (SELECT Competitor_Advance_Company__c FROM Sales_Check_Lists__r)
                                        FROM 
                                                Opportunity 
                                        WHERE 
                                                Id = :oppId LIMIT 1]};
                                            
    }
}