Rapid Prd/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Top</fullName>
                </value>
                <value>
                    <fullName>2 - High</fullName>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                </value>
                <value>
                    <fullName>4 - Low</fullName>
                </value>
                <value>
                    <fullName>5 - Cold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Rapid Prd/src/objects/Priority_Queue__c.object
<CustomObject>
    <description>Placeholder for reference objects to Opportunity or Lead to be sorted by workflow-assigned criteria</description>
    <fields>
        <fullName>Last_Activity_Date__c</fullName>
        <formula>IF(Opportunity__c &lt;&gt; NULL, Opportunity__r.LastActivityDate,
(IF(Lead__c &lt;&gt; NULL, Lead__r.LastActivityDate, NULL))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Priority Queue</relationshipLabel>
        <relationshipName>Priority_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Priority Queue</relationshipLabel>
        <relationshipName>Priority_Queue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <formula>IF(Opportunity__c &lt;&gt; NULL, TEXT(Opportunity__r.StageName),
(IF(Lead__c &lt;&gt; NULL, TEXT(Lead__r.Status), NULL))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage / Status</label>
        <type>Text</type>
    </fields>
    <label>Priority Queue</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Priority Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rapid Prd/src/classes/QueueTests.cls
@isTest

private class QueueTests {

    @testSetup static void setup()
    {
        Test.startTest();
        LeadUtils.setTesting();   
        CALC.ApexTesting();
        Lead l = new Lead(
        FirstName = 'Test',
        LastName  = 'Testofferson',
        Company   = 'Test Industries LLC',
        Email     = 'test@test.com',
        Phone     = '1-800-555-TEST'
        );
        insert l;
        
        Priority_Queue__c pq1 = new Priority_Queue__c(Name = l.Company,Lead__c=l.id,Priority__c = 1);
        insert pq1;
        
        Task LeadTask = new Task (
        Status   = 'Closed',
        Priority = 'High',
        Subject  = 'Test Task for Lead',
        WhoId    = l.id
        );
        insert LeadTask;
        Test.stopTest();
    }

   // Test the Lead trigger/sync, attempt to convert the Lead. Add tasks too.
    private static testMethod void testLeadQueue() 
    {
        Test.startTest();
        LeadUtils.setTesting();   
        CALC.ApexTesting();
        
        Id LeadId=[Select id from Lead where company='Test Industries LLC' Limit 1].id;
        List<Priority_Queue__c> q_query = [SELECT Id,Lead__c,Last_Activity_Date__c FROM Priority_Queue__c WHERE name='Test Industries LLC'];   
        
        String QueueId = q_query[0].Id;
        Queue_Sync.clearActed();
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(LeadId);
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        Test.stopTest();

    }
   
   // Test the Opp trigger/sync as well as related Status field/formula
    private static testMethod void testOppQueue() 
    {
        Test.startTest();
        LeadUtils.setTesting();   // Mark this is an Apex test
        CALC.ApexTesting();
        
        Opportunity o = new Opportunity(
        Name      = 'Test Opp',
        StageName = 'Open',
        CloseDate = Date.today()
        );
        Database.SaveResult sr = Database.insert(o);
        String OppId = sr.getId();

        List<Priority_Queue__c> q_query = [SELECT Id,Stage_Status__c FROM Priority_Queue__c WHERE Opportunity__c=:OppId];
        Test.stopTest();

    }
} // end class